pub(crate) const KA_GLYPHS: [&'static str;1235] = [
    "一",
    "何",
    "七",
    "飼",
    "示",
    "述",
    "序",
    "織",
    "税",
    "舌",
    "銭",
    "祖",
    "測",
    "八",
    "属",
    "損",
    "退",
    "銅",
    "徳",
    "犯",
    "版",
    "俵",
    "婦",
    "富",
    "九",
    "武",
    "複",
    "墓",
    "報",
    "防",
    "貿",
    "務",
    "綿",
    "余",
    "略",
    "十",
    "領",
    "域",
    "宇",
    "沿",
    "灰",
    "閣",
    "割",
    "株",
    "干",
    "巻",
    "待",
    "看",
    "危",
    "揮",
    "貴",
    "郷",
    "警",
    "穴",
    "絹",
    "憲",
    "源",
    "堂",
    "己",
    "后",
    "孝",
    "紅",
    "鋼",
    "刻",
    "穀",
    "砂",
    "裁",
    "策",
    "話",
    "蚕",
    "至",
    "姿",
    "視",
    "磁",
    "樹",
    "宗",
    "就",
    "衆",
    "縦",
    "開",
    "縮",
    "処",
    "署",
    "諸",
    "傷",
    "蒸",
    "針",
    "仁",
    "垂",
    "寸",
    "閉",
    "盛",
    "誠",
    "宣",
    "泉",
    "染",
    "善",
    "奏",
    "装",
    "層",
    "操",
    "友",
    "臓",
    "誕",
    "暖",
    "宙",
    "庁",
    "頂",
    "潮",
    "賃",
    "討",
    "党",
    "上",
    "達",
    "糖",
    "納",
    "脳",
    "拝",
    "肺",
    "俳",
    "班",
    "秘",
    "腹",
    "奮",
    "手",
    "陛",
    "補",
    "宝",
    "棒",
    "幕",
    "密",
    "盟",
    "模",
    "郵",
    "幼",
    "紙",
    "翌",
    "卵",
    "覧",
    "裏",
    "臨",
    "朗",
    "依",
    "違",
    "鋭",
    "煙",
    "書",
    "汚",
    "押",
    "欧",
    "菓",
    "靴",
    "掛",
    "汗",
    "缶",
    "患",
    "幾",
    "秋",
    "詰",
    "叫",
    "況",
    "挟",
    "偶",
    "隅",
    "掘",
    "傾",
    "軒",
    "枯",
    "山",
    "雇",
    "更",
    "肯",
    "荒",
    "郊",
    "香",
    "硬",
    "込",
    "歳",
    "咲",
    "雪",
    "脂",
    "湿",
    "舟",
    "柔",
    "緒",
    "召",
    "床",
    "昇",
    "畳",
    "触",
    "雨",
    "伸",
    "吹",
    "姓",
    "隻",
    "跡",
    "籍",
    "占",
    "双",
    "捜",
    "掃",
    "当",
    "燥",
    "憎",
    "贈",
    "袋",
    "替",
    "濯",
    "畜",
    "駐",
    "超",
    "沈",
    "飲",
    "珍",
    "泥",
    "滴",
    "殿",
    "塗",
    "逃",
    "塔",
    "筒",
    "鈍",
    "軟",
    "下",
    "知",
    "悩",
    "濃",
    "泊",
    "薄",
    "爆",
    "肌",
    "髪",
    "販",
    "瓶",
    "浮",
    "前",
    "膚",
    "舞",
    "封",
    "幅",
    "沸",
    "捕",
    "抱",
    "帽",
    "磨",
    "埋",
    "後",
    "溶",
    "腰",
    "踊",
    "粒",
    "了",
    "涼",
    "療",
    "涙",
    "零",
    "齢",
    "授",
    "湾",
    "腕",
    "離",
    "々",
    "脱",
    "較",
    "業",
    "遅",
    "思",
    "夜",
    "映",
    "画",
    "中",
    "出",
    "電",
    "会",
    "物",
    "返",
    "簡",
    "単",
    "直",
    "習",
    "困",
    "右",
    "持",
    "調",
    "引",
    "聞",
    "野",
    "村",
    "背",
    "高",
    "低",
    "長",
    "左",
    "短",
    "着",
    "楽",
    "川",
    "質",
    "問",
    "以",
    "多",
    "若",
    "太",
    "色",
    "止",
    "遠",
    "忙",
    "借",
    "茶",
    "入",
    "新",
    "教",
    "味",
    "白",
    "女",
    "青",
    "黒",
    "方",
    "運",
    "動",
    "体",
    "痛",
    "元",
    "気",
    "変",
    "男",
    "疲",
    "寝",
    "天",
    "頭",
    "図",
    "館",
    "探",
    "失",
    "礼",
    "少",
    "人",
    "自",
    "由",
    "無",
    "理",
    "言",
    "度",
    "集",
    "音",
    "決",
    "事",
    "二",
    "見",
    "切",
    "符",
    "悪",
    "実",
    "病",
    "治",
    "校",
    "心",
    "発",
    "番",
    "先",
    "英",
    "文",
    "法",
    "練",
    "貸",
    "森",
    "試",
    "験",
    "題",
    "全",
    "車",
    "部",
    "目",
    "号",
    "研",
    "究",
    "室",
    "連",
    "花",
    "仕",
    "経",
    "国",
    "済",
    "的",
    "難",
    "広",
    "同",
    "夏",
    "春",
    "必",
    "要",
    "交",
    "時",
    "通",
    "冬",
    "走",
    "重",
    "卒",
    "社",
    "勤",
    "屋",
    "午",
    "机",
    "間",
    "使",
    "寒",
    "暑",
    "冷",
    "誰",
    "急",
    "用",
    "頃",
    "内",
    "伝",
    "半",
    "欲",
    "初",
    "次",
    "最",
    "田",
    "石",
    "原",
    "駅",
    "辺",
    "道",
    "分",
    "然",
    "工",
    "所",
    "横",
    "信",
    "曲",
    "橋",
    "向",
    "地",
    "銀",
    "月",
    "角",
    "赤",
    "祝",
    "相",
    "談",
    "接",
    "料",
    "払",
    "期",
    "働",
    "火",
    "供",
    "彼",
    "泣",
    "降",
    "晴",
    "曇",
    "空",
    "夕",
    "準",
    "備",
    "三",
    "水",
    "歩",
    "歌",
    "足",
    "口",
    "世",
    "界",
    "医",
    "者",
    "配",
    "規",
    "木",
    "則",
    "正",
    "活",
    "考",
    "計",
    "奥",
    "様",
    "眠",
    "外",
    "不",
    "金",
    "昔",
    "洋",
    "寄",
    "風",
    "呼",
    "怒",
    "宿",
    "渡",
    "旅",
    "取",
    "土",
    "盗",
    "建",
    "宅",
    "申",
    "願",
    "主",
    "関",
    "特",
    "別",
    "僕",
    "日",
    "予",
    "定",
    "写",
    "真",
    "普",
    "意",
    "忘",
    "覚",
    "席",
    "君",
    "百",
    "熱",
    "死",
    "結",
    "婚",
    "式",
    "牛",
    "乳",
    "沢",
    "町",
    "他",
    "千",
    "飯",
    "答",
    "店",
    "愛",
    "合",
    "悲",
    "職",
    "員",
    "幸",
    "飛",
    "今",
    "耳",
    "嫌",
    "窓",
    "喜",
    "反",
    "対",
    "恋",
    "告",
    "許",
    "件",
    "小",
    "戻",
    "服",
    "曜",
    "品",
    "未",
    "完",
    "海",
    "島",
    "級",
    "顔",
    "休",
    "面",
    "企",
    "市",
    "頼",
    "第",
    "表",
    "将",
    "希",
    "場",
    "査",
    "学",
    "行",
    "係",
    "訳",
    "課",
    "続",
    "際",
    "望",
    "成",
    "功",
    "約",
    "束",
    "家",
    "受",
    "有",
    "点",
    "識",
    "感",
    "送",
    "数",
    "球",
    "遊",
    "招",
    "帰",
    "選",
    "講",
    "義",
    "役",
    "立",
    "論",
    "基",
    "厚",
    "勧",
    "般",
    "近",
    "養",
    "化",
    "科",
    "績",
    "型",
    "苦",
    "満",
    "増",
    "声",
    "現",
    "父",
    "在",
    "夢",
    "乗",
    "放",
    "協",
    "力",
    "賛",
    "説",
    "落",
    "名",
    "母",
    "機",
    "具",
    "詳",
    "解",
    "構",
    "情",
    "共",
    "存",
    "静",
    "流",
    "兄",
    "芸",
    "術",
    "光",
    "景",
    "驚",
    "助",
    "求",
    "留",
    "興",
    "深",
    "弟",
    "猫",
    "想",
    "像",
    "平",
    "位",
    "置",
    "進",
    "越",
    "庭",
    "勢",
    "姉",
    "性",
    "団",
    "弁",
    "護",
    "条",
    "影",
    "響",
    "訪",
    "参",
    "御",
    "妹",
    "果",
    "慣",
    "専",
    "攻",
    "趣",
    "賞",
    "誌",
    "復",
    "限",
    "確",
    "院",
    "来",
    "保",
    "証",
    "追",
    "便",
    "著",
    "代",
    "抜",
    "肩",
    "伺",
    "材",
    "起",
    "残",
    "念",
    "恥",
    "都",
    "洗",
    "州",
    "福",
    "側",
    "恐",
    "敗",
    "毎",
    "比",
    "倍",
    "詩",
    "素",
    "胸",
    "打",
    "厳",
    "優",
    "可",
    "形",
    "朝",
    "詞",
    "程",
    "命",
    "令",
    "容",
    "議",
    "印",
    "象",
    "句",
    "線",
    "晩",
    "輩",
    "倒",
    "応",
    "募",
    "制",
    "量",
    "各",
    "評",
    "判",
    "換",
    "族",
    "競",
    "争",
    "率",
    "得",
    "張",
    "価",
    "抑",
    "弱",
    "技",
    "律",
    "勉",
    "尊",
    "敬",
    "観",
    "種",
    "能",
    "延",
    "薬",
    "笑",
    "非",
    "常",
    "強",
    "客",
    "届",
    "舎",
    "暮",
    "怖",
    "息",
    "拾",
    "段",
    "暇",
    "預",
    "昨",
    "断",
    "承",
    "丸",
    "謝",
    "敵",
    "坊",
    "岸",
    "良",
    "散",
    "訓",
    "食",
    "支",
    "組",
    "守",
    "消",
    "商",
    "似",
    "冒",
    "険",
    "捨",
    "状",
    "年",
    "作",
    "態",
    "勇",
    "敢",
    "派",
    "再",
    "与",
    "案",
    "美",
    "絵",
    "農",
    "読",
    "描",
    "徒",
    "城",
    "激",
    "異",
    "総",
    "注",
    "改",
    "革",
    "任",
    "週",
    "抗",
    "身",
    "門",
    "禁",
    "根",
    "提",
    "稲",
    "耕",
    "営",
    "展",
    "回",
    "疑",
    "漁",
    "突",
    "批",
    "端",
    "列",
    "即",
    "指",
    "値",
    "熟",
    "明",
    "易",
    "皇",
    "権",
    "神",
    "免",
    "逆",
    "製",
    "偉",
    "故",
    "修",
    "早",
    "街",
    "停",
    "路",
    "章",
    "政",
    "府",
    "堅",
    "担",
    "産",
    "省",
    "昼",
    "輪",
    "老",
    "荷",
    "貧",
    "乏",
    "記",
    "清",
    "給",
    "費",
    "刺",
    "才",
    "紹",
    "介",
    "責",
    "誤",
    "益",
    "毒",
    "骨",
    "健",
    "康",
    "快",
    "本",
    "積",
    "極",
    "哲",
    "公",
    "等",
    "節",
    "独",
    "迎",
    "輸",
    "片",
    "冊",
    "狭",
    "差",
    "刷",
    "利",
    "拡",
    "陸",
    "末",
    "燃",
    "馬",
    "鹿",
    "生",
    "枚",
    "負",
    "渉",
    "卓",
    "適",
    "創",
    "精",
    "認",
    "導",
    "固",
    "隣",
    "台",
    "戦",
    "和",
    "忠",
    "混",
    "鉄",
    "喫",
    "座",
    "鼻",
    "首",
    "震",
    "個",
    "災",
    "焦",
    "破",
    "壊",
    "造",
    "我",
    "去",
    "巨",
    "並",
    "坂",
    "匹",
    "緑",
    "植",
    "脈",
    "設",
    "築",
    "局",
    "温",
    "華",
    "氏",
    "算",
    "円",
    "邪",
    "軽",
    "絡",
    "毛",
    "布",
    "仮",
    "狂",
    "障",
    "害",
    "演",
    "安",
    "劇",
    "葉",
    "板",
    "階",
    "芝",
    "居",
    "移",
    "努",
    "折",
    "欠",
    "買",
    "皆",
    "虫",
    "歯",
    "圧",
    "転",
    "遺",
    "冗",
    "皮",
    "肉",
    "怪",
    "売",
    "系",
    "統",
    "鳥",
    "県",
    "尺",
    "収",
    "穫",
    "肥",
    "草",
    "泳",
    "犬",
    "亡",
    "豊",
    "寮",
    "飽",
    "油",
    "菜",
    "玉",
    "減",
    "皿",
    "湯",
    "子",
    "除",
    "控",
    "蔵",
    "庫",
    "器",
    "凍",
    "聖",
    "豚",
    "絶",
    "牧",
    "私",
    "万",
    "民",
    "誇",
    "仏",
    "殺",
    "含",
    "緊",
    "吸",
    "筋",
    "奨",
    "衛",
    "語",
    "迷",
    "充",
    "礎",
    "標",
    "推",
    "到",
    "否",
    "労",
    "範",
    "囲",
    "東",
    "征",
    "伏",
    "抵",
    "従",
    "射",
    "乱",
    "暴",
    "概",
    "焼",
    "編",
    "京",
    "雲",
    "偏",
    "甘",
    "衣",
    "騒",
    "悟",
    "避",
    "乾",
    "杯",
    "途",
    "育",
    "祈",
    "互",
    "賢",
    "鳴",
    "純",
    "辛",
    "管",
    "暗",
    "娘",
    "侮",
    "住",
    "辱",
    "弾",
    "王",
    "貝",
    "糸",
    "竹",
    "林",
    "羽",
    "園",
    "岩",
    "両",
    "汽",
    "弓",
    "魚",
    "戸",
    "黄",
    "谷",
    "細",
    "矢",
    "寺",
    "星",
    "親",
    "船",
    "池",
    "刀",
    "麦",
    "米",
    "里",
    "委",
    "央",
    "宮",
    "区",
    "南",
    "血",
    "湖",
    "港",
    "祭",
    "酒",
    "昭",
    "勝",
    "整",
    "速",
    "炭",
    "北",
    "柱",
    "丁",
    "帳",
    "笛",
    "投",
    "豆",
    "登",
    "童",
    "波",
    "箱",
    "古",
    "西",
    "畑",
    "筆",
    "氷",
    "羊",
    "陽",
    "胃",
    "栄",
    "塩",
    "億",
    "加",
    "漢",
    "貨",
    "芽",
    "械",
    "官",
    "季",
    "紀",
    "旗",
    "救",
    "挙",
    "鏡",
    "字",
    "軍",
    "郡",
    "径",
    "候",
    "航",
    "札",
    "察",
    "士",
    "史",
    "司",
    "好",
    "児",
    "辞",
    "周",
    "順",
    "松",
    "唱",
    "照",
    "臣",
    "浅",
    "倉",
    "終",
    "巣",
    "孫",
    "帯",
    "隊",
    "仲",
    "貯",
    "兆",
    "腸",
    "底",
    "典",
    "始",
    "灯",
    "梅",
    "博",
    "票",
    "夫",
    "付",
    "副",
    "粉",
    "兵",
    "包",
    "大",
    "浴",
    "類",
    "例",
    "歴",
    "録",
    "因",
    "永",
    "液",
    "往",
    "桜",
    "四",
    "恩",
    "河",
    "過",
    "賀",
    "格",
    "額",
    "刊",
    "幹",
    "眼",
    "久",
    "五",
    "旧",
    "境",
    "均",
    "群",
    "潔",
    "券",
    "検",
    "効",
    "鉱",
    "妻",
    "六",
    "秒",
    "採",
    "財",
    "罪",
    "雑",
    "酸",
    "志",
    "師",
    "枝",
    "資",
];

pub(crate) const KA_MEANINGS: [&'static str;1235] = [
    "one",
    "what, how many",
    "seven",
    "raise animals",
    "show",
    "state, mention, refer to, explain",
    "introductory part, order, preface",
    "weave",
    "tax",
    "tongue",
    "money",
    "ancestor",
    "measure, conjecture",
    "eight",
    "belong to",
    "loss, damage, harm",
    "retreat, drive away, repel",
    "copper",
    "virtue",
    "offense, commit (a crime), violate, defy",
    "printing plate, publishing, edition",
    "straw sack",
    "adult woman",
    "rich, wealth",
    "nine",
    "military",
    "compound, double, multiple",
    "grave, tomb",
    "inform, require, news, report, reward",
    "prevent, protect from",
    "trade, exchange",
    "duty, work, serve",
    "cotton",
    "remaining, excess",
    "abridged, strategy, omit, abbreviate",
    "ten",
    "territory, govern, rule",
    "bounded area, region",
    "universe",
    "along",
    "ash",
    "tower, tall magnificent building, cabinet",
    "divide, split",
    "stock, share, stump",
    "dry",
    "roll up, volume, wind",
    "wait",
    "watch, care for",
    "dangerous",
    "wield, direct, command",
    "noble, your honorable, valuable, respect",
    "hometown",
    "guard against, warn, admonish",
    "hole, cave",
    "silk",
    "constitution",
    "source, origin",
    "hall",
    "oneself, self",
    "empress",
    "filial piety",
    "crimson, deep red, rouge",
    "steel",
    "engrave, carve, chop up, point of time",
    "cereal, grain",
    "sand",
    "cut out, judge",
    "scheme, measure, plan, means, policy",
    "speak",
    "silkworm",
    "come to, arrive, lead to",
    "figure, form, shape, appearance, posture",
    "regard, consider, see, vision",
    "magnetism, magnetic",
    "standing tree, bush",
    "religious sect, religion",
    "set about, engage (in an occupation), employ",
    "multitude, populace",
    "vertical",
    "open",
    "shrink",
    "deal with, treat",
    "public-service station",
    "various",
    "wound, injury, hurt",
    "steam, evaporate",
    "needle",
    "benevolence, virtue, charity",
    "hang down, drip",
    "a bit of, unit of length",
    "close",
    "prosperous, flourish, serve food",
    "sincerity, truth, reality, fidelity",
    "proclaim, announce",
    "spring, fountain",
    "dye",
    "good",
    "play music",
    "dress, fit out, wear, pretend",
    "stratum, layer, level",
    "manipulate, operate, chastity",
    "friend",
    "internal organ",
    "be born, birth",
    "warm",
    "space, midair",
    "government agency",
    "summit, receive humbly",
    "tide",
    "wage, charges, fare, fee",
    "attack, study, examine, discuss",
    "party, faction",
    "up",
    "attain, suffix for plural",
    "sugar",
    "pay, accept, put away, supply",
    "brain",
    "worship, humbly, pray, venerate",
    "lung",
    "haiku, actor",
    "squad, group",
    "secret",
    "belly, heart, mind",
    "rouse up, be enlivened",
    "hand",
    "imperial palace steps",
    "supplement, supply, make up for",
    "treasure",
    "rod, stick, pole",
    "curtain, shogunate",
    "close, secret, dense, fine",
    "alliance, oath",
    "pattern, imitate, copy, model",
    "mail",
    "very young, infantile",
    "paper",
    "the following, the next",
    "egg",
    "look over, see",
    "rear, reverse side, back",
    "be present at, face, confront",
    "cheerful, clear, bright",
    "depend on",
    "differ, violate, different, be mistaken",
    "sharp",
    "smoke",
    "write, book",
    "dirty",
    "push",
    "Europe",
    "confectionery, cake",
    "shoes",
    "set, hang",
    "sweat",
    "can",
    "affected by disease, be ill, suffer",
    "how many/much, some",
    "autumn",
    "reprimand, stuff, closely packed, cram",
    "shout, scream",
    "conditions, situation, circumstances",
    "hold between, interpose",
    "by chance, even number, (married)couple",
    "nook, corner",
    "dig",
    "incline, lean, tilt",
    "eaves, counter for houses",
    "wither, blight",
    "mountain",
    "employ, charter, hire",
    "renew, again, further, furthermore",
    "assent, agree to, consent",
    "wild, violent, rough, devastate",
    "suburb, outskirts",
    "sweet smell, fragrance, aroma",
    "hard, firm",
    "move inward, include, be congested",
    "year, age suffix",
    "bloom",
    "snow",
    "fat, grease",
    "damp, moisten, humid",
    "small boat, ship",
    "soft",
    "outset, cord, strap, beginning, thong",
    "summon, wear, call",
    "bed, floor",
    "ascend, rise, be promoted",
    "tatami, fold up",
    "touch",
    "rain",
    "stretch, lengthen, grow",
    "blow",
    "surname",
    "one of a pair, counter for ships",
    "trace, mark, remains, ruins, tracks",
    "register",
    "occupy, tell fortunes, hold",
    "set of two, pair, both",
    "look for, search, seek",
    "sweep",
    "present, hit",
    "dry up",
    "hate, hatred, hateful",
    "present a gift, give, bestow",
    "bag, sack",
    "replace",
    "rinse",
    "livestock, animal raising",
    "stationed, stop, reside",
    "surpass, exceed",
    "sink",
    "drink",
    "rare, unusual",
    "mud",
    "drop, drip, trickle",
    "palace, hall, lord, formal honorific title",
    "apply on a surface, paint",
    "escape, run away, set free, miss",
    "tower",
    "tube, pipe",
    "dull, slow-witted, blunt, dim",
    "soft",
    "down",
    "know",
    "suffer, be troubled, afflict",
    "thick, dark",
    "stay overnight, lodge",
    "thin, weak, light, fade, dilute",
    "explode",
    "skin",
    "hair (on the head)",
    "engage in sales, sell",
    "bottle",
    "float, rise to the surface",
    "before, front",
    "skin",
    "dance",
    "seal",
    "width, breadth, range",
    "boil, seethe",
    "catch, grasp, capture",
    "hug, embrace, hold in one's arm",
    "headgear, cap, hat",
    "polish, brush",
    "bury, fill up",
    "after, back",
    "dissolve, melt",
    "waist, loins, hips, small of back",
    "dance",
    "grain",
    "finish, complete, understand",
    "cool",
    "treat",
    "tear",
    "zero",
    "age",
    "confer",
    "bay",
    "arm",
    "separate, leave, keep apart",
    "symbol of repetition",
    "remove, escape from, undress, drop out",
    "compare",
    "work, business, industry",
    "slow, late",
    "think",
    "night",
    "reflect, project",
    "picture",
    "middle, in",
    "go out, put out",
    "electricity",
    "meet, society",
    "thing",
    "return",
    "simple, brief",
    "single",
    "straight, fix, repair",
    "learn, custom",
    "be in trouble",
    "right",
    "hold",
    "tone, investigate, prepare",
    "draw, pull",
    "hear, listen, ask",
    "field",
    "village",
    "back",
    "high",
    "low",
    "long, chief",
    "left",
    "short",
    "put on, arrive, stick",
    "pleasure, comfortable, music",
    "river",
    "quality, matter",
    "question",
    "to the ... of, by means of",
    "many",
    "young",
    "great, thick",
    "color",
    "stop",
    "distant, far",
    "busy",
    "borrow",
    "tea",
    "enter, put in",
    "new",
    "teach, religion",
    "taste",
    "white",
    "woman",
    "blue",
    "black",
    "direction, way, square",
    "carry, move, fortune",
    "move",
    "body, form",
    "pain",
    "origin",
    "gas, spirit",
    "change, abnormal",
    "man",
    "tired",
    "go to sleep",
    "heaven",
    "head",
    "drawing",
    "public building",
    "probe, search",
    "lose, slip",
    "etiquette, rite, courtesy, gratitude",
    "little",
    "human being, person",
    "self",
    "reason",
    "without, nothing",
    "reason, basic principle",
    "say, speech",
    "degree, time",
    "collect",
    "sound",
    "decide",
    "affair, abstract thing",
    "two",
    "see",
    "cut",
    "symbol",
    "bad, evil",
    "real, fruit, nut",
    "illness, disease, sickness",
    "govern, cure, heal",
    "school",
    "heart",
    "start, emit",
    "numerical order, watch",
    "ahead",
    "distinguished, England",
    "letter, writings, sentence",
    "law, method",
    "train, knead",
    "lend",
    "forest",
    "try, attempt",
    "test",
    "title, topic, problem",
    "whole",
    "vehicle, wheel, car",
    "section",
    "eye, item",
    "number, designation, sign",
    "sand, sharpen",
    "study exhaustively",
    "room",
    "link, in succession, group, accompaniment",
    "flower",
    "serve, do",
    "pass through, manage, sutra",
    "country",
    "settle, relieve, finish",
    "target, adjectival suffix",
    "difficult, disaster",
    "wide",
    "same",
    "summer",
    "spring",
    "without failure, surely",
    "important, summarize, require",
    "intercourse, interchange",
    "time",
    "pass, communicate, commute",
    "winter",
    "run",
    "heavy",
    "graduate",
    "company, society",
    "service",
    "house, small shop",
    "noon",
    "desk",
    "interval, between",
    "use, envoy",
    "cold",
    "summer heat, hot",
    "cold",
    "who, someone",
    "urgent, hurry, sudden",
    "employ, things to do",
    "time, period",
    "inside",
    "transmit",
    "half",
    "desire, want",
    "first",
    "next",
    "most",
    "rice field",
    "stone",
    "plain, original",
    "station",
    "vicinity, borderland",
    "way, street, road",
    "divide, part, minute",
    "modifier forming suffix, as",
    "manufacture, construction",
    "place",
    "sideways, side",
    "believe, trust, message",
    "curve, musical composition",
    "bridge",
    "turn toward, face toward",
    "ground, place, base, earth, land",
    "silver",
    "moon, month",
    "angle, horn, corner",
    "red",
    "celebrate",
    "mutual, phase, minister",
    "talk, conversation",
    "contact, touch",
    "fee, materials",
    "sweep away, pay",
    "term, time, expect",
    "work",
    "fire",
    "offer, accompany",
    "third person pronoun, that",
    "cry",
    "descend, fall, get off",
    "fine weather, clear up",
    "cloudy",
    "sky, air, empty",
    "evening",
    "standard, semi-",
    "provide, furnish",
    "three",
    "water",
    "walk",
    "song",
    "foot, suffice, add",
    "mouth",
    "world, era",
    "world, boundary",
    "medicine, doctor",
    "person",
    "distribute",
    "regulation, measure",
    "tree, wood",
    "rule, law",
    "right, correct",
    "active, live",
    "think",
    "plan, compute, measure",
    "inner part",
    "mode, way, formal title, manner",
    "sleep",
    "outside",
    "not",
    "metal, gold, money",
    "former times, antiquity",
    "ocean, western",
    "contribute, draw near, approach",
    "wind, manner",
    "call, invite",
    "get angry",
    "lodge",
    "cross",
    "travel",
    "take",
    "soil, earth, ground",
    "steal",
    "build",
    "house, residence",
    "report, speak humbly",
    "wish, ask a favor, request",
    "main, master",
    "concern, barrier",
    "special",
    "separate, another",
    "I, manservant",
    "day, sun, Japan",
    "in advance",
    "fix, determine",
    "copy",
    "true, genuine",
    "widespread, general",
    "mind, meaning, will",
    "forget",
    "perceive, remember, awake",
    "seat",
    "ruler, familiar title, you",
    "hundred",
    "heat, hot, fever",
    "die, death",
    "tie, conclude",
    "marry",
    "style, ceremony",
    "cattle, cow, ox",
    "milk",
    "marsh",
    "town",
    "other",
    "thousand",
    "cooked rice, meal",
    "answer",
    "shop, store",
    "love",
    "combine, fit, match",
    "sad",
    "employment",
    "member",
    "happiness, happy",
    "fly",
    "present, this",
    "ear",
    "dislike, unpleasant",
    "window",
    "happy, happiness, be glad",
    "counter, anti-",
    "oppose, opposite, against",
    "love",
    "notify, tell, inform",
    "permit, allow",
    "matter",
    "small",
    "return",
    "clothes, clothing, submit",
    "day of the week",
    "article, goods",
    "not yet",
    "complete",
    "sea, ocean",
    "island",
    "grade",
    "face",
    "rest",
    "face, mask, surface",
    "project, plan, attempt",
    "city, market",
    "rely on, request",
    "ordinal number prefix, degree",
    "express, surface, table",
    "general, officer",
    "hope, aspire",
    "place",
    "look into, investigate",
    "study, educational, institution",
    "go, act, line",
    "connect, person in charge",
    "translate, sense, reason",
    "section, lesson",
    "continue",
    "verge, occasion, edge",
    "hope, desire, look after",
    "form, achieve",
    "merit, success",
    "promise, contract, approximately",
    "tie up, bundle",
    "house, family",
    "receive",
    "have",
    "point",
    "discriminate, knowledge, know",
    "sense, feel",
    "send",
    "number, count",
    "ball",
    "play",
    "invite",
    "return",
    "choose, elect",
    "lecture",
    "righteousness, meaning, justice",
    "service, role",
    "stand, establish",
    "argue, theory, thesis",
    "base, foundation",
    "thick, kind",
    "urge, recommend, offer",
    "sort, carry, all, general",
    "near, recent",
    "foster, rear",
    "change into",
    "subject of study",
    "achievements",
    "type",
    "suffering, bitter, painful",
    "full",
    "increase",
    "voice",
    "actual, appear, present",
    "father",
    "be, exist",
    "dream",
    "ride, get on",
    "let go, release",
    "cooperate",
    "power, force",
    "praise, agreement",
    "explain, theory, opinion",
    "fall",
    "name",
    "mother",
    "machine, opportunity",
    "implement, tool",
    "detailed",
    "take apart, dissolve, clarify, untie",
    "construct, mind",
    "emotion, actual conditions",
    "joint, together, both",
    "exist, know",
    "quiet",
    "flow, current, style",
    "older brother",
    "art, craft",
    "practical art, technique",
    "light",
    "scene",
    "surprise",
    "help, rescue, assistance",
    "seek, demand",
    "keep, stay",
    "prosper, amusement, interest, revive",
    "deep",
    "younger brother",
    "cat",
    "conceive, idea, thought",
    "image",
    "flat, calm",
    "rank, position",
    "place, put",
    "advance, progress",
    "go beyond, exceed",
    "court, garden",
    "power, force, vigor",
    "older sister",
    "nature, sex, -ity, gender",
    "body, group",
    "speak eloquently, speech, valve, petal",
    "protect",
    "article, line",
    "shadow, silhouette",
    "reverberate, echo, resound, affect",
    "visit",
    "participate, visit a holy place",
    "general honorific term, polite prefix",
    "younger sister",
    "fruit",
    "habitual practice, get used",
    "exclusive",
    "attack",
    "flavor, taste, elegance",
    "prize",
    "magazine",
    "return to, be restored",
    "limit",
    "certain, verify",
    "institution",
    "come",
    "preserve",
    "prove, certificate",
    "chase, pursue",
    "mail, post, convenient, excrement",
    "write, publish, author, remarkable, conspicuous",
    "substitute, generation, charge",
    "pull out, stand out, surpass",
    "shoulder",
    "inquire",
    "timber, material",
    "rise, get up",
    "remain, ruthless",
    "thought, desire, attention",
    "shame, disgrace, shy",
    "capital (city), metropolis",
    "wash",
    "state",
    "fortune",
    "side",
    "fear",
    "be defeated",
    "every",
    "compare",
    "times, double",
    "poetry, poem",
    "element, plain",
    "chest, breast",
    "strike, hit",
    "severe, strict, solemn",
    "superior, actor, gentle, excel",
    "",
    "shape",
    "morning, dynasty",
    "words",
    "extent, established form, degree",
    "order, life",
    "command",
    "appearance, contain",
    "discuss, legislative body, deliberation",
    "mark, seal, stamp",
    "phenomenon, elephant",
    "phrase, haiku, verse",
    "line",
    "evening",
    "fellow",
    "topple, collapse, fall over",
    "respond, reply",
    "raise, invite",
    "system, control",
    "quantity, measure, weigh",
    "each",
    "comment, criticism",
    "stamp, seal, judge",
    "exchange, substitute",
    "family, tribe",
    "compete",
    "contend, dispute, argue",
    "rate, lead, command",
    "acquire, gain, profit",
    "spread, strain, stretch",
    "price, value",
    "suppress, control",
    "weak",
    "skill, technique",
    "law, rhythm, regulation",
    "endeavor",
    "honor, respect, valuable, noble",
    "respect",
    "view",
    "variety, seed, type, kind",
    "ability, function, Noh play",
    "extend, postpone",
    "drug, medicine",
    "laugh",
    "is not, mistake, non-, un-",
    "normal, regular, ever-, always",
    "strong",
    "visitor, customer, guest",
    "deliver, reach, report, notify",
    "building, quarters",
    "dusk, live, come to an end",
    "fearful, scary",
    "breath",
    "pick up, ten (in documents)",
    "step, stairs, rank",
    "free time, leisure",
    "deposit, entrust",
    "yesterday, last",
    "cut off, decision, refuse",
    "agree to, hear, be told",
    "round, suffix for names of ships/people",
    "thank, apologize, gratitude",
    "enemy",
    "Buddhist priest, boy, colloquial person suffix",
    "shore, bank, coast",
    "good",
    "scatter",
    "instruct, teaching, precept",
    "eat, food",
    "branch, support",
    "organize, assemble, group, class, gang",
    "protect, obey, babysitter",
    "extinguish, delete, disappear, erase",
    "trade, deal",
    "resemble, be similar",
    "risk, brave, desecrate",
    "danger, steep",
    "discard, throw away, abandon",
    "form, condition, letter, circumstances",
    "year",
    "make, work",
    "state, condition",
    "brave, be spirited, encouraged",
    "bold, boldly, daring",
    "sect, group, dispatch",
    "another time, again, twice",
    "give, grant",
    "proposal, plan",
    "beautiful, beauty",
    "picture",
    "farming, agriculture",
    "read",
    "depict, draw, paint",
    "follower, vain, useless, on foot",
    "castle",
    "violent, intense, fierce",
    "different",
    "total, general, overall",
    "pour, concentrate, note",
    "reform",
    "leather, reform",
    "office, duty, responsibility, leave to, entrust",
    "week",
    "resist",
    "body, oneself",
    "gate",
    "prohibit",
    "root",
    "present, submit",
    "rice plant",
    "till, cultivate, plough",
    "manage, barracks, conduct business",
    "unfold, display, expand",
    "turn round, time",
    "doubt",
    "fish, fishing",
    "dash, thrust, poke, strike",
    "criticize, critique",
    "end, edge, side",
    "row",
    "immediate, namely, conform",
    "finger, point",
    "value, price",
    "mature, ripen",
    "bright, clear",
    "easy, exchange",
    "emperor",
    "right, power, authority",
    "god, mind",
    "exempt, escape, avoid",
    "reverse, be contrary",
    "manufacture, produce, make",
    "great, eminent, remarkable",
    "old, the late, deceased, reason",
    "cultivate, repair, study, master",
    "early, quick",
    "city quarter, street",
    "halt, stop",
    "road, way, street",
    "chapter, badge",
    "political administration, government, rule",
    "urban prefecture, government office, capital city",
    "firm, hard, solid",
    "bear on shoulder, undertake",
    "give birth, produce",
    "ministry, save, reflect on, omit",
    "daytime",
    "wheel, ring, circle",
    "old, grow old",
    "load, cargo, baggage",
    "poor",
    "scanty, meager, scarce",
    "write down",
    "clear, purify, pure",
    "supply, pay",
    "expense, spend, waste",
    "stab, pierce",
    "talent, counter for age",
    "introduce",
    "mediate, be in between",
    "responsibility, blame, condemn",
    "mistake, err",
    "benefit, profit, advantage",
    "poison",
    "bone",
    "robust, healthy",
    "healthy, composure",
    "pleasant",
    "basis, book, this",
    "accumulate",
    "extreme, pole",
    "sagacious, philosophy",
    "public, official",
    "equal, class",
    "joint, season of the year, section, melody",
    "alone, Germany",
    "welcome, go to meet, pick up",
    "transport",
    "fragment, one (of two), part",
    "counter for books",
    "narrow",
    "difference",
    "print",
    "advantage, profit, be effective",
    "enlarge, extend, expand",
    "land",
    "last part, end",
    "burn",
    "horse",
    "deer",
    "life, be born, student",
    "counter for flat things",
    "bear, lose, defeat, owe",
    "have relation with, cross over",
    "table, prominent",
    "suitable, fit, suit, appropriate",
    "create",
    "refine, essence, spirit, energy",
    "recognize",
    "guide, lead",
    "solid, firm, hard",
    "neighbor",
    "stand, counter for machinery",
    "war, fight, battle",
    "harmony, peace, Japan",
    "loyalty, faithfulness",
    "mix",
    "iron",
    "ingest, drink, smoke",
    "seat, sit",
    "nose",
    "head, neck, leader",
    "quake, shake, tremble",
    "individual, general counter",
    "calamity, disaster, misfortune",
    "scorch, be impatient, yearn for",
    "break, tear",
    "break down, destroy, damage",
    "make, produce, build",
    "self, I, my, our",
    "go away, leave",
    "huge, gigantic, large",
    "line up, ordinary",
    "slope, hill",
    "counter for animals",
    "green",
    "plant",
    "vein, pulse",
    "set up, establish",
    "construct, build",
    "bureau, limited part, office",
    "warm",
    "magnificent, flower, brilliant, China",
    "courtesy title, family name, lineage",
    "calculate",
    "circle, yen",
    "evil, wrong",
    "light",
    "interlink, entwine, get entangled",
    "hair, fur, feather, down",
    "cloth, spread",
    "temporary, tentative",
    "crazy, go mad",
    "hindrance, interfere with",
    "harm, damage",
    "perform",
    "peaceful, inexpensive",
    "drama, play",
    "leaf、foliage",
    "board, plate",
    "floor, rank, stair, level",
    "lawn",
    "reside, exist",
    "shift, move, transfer",
    "exert, make efforts, strive",
    "break off, fold, bend",
    "lack",
    "buy",
    "all",
    "insect, bug",
    "tooth",
    "pressure",
    "turn, roll over, fall down",
    "leave behind",
    "redundant, superfluous",
    "skin, hide, rind, leather, bark",
    "flesh, meat",
    "mysterious, strange, doubt",
    "sell",
    "system, lineage",
    "unite, interconnected system, govern, control",
    "bird, fowl, poultry",
    "prefecture",
    "shaku (unit of length, about 30 cm), measure",
    "take in, obtain, collect",
    "harvest",
    "fatten, fertilize",
    "grass",
    "swim",
    "dog",
    "decease, dead",
    "plentiful, abundant, rich",
    "dormitory",
    "satiated, get tired of",
    "oil",
    "vegetable, greens",
    "gem, jewel, ball",
    "decrease",
    "plate, dish, saucer",
    "hot water",
    "child, noun suffix",
    "rid of, exclude",
    "hold back, refrain from, wait",
    "store, warehouse",
    "storage chamber, storehouse",
    "vessel, instrument, container, capacity",
    "freeze",
    "holy, saint",
    "pig",
    "break off, come to an end",
    "pasture",
    "I, private",
    "ten thousand",
    "people",
    "boast, be proud of",
    "Buddha, France",
    "kill",
    "contain, include",
    "tight, exigent, tense, hard",
    "suck, breathe in, inhale, smoke",
    "muscle, threadlike structure, line, plot",
    "encourage, urge",
    "guard, defend, protect",
    "language, word, tell",
    "perplexed, get lost",
    "fill, allocate, assign",
    "foundation stone, cornerstone",
    "mark, sign",
    "infer, deduce, recommend",
    "arrive, reach",
    "say no, not",
    "labor, toil",
    "model, example",
    "enclose, surround",
    "east",
    "conquer",
    "prostrate, bend down, lie down, hide",
    "resist",
    "follow, obey, conquer",
    "shoot",
    "disordered, riot, confusion",
    "violent, rage, expose",
    "general, approximate",
    "burn, roast, broil, bake",
    "compile, knit, edit",
    "capital",
    "cloud",
    "one-sided, lean, incline, partial",
    "sweet",
    "garment, clothes",
    "clamor, make noise",
    "awake to, perceive, be enlightened",
    "avoid",
    "dry",
    "cup, sake cup",
    "way, road",
    "raise",
    "pray",
    "reciprocal, mutual, each other",
    "wise, intelligent",
    "cry, sound, ring, sing, howl",
    "pure",
    "pungent, hard, spicy",
    "pipe, exercise control, wind instrument, tube",
    "dark, dim",
    "daughter, girl",
    "insult, despise, scorn",
    "live",
    "humiliate, disgrace",
    "bullet, spring back, bounce, play",
    "king",
    "shellfish, shell",
    "thread",
    "bamboo",
    "woods, forest",
    "feather, wing",
    "garden",
    "rock",
    "both",
    "steam",
    "bow",
    "fish",
    "door, household",
    "yellow",
    "valley",
    "slender, minute, narrow, fine, detailed",
    "arrow",
    "Buddhist temple",
    "star",
    "parent, relatives, intimate",
    "ship, boat, vessel",
    "pond",
    "sword",
    "wheat",
    "rice, America",
    "countryside, league, hometown, village, town",
    "commit, entrust",
    "center, middle",
    "royal palace, Shinto shrine",
    "district, ward",
    "south",
    "blood",
    "lake",
    "port, harbor",
    "festival",
    "alcoholic drink, sake, alcohol, liquor",
    "luminous, bright, clear",
    "win, excel, be superior",
    "put in order, organize, prepared",
    "quick, fast, prompt",
    "coal, charcoal",
    "north",
    "pillar, pole",
    "town subsection, miscellaneous counter, even number",
    "notebook",
    "flute, whistle",
    "throw, send in",
    "bean, pea, miniature",
    "climb",
    "child",
    "wave",
    "box",
    "old",
    "west",
    "field, cultivated field",
    "brush, writing",
    "ice",
    "sheep",
    "sun, positive",
    "stomach",
    "flourish, glory, honor, prosper",
    "salt",
    "hundred million",
    "add, append, join",
    "Chinese, fellow",
    "money, goods, property, freight",
    "bud, sprout",
    "mechanical contrivance, machine",
    "government, government official, authorities",
    "season",
    "era",
    "flag, banner",
    "save, rescue, aid",
    "nominate, noteworthy act, raise",
    "mirror, optical instrument",
    "character",
    "army",
    "county",
    "path, diameter",
    "season, seasonal weather",
    "navigate, sail",
    "tag, bill, paper money, label",
    "inspect, guess, surmise, judge",
    "military man, profession suffix",
    "history",
    "officiate, administer",
    "like, favorable",
    "child",
    "word, resign, quit",
    "lap, periphery, circumference",
    "order, obey, sequence",
    "pine",
    "sing",
    "illuminate, shine",
    "retainer",
    "shallow",
    "storehouse, warehouse, depository",
    "end",
    "nest",
    "grandchild",
    "belt, wear, zone",
    "party, squad, unit",
    "intermediary, personal relations, relation",
    "lay-up, storage, store",
    "omen, trillion",
    "intestines",
    "bottom",
    "standard work, canon, law code, ceremony",
    "begin",
    "lamp, light",
    "Japanese apricot, plum",
    "extensive, doctor, broad",
    "vote, slip, ballot",
    "husband, man laborer",
    "attach, belong, apply",
    "secondary, assistant, accompany, supplement",
    "powder",
    "soldier",
    "wrap, encompass",
    "big",
    "bathe, pour over, shower",
    "kind, type, genus",
    "example",
    "personal history, passing of time",
    "record",
    "cause, depend, be limited",
    "eternal, long, forever",
    "liquid, fluid",
    "go on, proceed",
    "cherry",
    "four",
    "grace, favor, debt of gratitude",
    "river",
    "pass by, exceed, spend (time), err",
    "congratulate",
    "norm, status, rank, standard",
    "amount, forehead",
    "publish",
    "tree trunk, main part",
    "eye",
    "of long duration, long time",
    "five",
    "former, old",
    "boundary, situation, border",
    "even, equal",
    "group, herd, crowd, flock",
    "immaculate, pure, righteous",
    "ticket, certificate",
    "examine, investigate, inspect",
    "effect, be effective",
    "ore, mine",
    "wife",
    "six",
    "second (of time)",
    "pick, gather, take, accept, employ",
    "wealth, property, money",
    "crime, sin, guilt",
    "miscellaneous, mixed",
    "acid, oxygen",
    "ambition, will, intention, aim",
    "master, teacher",
    "branch",
    "resources, capital, funds",
];

pub(crate) const KA_ONYOMIS: [&'static [&'static str];1235] = [
    &["イチ"],
    &["カ"],
    &["シチ"],
    &["シ"],
    &["シ","ジ"],
    &["ジュツ"],
    &["ジョ"],
    &["ショク","シキ"],
    &["ゼイ"],
    &["ゼツ"],
    &["セン"],
    &["ソ"],
    &["ソク"],
    &["ハチ"],
    &["ゾク"],
    &["ソン"],
    &["タイ"],
    &["ドウ"],
    &["トク"],
    &["ハン"],
    &["ハン"],
    &["ヒョウ"],
    &["フ"],
    &["フ","フウ"],
    &["キュウ","ク"],
    &["ブ","ム"],
    &["フク"],
    &["ボ"],
    &["ホウ"],
    &["ボウ"],
    &["ボウ"],
    &["ム"],
    &["メン"],
    &["ヨ"],
    &["リャク"],
    &["ジュウ"],
    &["リョウ"],
    &["イキ"],
    &["ウ"],
    &["エン"],
    &["カイ"],
    &["カク"],
    &["カツ"],
    &[""],
    &["カン"],
    &["カン"],
    &["タイ"],
    &["カン"],
    &["キ"],
    &["キ"],
    &["キ"],
    &["キョウ","ゴウ"],
    &["ケイ"],
    &["ケツ"],
    &["ケン"],
    &["ケン"],
    &["ゲン"],
    &["ドウ"],
    &["コ","キ"],
    &["コウ"],
    &["コウ"],
    &["コウ","ク"],
    &["コウ"],
    &["コク"],
    &["コク"],
    &["サ","シャ"],
    &["サイ"],
    &["サク"],
    &["ワ"],
    &["サン"],
    &["シ"],
    &["シ"],
    &["シ"],
    &["ジ"],
    &["ジュ"],
    &["シュウ","ソウ"],
    &["シュウ","ジュ"],
    &["シュウ","シュ"],
    &["ジュウ"],
    &["カイ"],
    &["シュク"],
    &["ショ"],
    &["ショ"],
    &["ショ"],
    &["ショウ"],
    &["ジョウ"],
    &["シン"],
    &["ジン","ニン"],
    &["スイ"],
    &["スン"],
    &["ヘイ"],
    &["セイ","ジョウ"],
    &["セイ"],
    &["セン"],
    &["セン"],
    &["セン"],
    &["ゼン"],
    &["ソウ"],
    &["ソウ","ショウ"],
    &["ソウ"],
    &["ソウ"],
    &["ユウ"],
    &["ゾウ"],
    &["タン"],
    &["ダン"],
    &["チュウ"],
    &["チョウ"],
    &["チョウ"],
    &["チョウ"],
    &["チン"],
    &["トウ"],
    &["トウ"],
    &["ジョウ","ショウ"],
    &["タツ"],
    &["トウ"],
    &["ノウ","ナツ","ナ","ナン","トウ"],
    &["ノウ"],
    &["ハイ"],
    &["ハイ"],
    &["ハイ"],
    &["ハン"],
    &["ヒ"],
    &["フク"],
    &["フン"],
    &["シュ","ズ"],
    &["ヘイ"],
    &["ホ"],
    &["ホウ"],
    &["ボウ"],
    &["マク","バク"],
    &["ミツ"],
    &["メイ"],
    &["モ","ボ"],
    &["ユウ"],
    &["ヨウ"],
    &["シ"],
    &["ヨク"],
    &["ラン"],
    &["ラン"],
    &["リ"],
    &["リン"],
    &["ロウ"],
    &["イ","エ"],
    &["イ"],
    &["エイ"],
    &["エン"],
    &["ショ"],
    &["オ"],
    &["オウ"],
    &["オウ"],
    &["カ"],
    &["カ"],
    &[""],
    &["カン"],
    &["カン"],
    &["カン"],
    &["キ"],
    &["シュウ"],
    &["キツ"],
    &["キョウ"],
    &["キョウ"],
    &["キョウ"],
    &["グウ"],
    &["グウ"],
    &["クツ"],
    &["ケイ"],
    &["ケン"],
    &["コ"],
    &["サン"],
    &["コ"],
    &["コウ"],
    &["コウ"],
    &["コウ"],
    &["コウ"],
    &["コウ","キョウ"],
    &["コウ"],
    &[""],
    &["サイ","セイ"],
    &[""],
    &["セツ"],
    &["シ"],
    &["シツ"],
    &["シュウ"],
    &["ジュウ","ニュウ"],
    &["ショ","チョ"],
    &["ショウ"],
    &["ショウ"],
    &["ショウ"],
    &["ジョウ"],
    &["ショク"],
    &["ウ"],
    &["シン"],
    &["スイ"],
    &["セイ","ショウ"],
    &["セキ"],
    &["セキ"],
    &["セキ"],
    &["セン"],
    &["ソウ"],
    &["ソウ"],
    &["ソウ"],
    &["トウ"],
    &["ソウ"],
    &["ゾウ"],
    &["ゾウ","ソウ"],
    &["タイ"],
    &["タイ"],
    &["タク"],
    &["チク"],
    &["チュウ"],
    &["チョウ"],
    &["チン"],
    &["イン"],
    &["チン"],
    &["デイ"],
    &["テキ"],
    &["デン","テン"],
    &["ト"],
    &["トウ"],
    &["トウ"],
    &["トウ"],
    &["ドン"],
    &["ナン"],
    &["カ","ゲ"],
    &["チ"],
    &["ノウ"],
    &["ノウ"],
    &["ハク"],
    &["ハス"],
    &["バク"],
    &[""],
    &["ハツ"],
    &["ハン"],
    &["ビン"],
    &["フ"],
    &["ゼン"],
    &["フ"],
    &["ブ"],
    &["フウ","ホウ"],
    &["フク"],
    &["フツ"],
    &["ホ"],
    &["ホウ"],
    &["ボウ"],
    &["マ"],
    &["マイ"],
    &["ゴ","コウ"],
    &["ヨウ"],
    &["ヨウ"],
    &["ヨウ"],
    &["リュウ"],
    &["リョウ"],
    &["リョウ"],
    &["リョウ"],
    &["ルイ"],
    &["レイ"],
    &["レイ"],
    &["ジュ"],
    &["ワン"],
    &["ワン"],
    &["リ"],
    &[""],
    &["ダツ"],
    &["カク"],
    &["ギョウ","ゴウ"],
    &["チ"],
    &["シ"],
    &["ヤ"],
    &["エイ"],
    &["ガ","カク"],
    &["チュウ"],
    &["シュツ","スイ"],
    &["デン"],
    &["カイ","エ"],
    &["ブツ","モツ"],
    &["ヘン"],
    &["カン"],
    &["タン"],
    &["チョク","ジキ","ジカ"],
    &["シュウ"],
    &["コン"],
    &["ウ","ユウ"],
    &["ジ"],
    &["チョウ"],
    &["イン"],
    &["ブン","モン"],
    &["ヤ"],
    &["ソン"],
    &["ハイ"],
    &["コウ"],
    &["テイ"],
    &["チョウ"],
    &["サ"],
    &["タン"],
    &["チャク","ジャク"],
    &["ガク","ラク"],
    &["セン"],
    &["シツ","シチ","チ"],
    &["モン"],
    &["イ"],
    &["タ"],
    &["ジャク","ニャク"],
    &["タイ","タ"],
    &["ショク","シキ"],
    &["シ"],
    &["エン","オン"],
    &["ボウ"],
    &["シャク"],
    &["チャ","サ"],
    &["ニュウ"],
    &["シン"],
    &["キョウ"],
    &["ミ"],
    &["ハク","ビャク"],
    &["ジョ","ニョ","ニョウ"],
    &["セイ","ショウ"],
    &["コク"],
    &["ホウ"],
    &["ウン"],
    &["ドウ"],
    &["タイ","テイ"],
    &["ツウ"],
    &["ゲン","ガン"],
    &["キ","ケ"],
    &["ヘン"],
    &["ダン","ナン"],
    &["ヒ"],
    &["シン"],
    &["テン"],
    &["トウ","ズ","ト"],
    &["ズ","ト"],
    &["カン"],
    &["タン"],
    &["シツ"],
    &["レイ","ライ"],
    &["ショウ"],
    &["ジン","ニン"],
    &["ジ","シ"],
    &["ユ","ユウ","ユイ"],
    &["ム","ブ"],
    &["リ"],
    &["ゲン","ゴン"],
    &["ド","ト","タク"],
    &["シュウ"],
    &["オン","ノン","イン"],
    &["ケツ"],
    &["ジ","ズ"],
    &["ニ"],
    &["ケン"],
    &["セツ","サイ"],
    &["フ"],
    &["アク","オ"],
    &["ジツ"],
    &["ビョウ","ヘイ"],
    &["ジ","チ"],
    &["コウ"],
    &["シン"],
    &["ハツ","ホツ"],
    &["バン"],
    &["セン"],
    &["エイ"],
    &["ブン","モン"],
    &["ホウ","ハツ","ホツ"],
    &["レン"],
    &["タイ"],
    &["シン"],
    &["シ"],
    &["ケン"],
    &["ダイ"],
    &["ゼン"],
    &["シャ"],
    &["ブ"],
    &["モク"],
    &["ゴウ"],
    &["ケン"],
    &["キュウ"],
    &["シツ"],
    &["レン"],
    &["カ"],
    &["シ","ジ"],
    &["ケイ","キョウ"],
    &["コク"],
    &["サイ"],
    &["テキ"],
    &["ナン"],
    &["コウ"],
    &["ドウ"],
    &["カ","ゲ"],
    &["シュン"],
    &["ヒツ"],
    &["ヨウ"],
    &["コウ"],
    &["ジ"],
    &["ツウ","ツ"],
    &["トウ"],
    &["ソウ"],
    &["ジュウ","チョウ"],
    &["ソツ"],
    &["シャ"],
    &["キン","ゴン"],
    &["オク"],
    &["ゴ"],
    &["キ"],
    &["カン","ケン"],
    &["シ"],
    &["カン"],
    &["ショ"],
    &["レイ"],
    &["スイ"],
    &["キュウ"],
    &["ヨウ"],
    &["ケイ"],
    &["ナイ"],
    &["デン"],
    &["ハン"],
    &["ヨク"],
    &["ショ"],
    &["ジ","シ"],
    &["サイ"],
    &["デン"],
    &["セキ","シャク","コク"],
    &["ゲン"],
    &["エキ"],
    &["ヘン"],
    &["ドウ","トウ"],
    &["ブン","フン","ブ"],
    &["ゼン","ネン"],
    &["コウ","ク"],
    &["ショ"],
    &["オウ"],
    &["シン"],
    &["キョク"],
    &["キョウ"],
    &["コウ"],
    &["チ","ジ"],
    &["ギン"],
    &["ゲツ","ガツ"],
    &["カク"],
    &["セキ","シャク"],
    &["シュク","シュウ"],
    &["ソウ","ショウ"],
    &["ダン"],
    &["セツ"],
    &["リョウ"],
    &["フツ"],
    &["キ","ゴ"],
    &["ドウ"],
    &["カ"],
    &["キョウ","ク"],
    &["ヒ"],
    &["キュウ"],
    &["コウ"],
    &["セイ"],
    &["ドン"],
    &["クウ"],
    &["セキ"],
    &["ジュン"],
    &["ビ"],
    &["サン"],
    &["スイ"],
    &["ホ","ブ","フ"],
    &["カ"],
    &["ソク"],
    &["コウ","ク"],
    &["セイ","セ"],
    &["カイ"],
    &["イ"],
    &["シャ"],
    &["ハイ"],
    &["キ"],
    &["ボク","モク"],
    &["ソク"],
    &["セイ","ショウ"],
    &["カツ"],
    &["コウ"],
    &["ケイ"],
    &["オウ"],
    &["ヨウ"],
    &["ミン"],
    &["ガイ","ゲ"],
    &["フ","ブ"],
    &["キン","コン"],
    &["セキ","シャク"],
    &["ヨウ"],
    &["キ"],
    &["フウ","フ"],
    &["コ"],
    &["ド"],
    &["シュク"],
    &["ト"],
    &["リョ"],
    &["シュ"],
    &["ド","ト"],
    &["トウ"],
    &["ケン","コン"],
    &["タク"],
    &["シン"],
    &["ガン"],
    &["シュ","ス"],
    &["カン"],
    &["トク"],
    &["ベツ"],
    &["ボク"],
    &["ニチ","ジツ"],
    &["ヨ"],
    &["テイ","ジョウ"],
    &["シャ"],
    &["シン"],
    &["フ"],
    &["イ"],
    &["ボウ"],
    &["カク"],
    &["セキ"],
    &["クン"],
    &["ヒャク"],
    &["ネツ"],
    &["シ"],
    &["ケツ"],
    &["コン"],
    &["シキ"],
    &["ギュウ"],
    &["ニュウ"],
    &["タク"],
    &["チョウ"],
    &["タ"],
    &["セン"],
    &["ハン"],
    &["トウ"],
    &["テン"],
    &["アイ"],
    &["ゴウ","カ","ガ"],
    &["ヒ"],
    &["ショク"],
    &["イン"],
    &["コウ"],
    &["ヒ"],
    &["コン","キン"],
    &["ジ"],
    &["ケン"],
    &["ソウ"],
    &["キ"],
    &["ハン","ホン","タン"],
    &["タイ","ツイ"],
    &["レン"],
    &["コク"],
    &["キョ"],
    &["ケン"],
    &["ショウ"],
    &["レイ"],
    &["フク"],
    &["ヨウ"],
    &["ヒン"],
    &["ミ"],
    &["カン"],
    &["カイ"],
    &["トウ"],
    &["キュウ"],
    &["ガン"],
    &["キュウ"],
    &["メン"],
    &["キ"],
    &["シ"],
    &["ライ"],
    &["ダイ"],
    &["ヒョウ"],
    &["ショウ"],
    &["キ"],
    &["ジョウ"],
    &["サ"],
    &["ガク"],
    &["コウ","ギョウ","アン"],
    &["ケイ"],
    &["ヤク"],
    &["カ"],
    &["ゾク"],
    &["サイ"],
    &["ボウ","モウ"],
    &["セイ","ジョウ"],
    &["コウ","ク"],
    &["ヤク"],
    &["ソク"],
    &["カ","ケ"],
    &["ジュ"],
    &["ユウ","ウ"],
    &["テン"],
    &["シキ"],
    &["カン"],
    &["ソウ"],
    &["スウ","ス"],
    &["キュウ"],
    &["ユウ","ユ"],
    &["ショウ"],
    &["キ"],
    &["セン"],
    &["コウ"],
    &["ギ"],
    &["ヤク","エキ"],
    &["リツ","リュウ"],
    &["ロン"],
    &["キ"],
    &["コウ"],
    &["カン"],
    &["ハン"],
    &["キン"],
    &["ヨウ"],
    &["カ","ケ"],
    &["カ"],
    &["セキ"],
    &["ケイ"],
    &["ク"],
    &["マン"],
    &["ゾウ"],
    &["セイ","ショウ"],
    &["ゲン"],
    &["フ"],
    &["ザイ"],
    &["ム"],
    &["ジョウ"],
    &["ホウ"],
    &["キョウ"],
    &["リョク","リキ"],
    &["サン"],
    &["セツ","ゼイ"],
    &["ラク"],
    &["メイ","ミョウ"],
    &["ボ"],
    &["キ"],
    &["グ"],
    &["ショウ"],
    &["カイ","ゲ"],
    &["コウ"],
    &["ジョウ","セイ"],
    &["キョウ"],
    &["ソン","ゾン"],
    &["セイ","ジョウ"],
    &["リュウ","ル"],
    &["ケイ","キョウ"],
    &["ゲイ"],
    &["ジュツ"],
    &["コウ"],
    &["ケイ"],
    &["キョウ"],
    &["ジョ"],
    &["キュウ"],
    &["リュウ","ル"],
    &["コウ","キョウ"],
    &["シン"],
    &["テイ","ダイ","デ"],
    &["ビョウ"],
    &["ソウ","ソ"],
    &["ゾウ"],
    &["ヘイ","ビョウ"],
    &["イ"],
    &["チ"],
    &["シン"],
    &["エツ"],
    &["テイ"],
    &["セイ"],
    &["シ"],
    &["セイ","ショウ"],
    &["ダン","トン"],
    &["ベン"],
    &["ゴ"],
    &["ジョウ"],
    &["エイ"],
    &["キョウ"],
    &["ホウ"],
    &["サン"],
    &["ギョ","ゴ"],
    &["マイ"],
    &["カ"],
    &["カン"],
    &["セン"],
    &["コウ"],
    &["シュ"],
    &["ショウ"],
    &["シ"],
    &["フク"],
    &["ゲン"],
    &["カク"],
    &["イン"],
    &["ライ"],
    &["ホ"],
    &["ショウ"],
    &["ツイ"],
    &["ビン","ベン"],
    &["チョ"],
    &["ダイ","タイ"],
    &["バツ"],
    &["ケン"],
    &["シ"],
    &["ザイ"],
    &["キ"],
    &["ザン"],
    &["ネン"],
    &["チ"],
    &["ト","ツ"],
    &["セン"],
    &["シュウ"],
    &["フク"],
    &["ソク"],
    &["キョウ"],
    &["ハイ"],
    &["マイ"],
    &["ヒ"],
    &["バイ"],
    &["シ"],
    &["ソ","ス"],
    &["キョウ"],
    &["ダ"],
    &["ゲン","ゴン"],
    &["ユウ"],
    &["カ"],
    &["ケイ","ギョウ"],
    &["チョウ"],
    &["シ"],
    &["テイ"],
    &["メイ","ミョウ"],
    &["レイ"],
    &["ヨウ"],
    &["ギ"],
    &["イン"],
    &["ショウ","ゾウ"],
    &["ク"],
    &["セン"],
    &["バン"],
    &["ハイ"],
    &["トウ"],
    &["オウ","ノウ"],
    &["ボ"],
    &["セイ"],
    &["リョウ"],
    &["カク"],
    &["ヒョウ"],
    &["ハン","バン"],
    &["カン"],
    &["ゾク"],
    &["キョウ","ケイ"],
    &["ソウ"],
    &["ソツ","リツ"],
    &["トク"],
    &["チョウ"],
    &["カ"],
    &["ヨク"],
    &["ジャク"],
    &["ギ"],
    &["リツ","リチ"],
    &["ベン"],
    &["ソン"],
    &["ケイ"],
    &["カン"],
    &["シュ"],
    &["ノウ"],
    &["エン"],
    &["ヤク"],
    &["ショウ"],
    &["ヒ"],
    &["ジョウ"],
    &["キョウ","ゴウ"],
    &["キャク","カク"],
    &[""],
    &["シャ"],
    &["ボ"],
    &["フ"],
    &["ソク"],
    &["シュウ","ジュウ"],
    &["ダン"],
    &["カ"],
    &["ヨ"],
    &["サク"],
    &["ダン"],
    &["ショウ"],
    &["ガン"],
    &["シャ"],
    &["テキ"],
    &["ボウ","ボツ"],
    &["ガン"],
    &["リョウ"],
    &["サン"],
    &["クン"],
    &["ショク","ジキ"],
    &["シ"],
    &["ソ"],
    &["シュ","ス"],
    &["ショウ"],
    &["ショウ"],
    &["ジ"],
    &["ボウ"],
    &["ケン"],
    &["シャ"],
    &["ジョウ"],
    &["ネン"],
    &["サク","サ"],
    &["タイ"],
    &["ユウ"],
    &["カン"],
    &["ハ"],
    &["サイ","サ"],
    &["ヨ"],
    &["アン"],
    &["ビ"],
    &["カイ","エ"],
    &["ノウ"],
    &["ドク","トク","トウ"],
    &["ビョウ"],
    &["ト"],
    &["ジョウ"],
    &["ゲキ"],
    &["イ"],
    &["ソウ"],
    &["チュウ"],
    &["カイ"],
    &["カク"],
    &["ニン"],
    &["シュウ"],
    &["コウ"],
    &["シン"],
    &["モン"],
    &["キン"],
    &["コン"],
    &["テイ"],
    &["トウ"],
    &["コウ"],
    &["エイ"],
    &["テン"],
    &["カイ","エ"],
    &["ギ"],
    &["ギョ","リョウ"],
    &["トツ"],
    &["ヒ"],
    &["タン"],
    &["レツ"],
    &["ソク"],
    &["シ"],
    &["チ"],
    &["ジュク"],
    &["メイ","ミョウ"],
    &["エキ","イ"],
    &["コウ","オウ"],
    &["ケン","ゴン"],
    &["シン","ジン"],
    &["メン"],
    &["ギャク"],
    &["セイ"],
    &["イ"],
    &["コ"],
    &["シュウ","シュ"],
    &["ソウ"],
    &["ガイ","カイ"],
    &["テイ"],
    &["ロ"],
    &["ショウ"],
    &["セイ","ショウ"],
    &["フ"],
    &["ケン"],
    &["タン"],
    &["サン"],
    &["セイ","ショウ"],
    &["チュウ"],
    &["リン"],
    &["ロウ"],
    &["カ"],
    &["ヒン","ビン"],
    &["ボウ"],
    &["キ"],
    &["セイ","ショウ"],
    &["キュウ"],
    &["ヒ"],
    &["シ"],
    &["サイ"],
    &["ショウ"],
    &["カイ"],
    &["セキ"],
    &["ゴ"],
    &["エキ","ヤク"],
    &["ドク"],
    &["コツ"],
    &["ケン"],
    &["コウ"],
    &["カイ"],
    &["ホン"],
    &["セキ"],
    &["キョク","ゴク"],
    &["テツ"],
    &["コウ"],
    &["トウ"],
    &["セツ","セチ"],
    &["ドク"],
    &["ゲイ"],
    &["ユ"],
    &["ヘン"],
    &["サツ","サク"],
    &["キョウ"],
    &["サ"],
    &["サツ"],
    &["リ"],
    &["カク"],
    &["リク"],
    &["マツ","バツ"],
    &["ネン"],
    &["バ"],
    &["ロク"],
    &["セイ","ショウ"],
    &["マイ"],
    &["フ"],
    &["ショウ"],
    &["タク"],
    &["テキ"],
    &["ソウ"],
    &["セイ","ショウ"],
    &["ニン"],
    &["ドウ"],
    &["コ"],
    &["リン"],
    &["ダイ","タイ"],
    &["セン"],
    &["ワ","オ"],
    &["チュウ"],
    &["コン"],
    &["テツ"],
    &["キツ"],
    &["ザ"],
    &["ビ"],
    &["シュ"],
    &["シン"],
    &["コ","カ"],
    &["サイ"],
    &["ショウ"],
    &["ハ"],
    &["カイ"],
    &["ゾウ"],
    &["ガ"],
    &["キョ","コ"],
    &["キョ"],
    &["ヘイ"],
    &["ハン"],
    &["ヒツ"],
    &["リョク","ロク"],
    &["ショク"],
    &["ミャク"],
    &["セツ"],
    &["チク"],
    &["キョク"],
    &["オン"],
    &["カ","ケ"],
    &["シ"],
    &["サン"],
    &["エン"],
    &["ジャ"],
    &["ケイ"],
    &["ラク"],
    &["モウ"],
    &["フ"],
    &["カ","ケ"],
    &["キョウ"],
    &["ショウ"],
    &["ガイ"],
    &["エン"],
    &["アン"],
    &["ゲキ"],
    &["ヨウ"],
    &["ハン","バン"],
    &["カイ"],
    &[""],
    &["キョ"],
    &["イ"],
    &["ド"],
    &["セツ"],
    &["ケツ"],
    &["バイ"],
    &["カイ"],
    &["チュウ"],
    &["シ"],
    &["アツ"],
    &["テン"],
    &["イ","ユイ"],
    &["ジョウ"],
    &["ヒ"],
    &["ニク"],
    &["カイ","ケ"],
    &["バイ"],
    &["ケイ"],
    &["トウ"],
    &["チョウ"],
    &["ケン"],
    &["シャク"],
    &["シュウ"],
    &["カク"],
    &["ヒ"],
    &["ソウ"],
    &["エイ"],
    &["ケン"],
    &["ボウ","モウ"],
    &["ホウ"],
    &["リョウ"],
    &["ホウ"],
    &["ユ"],
    &["サイ"],
    &["ギョク"],
    &["ゲン"],
    &[""],
    &["トウ"],
    &["シ","ス"],
    &["ジョ","ジ"],
    &["コウ"],
    &["ゾウ"],
    &["コ","ク"],
    &["キ"],
    &["トウ"],
    &["セイ"],
    &["トン"],
    &["ゼツ"],
    &["ボク"],
    &["シ"],
    &["マン","バン"],
    &["ミン"],
    &["コ"],
    &["ブツ"],
    &["サツ","サイ","セツ"],
    &["ガン"],
    &["キン"],
    &["キュウ"],
    &["キン"],
    &["ショウ"],
    &["エイ"],
    &["ゴ"],
    &["メイ"],
    &["ジュウ"],
    &["ソ"],
    &["ヒョウ"],
    &["スイ"],
    &["トウ"],
    &["ヒ"],
    &["ロウ"],
    &["ハン"],
    &["イ"],
    &["トウ"],
    &["セイ"],
    &["フク"],
    &["テイ"],
    &["ジュウ","ショウ","ジュ"],
    &["シャ"],
    &["ラン"],
    &["ボウ","バク"],
    &["ガイ"],
    &["ショウ"],
    &["ヘン"],
    &["キョウ","ケイ","キン"],
    &["ウン"],
    &["ヘン"],
    &["カン"],
    &["イ"],
    &["ソウ"],
    &["ゴ"],
    &["ヒ"],
    &["カン"],
    &["ハイ"],
    &["ト"],
    &["イク"],
    &["キ"],
    &["ゴ"],
    &["ケン"],
    &["メイ"],
    &["ジュン"],
    &["シン"],
    &["カン"],
    &["アン"],
    &[""],
    &["ブ"],
    &["ジュウ"],
    &["ジョク"],
    &["ダン"],
    &["オウ"],
    &[""],
    &["シ"],
    &["チク"],
    &["リン"],
    &["ウ"],
    &["エン"],
    &["ガン"],
    &["リョウ"],
    &["キ"],
    &["キュウ"],
    &["ギョ"],
    &["コ"],
    &["コウ","オウ"],
    &["コク"],
    &["サイ"],
    &["シ"],
    &["ジ"],
    &["セイ","ショウ"],
    &["シン"],
    &["セン"],
    &["チ"],
    &["トウ"],
    &["バク"],
    &["ベイ","マイ"],
    &["リ"],
    &["イ"],
    &["オウ"],
    &["キュウ","グウ","ク"],
    &["ク"],
    &["ナン"],
    &["ケツ"],
    &["コ"],
    &["コウ"],
    &["サイ"],
    &["シュ"],
    &["ショウ"],
    &["ショウ"],
    &["セイ"],
    &["ソク"],
    &["タン"],
    &["ホク"],
    &["チュウ"],
    &["チョウ","テイ"],
    &["チョウ"],
    &["テキ"],
    &["トウ"],
    &["トウ","ズ"],
    &["トウ","ト"],
    &["ドウ"],
    &["ハ"],
    &[""],
    &["コ"],
    &["セイ","サイ"],
    &[""],
    &["ヒツ"],
    &["ヒョウ"],
    &["ヨウ"],
    &["ヨウ"],
    &["イ"],
    &["エイ"],
    &["エン"],
    &["オク"],
    &["カ"],
    &["カン"],
    &["カ"],
    &["ガ"],
    &["カイ"],
    &["カン"],
    &["キ"],
    &["キ"],
    &["キ"],
    &["キュウ"],
    &["キョ"],
    &["キョウ"],
    &["ジ"],
    &["グン"],
    &["グン"],
    &["ケイ"],
    &["コウ"],
    &["コウ"],
    &["サツ"],
    &["サツ"],
    &["シ"],
    &["シ"],
    &["シ"],
    &["コウ"],
    &["ジ","ニ"],
    &["ジ"],
    &["シュウ"],
    &["ジュン"],
    &["ショウ"],
    &["ショウ"],
    &["ショウ"],
    &["シン","ジン"],
    &["セン"],
    &["ソウ"],
    &["シュウ"],
    &["ソウ"],
    &["ソン"],
    &["タイ"],
    &["タイ"],
    &["チュウ"],
    &["チョ"],
    &["チョウ"],
    &["チョウ"],
    &["テイ"],
    &["テン"],
    &["シ"],
    &["トウ"],
    &["バイ"],
    &["ハク","バク"],
    &["ヒョウ"],
    &["フ","フウ"],
    &["フ"],
    &["フク"],
    &["フン"],
    &["ヘイ","ヒョウ"],
    &["ホウ"],
    &["ダイ","タイ"],
    &["ヨク"],
    &["ルイ"],
    &["レイ"],
    &["レキ"],
    &["ロク"],
    &["イン"],
    &["エイ"],
    &["エキ"],
    &["オウ"],
    &["オウ"],
    &["シ"],
    &["オン"],
    &["カ"],
    &["カ"],
    &["ガ"],
    &["カク","コウ"],
    &["ガク"],
    &["カン"],
    &["カン"],
    &["ガン","ゲン"],
    &["キュウ","ク"],
    &["ゴ"],
    &["キュウ"],
    &["キョウ","ケイ"],
    &["キン"],
    &["グン"],
    &["ケツ"],
    &["ケン"],
    &["ケン"],
    &["コウ"],
    &["コウ"],
    &["サイ"],
    &["ロク"],
    &["ビョウ"],
    &["サイ"],
    &["ザイ","サイ"],
    &["ザイ"],
    &["ザツ","ゾウ"],
    &["サン"],
    &["シ"],
    &["シ"],
    &["シ"],
    &["シ"],
];

pub(crate) const KA_KUNYOMIS: [&'static [&'static str];1235] = [
    &["ひと"],
    &["なに","なん"],
    &["なな","なの","ななつ"],
    &["か","かう"],
    &["しめ","しめす"],
    &["の","のべる"],
    &[""],
    &["お","おる","おり"],
    &[""],
    &["した"],
    &["ぜに"],
    &[""],
    &["はか","はかる"],
    &["や","よう","やっつ"],
    &[""],
    &["そこ","そこねる","そこなう"],
    &["しりぞ","しりぞく","しりぞける"],
    &[""],
    &[""],
    &["おか","おかす"],
    &[""],
    &["たわら"],
    &[""],
    &["と","とむ","とみ"],
    &["ここの","ここのつ"],
    &[""],
    &[""],
    &["はか"],
    &["むく","むくい","むくいる","むくう"],
    &["ふせ","ふせぐ"],
    &[""],
    &["つと","つとめる","つとまる"],
    &["わた"],
    &["あま","あまり","あまる","あます"],
    &[""],
    &["とお","と"],
    &[""],
    &[""],
    &[""],
    &["そ","そう"],
    &["はい"],
    &[""],
    &["わ","わる","わり","われる","さ","さく"],
    &["かぶ"],
    &["ほ","ひ","ほす","ほし","ひる"],
    &["ま","まく","まき"],
    &["まつ","またせる"],
    &[""],
    &["あぶ","あや","あぶない","あやうい","あやぶむ","あやうく"],
    &[""],
    &["たっと","とうと","たっとい","とうとい"],
    &[""],
    &[""],
    &["あな"],
    &["きぬ"],
    &[""],
    &["みなもと"],
    &[""],
    &["おのれ"],
    &[""],
    &[""],
    &["べに","くれない"],
    &["はがね"],
    &["きざ","きざむ","きざみ"],
    &[""],
    &["すな"],
    &["た","さば","たつ","さばく"],
    &[""],
    &["はな","はなす","はなし"],
    &["かいこ"],
    &["いた","いたる"],
    &["すがた"],
    &[""],
    &[""],
    &[""],
    &[""],
    &["つ","つく"],
    &[""],
    &["たて"],
    &["ひら","ひらく","あ","あく","あける"],
    &["ちぢ","ちぢむ","ちぢまる","ちぢめる","ちぢれる","ちぢらす"],
    &[""],
    &[""],
    &[""],
    &["きず","いた","いたむ","いためる"],
    &["む","むす","むれる","むらす"],
    &["はり"],
    &[""],
    &["た","たれる","たらす","たれ"],
    &[""],
    &["と","とじる","とざす","し","しめる","しまる"],
    &["も","さか","もる","さかん","さかんな"],
    &["まこと"],
    &[""],
    &["いずみ"],
    &["そ","し","そめる","ぞめ","そまる","しみる","しみ"],
    &["よ","よい"],
    &["かな","かなでる"],
    &["よそお","よそおう"],
    &[""],
    &["みさお","あやつ","あやつる"],
    &["とも"],
    &[""],
    &[""],
    &["あたた","あたたかい","あたたまる","あたためる"],
    &[""],
    &[""],
    &["いただ","いただく","いただき"],
    &["しお"],
    &[""],
    &["う","うつ"],
    &[""],
    &["うえ","うわ","かみ","あ","あげる","あがる","のぼ","のぼる"],
    &["たち"],
    &[""],
    &["おさ"," おさめる","おさまる"],
    &[""],
    &["おが","おがむ"],
    &[""],
    &[""],
    &[""],
    &["ひ","ひめる"],
    &["はら"],
    &["ふる","ふるう"],
    &["て","た"],
    &[""],
    &["おぎな","おぎなう"],
    &["たから"],
    &[""],
    &[""],
    &[""],
    &[""],
    &[""],
    &[""],
    &["おさない"],
    &["かみ"],
    &[""],
    &["たまご"],
    &[""],
    &["うら"],
    &["のぞ","のぞむ"],
    &["ほが","ほがらかな"],
    &[""],
    &["ちが","ちがう","ちがえる"],
    &["するど","するどい"],
    &["けむ","けむる","けむい","けむり"],
    &["か","かく"],
    &["けが","よご","きたな","けがす","けがれる","けがらわしい","よごす","よごれる","きたない"],
    &["お","おす","おさえる"],
    &[""],
    &[""],
    &["くつ"],
    &["か","かける","かけ","かかる","かかり"],
    &["あせ"],
    &[""],
    &["わずら","わずらう"],
    &["いく","いくつ","いくら"],
    &["あき"],
    &["つ","つめる","つまる","つむ"],
    &["さけ","さけぶ"],
    &[""],
    &["はさ","はさむ","はさまる"],
    &[""],
    &["すみ"],
    &["ほ","ほる"],
    &["かたむ","かし","かたむける","かたむく","かしげる"],
    &["のき"],
    &["か","かれる","からす"],
    &["やま"],
    &["やと","やとう"],
    &["さら","ふ","さらに","ふける","ふかす"],
    &[""],
    &["あら","あ","あらい","あらす","あれる"],
    &[""],
    &["か","かお","かおり","かおる"],
    &["かた","かたい"],
    &["こ","こむ","こめる"],
    &[""],
    &["さ","さく"],
    &["ゆき"],
    &["あぶら"],
    &["しめ","しめる","しめす"],
    &["ふね","ふな"],
    &["やわ","やわらかい","やわな"],
    &["お"],
    &["め","めす"],
    &["とこ","ゆか"],
    &["のぼ","のぼる"],
    &["たた","たたむ","たたみ"],
    &["ふ","さわ","ふれる","さわる"],
    &["あめ","あま"],
    &["の","のびる","のばす"],
    &["ふ","ふく"],
    &[""],
    &[""],
    &["あと"],
    &[""],
    &["し","うらな","しめる","うらなう"],
    &["ふた"],
    &["さが","さがす"],
    &["は","はく"],
    &["あ","あたり","あたる","あてる"],
    &[""],
    &["にく","にくむ","にくい","にくらしい","にくしみ"],
    &["おく","おくる"],
    &["ふくろ"],
    &["か","かわる","かえる"],
    &[""],
    &[""],
    &[""],
    &["こ","こえる","こす"],
    &["しず","しずむ","しずめる"],
    &["の","のむ"],
    &["めずら","めずらしい"],
    &["どろ"],
    &["しずく","したた","したたる"],
    &["との"],
    &["ぬ","ぬる","ぬり"],
    &["に","のが","にげる","にがす","のがす","のがれる"],
    &[""],
    &["つつ"],
    &["にぶ","にぶい","にぶる"],
    &["やわ","やわらかい"],
    &["した","しも","さ","さがる","さげる","くだ","くだる","ください","お","おろす","おりる"],
    &["し","しる","しらす","しらせる"],
    &["なや","なやむ","なやみ","なやます"],
    &["こ","こい","こさ"],
    &["とまる","とめる"],
    &["うす","うすい","うすめる","うすまる","うすらぐ","うすれる"],
    &[""],
    &["はだ"],
    &["かみ"],
    &[""],
    &[""],
    &["う","うく","うかれる","うかぶ","うかべる"],
    &["まえ"],
    &[""],
    &["ま","まう","まい"],
    &[""],
    &["はば"],
    &["わ","わく","わかす"],
    &["と","つか","とらえる","とらわれる","とる","つかまえる","つかまる"],
    &["だ","いだ","かか","だく","いだく","かかえる"],
    &[""],
    &["みが","みがく"],
    &["う","うめる","うまる","うもれる"],
    &["のち","うし","うしろ","あと","おく","おくれ"],
    &["と","とける","とかす","とく"],
    &["こし"],
    &["おど","おどる","おどり"],
    &["つぶ"],
    &[""],
    &["すず","すずしい","すずむ"],
    &[""],
    &["なみだ"],
    &[""],
    &[""],
    &["さず"," さずける","さずかる"],
    &[""],
    &["うで"],
    &["はなれる","はなす","はな"],
    &["n/a"],
    &["ぬ","ぬぐ","ぬげる"],
    &[""],
    &["わざ"],
    &["おく","おそ","おくれる","おくらす","おそい","おそく"],
    &["おも","おもう","おもい"],
    &["よ","よる"],
    &["うつ","は","うつる","うつす","はえる"],
    &[""],
    &["なか"],
    &["で","だ","でる","だす"],
    &[""],
    &["あ","あう"],
    &["もの"],
    &["かえ","かえす","かえる","かえり"],
    &[""],
    &[""],
    &["ただ","ただす","なお","なおる","なおす"],
    &["なら","ならう","ならい"],
    &["こま","こまる"],
    &["みぎ"],
    &["も","もつ","もち"],
    &["しら","ととの","しらべる","ととのえる","ととのう"],
    &["ひ","ひく"],
    &["き","きく","きこえる"],
    &["の"],
    &["むら"],
    &["せ","せい","そむく","そむける"],
    &["たか","たかい","たかさ","たかまる","たかぶる","たかめる"],
    &["ひく","ひくい","ひくまる","ひくめる"],
    &["なが","ながい"],
    &["ひだり"],
    &["みじか","みじかい"],
    &["き","つ","きる","きせる","つく"],
    &["たの","たのしむ","たのしい","たのしみ"],
    &["かわ"],
    &[""],
    &["と","とう","とい","とん"],
    &["も","もって"],
    &["おお","おおい","おおく"],
    &["わかい","わか","も","もし"],
    &["ふと","ふとる","ふとい","ふとった","ふとさ"],
    &["いろ"],
    &["と","や","とめる","とまる","やむ","やめる"],
    &["とお","とおい","とおく"],
    &["いそが","いそがしい"],
    &["か","かりる"],
    &[""],
    &["い","はい","いり","いる","はいる","いれる","いれ"],
    &["あら","あたら","あたらしい","あらた","にい"],
    &["おし","おそ","おしえる","おそわる"],
    &["あじ","あじわう","あじわい"],
    &["しろ","しら","しろい"],
    &["おんな","め"],
    &["あお","あおい"],
    &["くろい","くろ"],
    &["かた"],
    &["はこ","はこぶ"],
    &["うご","うごく","うごかす","うごき"],
    &["からだ"],
    &["いた","いたい","いたむ","いたましい","いためる","いたみ"],
    &["もと"],
    &[""],
    &["か","かわる","かわり","かえる"],
    &["おとこ"],
    &["つか","つかれる","つかれ"],
    &["ね","ねる","ねかす","ねかせる"],
    &["あめ","あま"],
    &["あたま","かしら"],
    &["はか","はかる"],
    &["たて"],
    &["さぐ","さが","さぐる","さがす"],
    &["うしな","うしなう"],
    &[""],
    &["すく","すこ","すくない","すこし"],
    &["ひと"],
    &["みずか","おの","みずから","おのずから"],
    &["よし"],
    &["な","ない","なし","なくす","なくなる"],
    &[""],
    &["い","いう","こと"],
    &["たび"],
    &["あつ","つど","あつまる","あつまり","あつめる","つどう","つどい"],
    &["おと","ね"],
    &["き","きめる","きまる"],
    &["こと"],
    &["ふた","ふたつ","ふたり"],
    &["み","みる","みえる","みせる"],
    &["き","きる","きり","きれる"],
    &[""],
    &["わる","あ","わるい","わるさ","あし","あしき"],
    &["み","みの","みのる","みのり"],
    &["や","やむ","やみ","やまい"],
    &["おさ","なお","おさめる","おさまる","なおる","なおす"],
    &[""],
    &["こころ"],
    &["た","たつ"],
    &[""],
    &["さき"],
    &[""],
    &["ふみ"],
    &[""],
    &["ね","ねる","ねり"],
    &["か","かす","かし"],
    &["もり"],
    &["こころ","ため","こころみる","こころみ","ためす","ためし"],
    &[""],
    &[""],
    &["まった","まったく","すべ","すべて"],
    &["くるま"],
    &[""],
    &["め","ま"],
    &[""],
    &["と","とぐ"],
    &["きわ","きわめる"],
    &["むろ"],
    &["つら","つ","つらなる","つらねる","つれる","つれ"],
    &["はな"],
    &["つか","つかえる"],
    &["へ","た","へる","たつ"],
    &["くに"],
    &["す","すむ","すみ","すます","すませる"],
    &["まと"],
    &["かた","むずか","かたい","かたさ","むずかしい"],
    &["ひろ","ひろまる","ひろめる","ひろがる","ひろげる","ひろい","ひろさ"],
    &["おな","おなじ","おなじく"],
    &["なつ"],
    &["はる"],
    &["かなら","かならず"],
    &["い","かなめ","いる"],
    &["まじ","ま","か","まじわる","まじえる","まじる","まざる","まぜる","かう","かわす"],
    &["とき"],
    &["とお","かよ","とおる","とおり","とおす","とおし","かよう"],
    &["ふゆ"],
    &["はし","はしる","はしり"],
    &["え","おも","かさ","おもい","おもさ","おもり","おもたい","おもし","かさねる","かさなる"],
    &[""],
    &["やしろ"],
    &["つと","つとめる","つとまる"],
    &["や"],
    &[""],
    &["つくえ"],
    &["あいだ","ま"],
    &["つか","つかう","つかい"],
    &["さむ","さむい"],
    &["あつ","あつい","あつさ"],
    &["つめ","ひ","さ","つめたい","ひえる","ひや","ひややか","ひやす","ひやかす","さめる","さます"],
    &["だれ"],
    &["いそ","いそぐ","いそぎ"],
    &["もち","もちいる"],
    &["ころ"],
    &["うち"],
    &["つた","つたわる","つたえる","つたう","つたい"],
    &["なか","なかば"],
    &["ほ","ほっする","ほしい"],
    &["はじ","はつ","うい","そ","はじめて","はじめ","はつ","そめる"],
    &["つ","つぐ","つぎ"],
    &["もっと","もっとも"],
    &["た"],
    &["いし"],
    &["はら"],
    &[""],
    &["あた","あたり","べ"],
    &["みち"],
    &["わ","わける","わかる","わかれる"],
    &[""],
    &[""],
    &["ところ"],
    &["よこ"],
    &[""],
    &["ま","まがる","まげる"],
    &["はし"],
    &["む","むく","むき","むける","むかう","むこう"],
    &[""],
    &[""],
    &["つき"],
    &["かど","つの"],
    &["あか","あかい","あからむ","あからめる"],
    &["いわ","いわう","いわい"],
    &["あい"],
    &[""],
    &["つ","つぐ"],
    &[""],
    &["はら","はらう","はらい"],
    &[""],
    &["はたら","はたらく","はたらき"],
    &["ひ"],
    &["そな","とも","そなえ","そなえる"],
    &["かれ","かの"],
    &["な","なく"],
    &["お","ふ","おりる","おろす","ふる","ふり"],
    &["は","はれる","はれ","はらす"],
    &["くも","くもる","くもり"],
    &["そら","あ","から","むな","あく","あき","あける","から","むなしい","むなしさ"],
    &["ゆう"],
    &[""],
    &["そな","そなえる","そなわる"],
    &["み","みっか","みっつ"],
    &["みず"],
    &["ある","あゆ","あるく","あゆむ","あゆみ"],
    &["うた","うたう"],
    &["あし","た","たる","たりる","たす"],
    &["くち"],
    &["よ"],
    &[""],
    &[""],
    &["もの"],
    &["くば","くばる"],
    &[""],
    &["き","こ"],
    &[""],
    &["ただ","ただしい","ただす","まさ","まさに"],
    &[""],
    &["かんが","かんがえる","かんがえ"],
    &["はか","はかる","はかり","はからう"],
    &["おく"],
    &["さま"],
    &["ねむ","ねむい","ねむる"],
    &["そと","ほか","はず","はずす","はずれる"],
    &[""],
    &["かね","かな"],
    &["むかし"],
    &[""],
    &["よ","よる","より","よせる"],
    &["かぜ","かざ"],
    &["よ","よぶ"],
    &["いか","おこ","いかる","おこる"],
    &["やど","やどる","やどす"],
    &["わた","わたる","わたす"],
    &["たび"],
    &["と","とる","とり"],
    &["つち"],
    &["ぬす","ぬすむ","ぬすみ"],
    &["た","たつ","たてる","たて"],
    &[""],
    &["もう","もうす","もうし"],
    &["ねが","ねがう"],
    &["ぬし","おも","おもに","あるじ"],
    &["せき","かか","かかわる"],
    &[""],
    &["わか","わかれ","わかれる"],
    &[""],
    &["ひ","か"],
    &[""],
    &["さだ","さだか","さだめる","さだまる"],
    &["うつ","うつす","うつる"],
    &["ま"],
    &[""],
    &[""],
    &["わす","わすれる"],
    &["おぼ","さ","おぼえる","さます","さめる"],
    &[""],
    &["きみ"],
    &[""],
    &["あつ","あつい"],
    &["し","しぬ","しに"],
    &["むす","ゆ","むすぶ","ゆう","ゆわえる"],
    &[""],
    &[""],
    &["うし"],
    &["ちち","ち"],
    &["さわ"],
    &["まち"],
    &[""],
    &["ち"],
    &["めし"],
    &["こた","こたえ","こたえる"],
    &["みせ"],
    &["いと","いとしい","いとおしむ"],
    &["あ","あう","あい","あわす","あわせる"],
    &["かな","かなしい","かなしむ","かなしさ","かなしみ"],
    &[""],
    &[""],
    &["さいわ","さいわい","さち","しあわ","しあわせ"],
    &["と","とぶ","とばす"],
    &["いま"],
    &["みみ"],
    &["きら","きらう","きらい","いや","いやがる"],
    &["まど"],
    &["よろこ","よろこぶ","よろこび","よろこばす"],
    &["そ","そる","そらす"],
    &[""],
    &["こ","こう","こい","こいしい","こいする"],
    &["つ","つぐ","つげる"],
    &["ゆる","ゆるす","ゆるし"],
    &[""],
    &["ちい","ちいさい","こ","お"],
    &["もど","もどす","もどる"],
    &[""],
    &[""],
    &["しな"],
    &["いま","ま","いまだ","まだ"],
    &[""],
    &["うみ"],
    &["しま"],
    &[""],
    &["かお"],
    &["やす","やすむ","やすみ","やすめる"],
    &["おも","おもて","つら"],
    &["くわだ","くわだてる"],
    &["いち"],
    &["たの","たのむ","たのもしい","たよ","たよる"],
    &[""],
    &["おもて","あらわ","あらわす","あらわれる"],
    &[""],
    &[""],
    &["ば"],
    &[""],
    &["まな","まなぶ"],
    &["い","いく","ゆ","ゆく","おこな","おこなう"],
    &["かか","かかる","かかり","かかわる","かかわり"],
    &["わけ"],
    &[""],
    &["つづ","つづく","つづける","つづき"],
    &["きわ"],
    &["のぞ","のぞむ","のぞみ"],
    &["な","なる","なす"],
    &[""],
    &[""],
    &["たば","たばねる"],
    &["いえ","や"],
    &["う","うける","うかる"],
    &["あ","ある"],
    &[""],
    &[""],
    &[""],
    &["おく","おくる"],
    &["かず","かぞ","かぞえる"],
    &["たま"],
    &["あそ","あそび","あそぶ"],
    &["まね","まねく","まねき"],
    &["かえ","かえる"],
    &["えら","えらぶ"],
    &[""],
    &[""],
    &[""],
    &["た","たて","たつ","たち","たてる"],
    &[""],
    &["もと","もとい"],
    &["あつ","あつい"],
    &["すす","すすめる"],
    &[""],
    &["ちか","ちかい","ちかく"],
    &["やしな","やしなう"],
    &["ば","ばける","ばかす"],
    &[""],
    &[""],
    &["かた"],
    &["くる","にが","くるしい","くるしむ","くるしめる","にがい","にがる"],
    &["み","みちる","みつ","みたす"],
    &["ま","ふ","ます","まし","ふえる","ふやす"],
    &["こえ","こわ"],
    &["あらわ","あらわれる","あらわす"],
    &["ちち"],
    &["あ","ある"],
    &["ゆめ"],
    &["の","のる","のり","のせる"],
    &["はな","はなす","はなつ","はなれる"],
    &[""],
    &["ちから"],
    &[""],
    &["と","とく"],
    &["お","おちる","おとす"],
    &["な"],
    &["はは"],
    &["はた"],
    &[""],
    &["くわ","くわしい"],
    &["と","とく","とかす","とける"],
    &["かま","かまえる","かまう"],
    &["なさ","なさけ"],
    &["とも"],
    &[""],
    &["しず","しずか","しずまる","しずめる"],
    &["なが","ながれる","ながれ","ながす"],
    &["あに"],
    &[""],
    &[""],
    &["ひか","ひかる","ひかり"],
    &[""],
    &["おどろ","おどろく","おどろかす"],
    &["たす","たすける","たすかる","すけ"],
    &["もと","もとめる"],
    &["と","とど","とめる","とまる","とどまる","とどめる"],
    &["おこ","おこる","おこす"],
    &["ふか","ふかい","ふかまる","ふかめる"],
    &["おとうと"],
    &["ねこ"],
    &[""],
    &[""],
    &["たい","ひらたい","たいら","ひら"],
    &["くらい"],
    &["お","おく"],
    &["すす","すすむ","すすめる"],
    &["こ","こす","こえる"],
    &["にわ"],
    &["いきお","いきおい"],
    &["あね"],
    &[""],
    &[""],
    &[""],
    &["まも","まもる"],
    &[""],
    &["かげ"],
    &["ひび","ひびく","ひびき","ひびかす"],
    &["おとずれる","たずねる","おとず","たず"],
    &["まいる","まい"],
    &["おん"],
    &["いもうと"],
    &["はたす","はてる","はて","は"],
    &["なれる","ならす","な"],
    &["もっぱら","もっぱ"],
    &["せめる","せ"],
    &["おもむき"],
    &[""],
    &[""],
    &[""],
    &["かぎる","かぎり","かぎ"],
    &["たしか","たしかめる","たし"],
    &[""],
    &["く","くる","きた","きたる"],
    &["たもつ","たも"],
    &[""],
    &["おう","お"],
    &["たより","たよ"],
    &["あらわす","いちじるしい","あらわ","いちじる"],
    &["かわる","かわり","かえる","よ","しろ","か"],
    &["ぬく","ぬき","ぬける","ぬかす","ぬかる","ぬ"],
    &["かた"],
    &["うかがう","うかがい","うかが"],
    &[""],
    &["お","おきる","おこす"],
    &["のこる","のこす","のこり","のこ"],
    &[""],
    &["は","はじ","はじらう","はじらい","はじる","はずかしい"],
    &["みやこ"],
    &["あらう","あら"],
    &["す"],
    &[""],
    &["かわ"],
    &["おそれる","おそる","おそろしい","おそ"],
    &["やぶれる","やぶ"],
    &["ごと"],
    &["くらべる","くら"],
    &[""],
    &[""],
    &[""],
    &["むね","むな"],
    &["うつ","うち"],
    &["おごそか","きびしい","おごそ","きび"],
    &["やさし","やさしさ","すぐれる","やさ","すぐ"],
    &[""],
    &["かた","かたち"],
    &["あさ"],
    &[""],
    &["ほど"],
    &["いのち"],
    &[""],
    &[""],
    &[""],
    &["しるし"],
    &[""],
    &[""],
    &[""],
    &[""],
    &[""],
    &["たおれる","たおす","たお"],
    &[""],
    &["つのる"],
    &[""],
    &["はかる","はかり","はか"],
    &["おのおの"],
    &[""],
    &[""],
    &["かえる","かわる","か"],
    &[""],
    &["きそう","せる","きそ","せ"],
    &["あらそう","あらそい","あらそ"],
    &["ひきいる","ひき"],
    &["える","うる","え","う"],
    &["はる","はり","は"],
    &["あたい"],
    &["おさえる","おさ"],
    &["よわい","よわる","よわまる","よわめる","よわ"],
    &["わざ"],
    &[""],
    &[""],
    &["たっとい","たっとぶ","とうとい","とうとぶ","たっと","とうと"],
    &["うやまう","うやまい","うやま"],
    &[""],
    &["たね"],
    &[""],
    &["のびる","のべる","のべ","のばす","の"],
    &["くすり"],
    &["わら","え","わらう","わらい","えむ","えみ"],
    &[""],
    &["つね","とこ"],
    &["つよ","つよい","つよめる","つよまる","し","しいる"],
    &[""],
    &["とど","とどく","とどける"],
    &[""],
    &["く","くれる","くらす"],
    &["こわ","こわい","こわがる"],
    &["いき"],
    &["ひろ","ひろう"],
    &[""],
    &["ひま"],
    &["あず","あずける","あずかる"],
    &[""],
    &["た","ことわ","たつ","ことわる","ことわり"],
    &["うけたまわ","うけたまわる"],
    &["まる","まるい","まるめる"],
    &["あやまる","あやま"],
    &["かたき"],
    &[""],
    &["きし"],
    &["よ","い","よい","いい"],
    &["ち","ちる","ちらす","ちらかす","ちらかる","ちらばる","ちらばす"],
    &[""],
    &["く","くう","た","たべる"],
    &["ささ","ささえる"],
    &["く","くむ","くみ"],
    &["まも","もり","まもる","まもり"],
    &["き","け","きえる","けす"],
    &["あきな","あきなう","あきない"],
    &["にる","に"],
    &["おか","おかす"],
    &["けわ","けわしい"],
    &["す","すてる"],
    &[""],
    &["とし"],
    &["つく","つくる","つくり"],
    &[""],
    &["いさ","いさむ","いさましい"],
    &[""],
    &[""],
    &["ふたた","ふたたび"],
    &["あた","あたえる"],
    &[""],
    &["うつく","うつくしい"],
    &[""],
    &[""],
    &["よ","よむ"],
    &["えが","えがく"],
    &[""],
    &["しろ"],
    &["はげ","はげしい"],
    &["こと","ことなる"],
    &[""],
    &["そそ","そそぐ"],
    &["あらた","あらためる","あらたまる"],
    &["かわ"],
    &["まか","まかせる","まかす"],
    &[""],
    &[""],
    &["み"],
    &["かど"],
    &[""],
    &["ね"],
    &["さげる","さ"],
    &["いね","いな"],
    &["たがや","たがやす"],
    &["いとな","いとなむ","いとなみ"],
    &[""],
    &["まわ","まわる","まわす"],
    &["うたが","うたがう","うたがい"],
    &[""],
    &["つ","つく"],
    &[""],
    &["はし","は","はた"],
    &[""],
    &["すなわ","すなわち"],
    &["ゆび","さ","さす"],
    &["ね","あたい"],
    &["う","うれる"],
    &["あ","あける","あか","あかるい","あからむ","あき","あきらか"],
    &["やさ","やさしい","やすい"],
    &[""],
    &[""],
    &["かみ","かん","こう"],
    &["まぬか","まぬかれる"],
    &["さか","さかさ","さからう"],
    &[""],
    &["えら","えらい"],
    &["ゆえ"],
    &["おさ","おさめる","おさまる"],
    &["はや","はやい","はやまる","はやめる","はやく"],
    &["まち"],
    &[""],
    &["じ"],
    &[""],
    &["まつりごと"],
    &[""],
    &["かた","かたい","かたさ"],
    &["かつ","かつぐ","にな","になう"],
    &["う","うむ","うまれる","うぶ"],
    &["かえり","かえりみる","はぶ","はぶく"],
    &["ひる"],
    &["わ"],
    &["お","おいる","ふ","ふける"],
    &["に"],
    &["まず","まずしい","まずしさ"],
    &["とぼ","とぼしい","とぼしさ"],
    &["しる","しるす"],
    &["きよ","きよい","きよまる","きよめる"],
    &[""],
    &["つい","ついやす"],
    &["さ","さす","ささる","さし"],
    &[""],
    &[""],
    &[""],
    &["せ","せめる"],
    &["あやま","あやまる","あやまり"],
    &[""],
    &[""],
    &["ほね"],
    &["すこ","すこやかな"],
    &[""],
    &["こころよ","こころよい","こころよさ"],
    &["もと"],
    &["つ","つむ","つもる","つもり"],
    &["きわ","きわめる","きわまる","きわまり","きわみ"],
    &[""],
    &["おおやけ"],
    &["ひと","ひとしい"],
    &["ふし"],
    &["ひと","ひとり"],
    &["むか","むかえる"],
    &[""],
    &["かた"],
    &[""],
    &["せま","せまい","せば","せばめる","せばまる"],
    &["さ","さす","さし"],
    &["す","する"],
    &["き","きく","きき"],
    &[""],
    &[""],
    &["すえ"],
    &["も","もえる","もやす","もす"],
    &["うま","ま"],
    &["しか"],
    &["い","いきる","う","うまれる","うむ","お","は","はえる","はやす","なま","き"],
    &[""],
    &["ま","まける","まかす","まけ","お","おう"],
    &[""],
    &[""],
    &[""],
    &[""],
    &[""],
    &["みと","みとめる"],
    &["みちび","みちびく","みちびき"],
    &["かた","かためる","かたまる","かたまり","かたい"],
    &["とな","となり"],
    &[""],
    &["いくさ","たたか","たたかう","たたかわす"],
    &["やわ","やわらぐ","やわらげる","なご","なごむ","なごやか"],
    &[""],
    &["ま","まじる","まじり","まざる","まぜる"],
    &[""],
    &[""],
    &["すわ","すわる"],
    &["はな"],
    &["くび"],
    &["ふる","ふるえる","ふるえ"],
    &[""],
    &["わざわ","わざわい"],
    &["こ","こげる","こがす","こがれる","あせ","あせる","あせり"],
    &["やぶ","やぶる","やぶれる"],
    &["こわ","こわす","こわれる"],
    &["つく","つくる","つくり"],
    &["われ","わ"],
    &["さ","さる"],
    &[""],
    &["なみ","な","ならべる","なら","ならぶ","ならびに","ならび"],
    &["さか"],
    &["ひき"],
    &["みどり"],
    &["う","うえる","うわる"],
    &[""],
    &["もう","もうける"],
    &["きず","きずく"],
    &[""],
    &["あたた","あたたか","あたたかい","あたたまる","あたためる"],
    &["はな","はなやかな"],
    &["うじ"],
    &[""],
    &["まる","まるい"],
    &[""],
    &["かる","かるい","かろ","かろやかな"],
    &["から","からむ","からまる","からめる"],
    &["け"],
    &["ぬの"],
    &["かり","かりに"],
    &["くる","くるう","くるおしい","くるわす","くるわせる"],
    &["さわ","さわる"],
    &[""],
    &[""],
    &["やす","やすい","やすまる","やすらか"],
    &[""],
    &["は"],
    &["いた"],
    &[""],
    &["しば"],
    &["い","いる","お","おる"],
    &["うつ","うつす","うつる"],
    &["つと","つとめる","つとめて"],
    &["お","おる","おり","おれる"],
    &["か","かける","かく","かかす"],
    &["か","かう"],
    &["みな"],
    &["むし"],
    &["は"],
    &[""],
    &["ころ","ころがる","ころげる","ころがす","ころぶ"],
    &[""],
    &[""],
    &["かわ"],
    &[""],
    &["あや","あやしい","あやしむ"],
    &["う","うる"],
    &[""],
    &["す","すべる","すべて"],
    &["とり"],
    &[""],
    &[""],
    &["おさ","おさめる","おさまる"],
    &[""],
    &["こ","こえ","こえる","こやす","こやし"],
    &["くさ"],
    &["およ","およぐ","およぎ"],
    &["いぬ"],
    &["な","ない","なき","なくす","なくなる"],
    &["ゆた","ゆたか"],
    &[""],
    &["あ","あきる","あかす"],
    &["あぶら"],
    &["な"],
    &["たま"],
    &["へ","へる","へらす"],
    &["さら"],
    &["ゆ"],
    &["こ"],
    &["のぞ","のぞく"],
    &["ひか","ひかえる","ひかえ"],
    &["くら"],
    &[""],
    &["うつわ"],
    &["こ","こおる","こご","こごえる"],
    &[""],
    &["ぶた"],
    &["た","たえる","たやす","たつ"],
    &["まき"],
    &["わたし","わたくし"],
    &[""],
    &["たみ"],
    &["ほこ","ほこる","ほこり"],
    &["ほとけ"],
    &["ころ","ころす","ころし"],
    &["ふく","ふくむ","ふくみ","ふくめる"],
    &[""],
    &["す","すう"],
    &["すじ"],
    &[""],
    &[""],
    &["かた","かたる"],
    &["まよ","まよう","まよい"],
    &["あ","あてる"],
    &["いしずえ"],
    &[""],
    &["お","おす"],
    &["いた","いたる"],
    &["いな"],
    &[""],
    &[""],
    &["かこ","かこむ","かこう","かこい"],
    &["ひがし"],
    &[""],
    &["ふ","ふせる","ふす"],
    &[""],
    &["したが","したがう","したがえる"],
    &["い","いる","さ","さす"],
    &["みだ","みだれる","みだす","みだれ"],
    &["あば","あばく","あばれる"],
    &[""],
    &["や","やく","やき","やける"],
    &["あ","あむ","あみ"],
    &[""],
    &["くも"],
    &["かたよ","かたよる","かたより"],
    &["あま","あまい","あまさ","あまえる","あまえ","あまやかす"],
    &["ころも"],
    &["さわ","さわぐ","さわぎ","さわがす","さわがしい"],
    &["さと","さとる","さとり"],
    &["さ","さける"],
    &["かわ","かわく","かわき","かわかす"],
    &["さかずき"],
    &[""],
    &["そだ","そだつ","そだてる"],
    &["いの","いのる","いのり"],
    &["たが","たがい"],
    &["かしこ","かしこい"],
    &["な","なく","なる","ならす"],
    &[""],
    &["から","からい","からさ"],
    &["くだ"],
    &["くら","くらい","くらさ"],
    &["むすめ"],
    &["あなど","あなどる"],
    &["す","すむ","すまい"],
    &["はずかし","はずかしめ","はずかしめる"],
    &["ひ","ひく","ひき","はず","はずむ","たま"],
    &[""],
    &["かい"],
    &["いと"],
    &["たけ"],
    &["はやし"],
    &["は","わ","はね"],
    &["その"],
    &["いわ"],
    &[""],
    &[""],
    &["ゆみ"],
    &["うお","さかな"],
    &["と"],
    &["き","こ"],
    &["たに"],
    &["ほそい","ほそる","こまかい","ほそ","こま"],
    &["や"],
    &["てら"],
    &["ほし"],
    &["おや","した","したしい"],
    &["ふね","ふな"],
    &["いけ"],
    &["かたな"],
    &["むぎ"],
    &["こめ"],
    &["さと"],
    &[""],
    &[""],
    &["みや"],
    &[""],
    &["みなみ"],
    &["ち"],
    &["みずうみ"],
    &["みなと"],
    &["まつる","まつり"],
    &["さけ","さか"],
    &[""],
    &["か","かつ","かち","まさ","まさる"],
    &["ととの","ととのえる","ととのう"],
    &["はや","すみ","はやい","はやめる","すみやか"],
    &["すみ"],
    &["きた"],
    &["はしら"],
    &[""],
    &[""],
    &["ふえ"],
    &["な","なげる"],
    &["まめ"],
    &["のぼ","のぼる"],
    &["わらべ"],
    &["なみ"],
    &["はこ"],
    &["ふる","ふるい"],
    &["にし"],
    &["はた","はたけ"],
    &["ふで"],
    &["こおり","ひ"],
    &["ひつじ"],
    &["ひ"],
    &[""],
    &["さか","さかえる","は","はえる"],
    &["しお"],
    &[""],
    &["くわ","くわえる","くわわる"],
    &[""],
    &[""],
    &["め"],
    &[""],
    &[""],
    &[""],
    &[""],
    &["はた"],
    &["すく","すくう"],
    &["あ","あげる","あがる"],
    &["かがみ"],
    &["あざ"],
    &[""],
    &[""],
    &[""],
    &["そうろう"],
    &[""],
    &["ふだ"],
    &[""],
    &[""],
    &[""],
    &[""],
    &["この","このむ","このみ","す","すき","すく","よ","よい","い","いい"],
    &[""],
    &["や","やめる"],
    &["まわ","まわり"],
    &[""],
    &["まつ"],
    &["とな","となえる"],
    &["て","てる","てらす","てれる"],
    &[""],
    &["あさ","あさい"],
    &["くら"],
    &["お","おわり","おわらせる","おわる","おえる"],
    &["す"],
    &["まご"],
    &["お","おびる","おび"],
    &[""],
    &["なか"],
    &[""],
    &["きざ","きざす","きざし"],
    &[""],
    &["そこ"],
    &[""],
    &["はじ","はじまる","はじめる"],
    &["ひ"],
    &["うめ"],
    &[""],
    &[""],
    &["おっと"],
    &["つ","つける","つく","つき","づける","づく"],
    &[""],
    &["こ","こな"],
    &[""],
    &["つつ","つつむ","つつみ"],
    &["おお","おおきい"],
    &["あ","あびる","あびせる"],
    &[""],
    &["たと","たとえる"],
    &[""],
    &[""],
    &["よる","よ"],
    &["なが","ながい"],
    &[""],
    &[""],
    &["さくら"],
    &["よ","よん"],
    &[""],
    &["かわ"],
    &["す","すぎる","すごす","あやま","あやまつ","あやまち"],
    &[""],
    &[""],
    &["ひたい"],
    &[""],
    &["みき"],
    &["まなこ"],
    &["ひさ","ひさしい","ひさしぶり"],
    &["いつ","いつつ"],
    &[""],
    &["さかい"],
    &[""],
    &["む","むら","むれる","むれ","むらがる"],
    &["いさぎよ","いさぎよい"],
    &[""],
    &[""],
    &["き","きく"],
    &[""],
    &["つま"],
    &["む","むい","むっつ"],
    &[""],
    &["と","とる"],
    &[""],
    &["つみ"],
    &[""],
    &["す","すい"],
    &["こころざ","こころざす","こころざし"],
    &[""],
    &["えだ"],
    &[""],
];
