pub(crate) const KA_GLYPHS: [&'static str;1235] = [
    "一",
    "二",
    "十",
    "九",
    "七",
    "八",
    "力",
    "入",
    "人",
    "刀",
    "丁",
    "了",
    "上",
    "大",
    "下",
    "三",
    "口",
    "女",
    "小",
    "川",
    "夕",
    "千",
    "山",
    "子",
    "土",
    "弓",
    "万",
    "才",
    "工",
    "丸",
    "士",
    "久",
    "干",
    "亡",
    "己",
    "寸",
    "与",
    "々",
    "六",
    "犬",
    "五",
    "手",
    "火",
    "王",
    "水",
    "天",
    "中",
    "木",
    "円",
    "月",
    "日",
    "文",
    "切",
    "午",
    "止",
    "心",
    "元",
    "内",
    "友",
    "少",
    "父",
    "引",
    "太",
    "今",
    "戸",
    "牛",
    "公",
    "分",
    "方",
    "毛",
    "予",
    "化",
    "区",
    "反",
    "不",
    "欠",
    "夫",
    "氏",
    "比",
    "仏",
    "支",
    "収",
    "仁",
    "片",
    "尺",
    "匹",
    "乏",
    "介",
    "冗",
    "双",
    "互",
    "四",
    "左",
    "右",
    "白",
    "石",
    "目",
    "田",
    "正",
    "出",
    "玉",
    "立",
    "本",
    "生",
    "古",
    "半",
    "広",
    "北",
    "矢",
    "冬",
    "母",
    "外",
    "市",
    "兄",
    "用",
    "台",
    "氷",
    "写",
    "他",
    "由",
    "仕",
    "世",
    "平",
    "打",
    "主",
    "去",
    "央",
    "皿",
    "申",
    "号",
    "代",
    "皮",
    "礼",
    "民",
    "令",
    "史",
    "未",
    "失",
    "功",
    "末",
    "包",
    "加",
    "辺",
    "付",
    "司",
    "必",
    "以",
    "札",
    "可",
    "示",
    "刊",
    "圧",
    "旧",
    "布",
    "句",
    "永",
    "弁",
    "犯",
    "穴",
    "処",
    "冊",
    "庁",
    "幼",
    "甘",
    "払",
    "召",
    "巨",
    "占",
    "込",
    "耳",
    "休",
    "名",
    "年",
    "先",
    "竹",
    "糸",
    "百",
    "字",
    "気",
    "虫",
    "早",
    "同",
    "多",
    "池",
    "自",
    "西",
    "光",
    "毎",
    "考",
    "色",
    "肉",
    "当",
    "会",
    "米",
    "羽",
    "行",
    "寺",
    "回",
    "合",
    "交",
    "地",
    "列",
    "両",
    "有",
    "次",
    "全",
    "州",
    "羊",
    "血",
    "死",
    "式",
    "安",
    "向",
    "守",
    "曲",
    "各",
    "伝",
    "灯",
    "成",
    "老",
    "兆",
    "好",
    "衣",
    "印",
    "共",
    "争",
    "仲",
    "件",
    "舌",
    "在",
    "団",
    "仮",
    "因",
    "再",
    "任",
    "灰",
    "机",
    "后",
    "宇",
    "危",
    "存",
    "宅",
    "至",
    "吸",
    "缶",
    "忙",
    "肌",
    "芝",
    "汗",
    "汚",
    "叫",
    "舟",
    "企",
    "充",
    "伏",
    "男",
    "見",
    "赤",
    "町",
    "花",
    "村",
    "貝",
    "足",
    "車",
    "走",
    "売",
    "来",
    "声",
    "形",
    "汽",
    "麦",
    "谷",
    "図",
    "体",
    "作",
    "言",
    "近",
    "何",
    "弟",
    "社",
    "角",
    "里",
    "住",
    "決",
    "返",
    "坂",
    "役",
    "身",
    "投",
    "医",
    "究",
    "豆",
    "助",
    "対",
    "君",
    "局",
    "低",
    "冷",
    "良",
    "児",
    "初",
    "改",
    "兵",
    "完",
    "臣",
    "芸",
    "労",
    "希",
    "求",
    "位",
    "束",
    "材",
    "別",
    "囲",
    "告",
    "折",
    "努",
    "利",
    "快",
    "均",
    "条",
    "応",
    "技",
    "余",
    "判",
    "似",
    "防",
    "志",
    "災",
    "序",
    "状",
    "卵",
    "忘",
    "私",
    "否",
    "孝",
    "困",
    "系",
    "我",
    "批",
    "乱",
    "吹",
    "沈",
    "沢",
    "戻",
    "抗",
    "攻",
    "伺",
    "床",
    "狂",
    "含",
    "抑",
    "辛",
    "伸",
    "即",
    "抜",
    "迎",
    "更",
    "坊",
    "雨",
    "青",
    "林",
    "空",
    "金",
    "学",
    "岩",
    "東",
    "歩",
    "知",
    "門",
    "夜",
    "京",
    "国",
    "画",
    "店",
    "長",
    "姉",
    "明",
    "妹",
    "直",
    "油",
    "取",
    "波",
    "泳",
    "味",
    "始",
    "所",
    "物",
    "育",
    "者",
    "受",
    "使",
    "命",
    "板",
    "定",
    "具",
    "委",
    "放",
    "実",
    "幸",
    "岸",
    "和",
    "事",
    "昔",
    "注",
    "表",
    "服",
    "苦",
    "泣",
    "松",
    "刷",
    "果",
    "季",
    "底",
    "毒",
    "例",
    "牧",
    "卒",
    "協",
    "法",
    "芽",
    "径",
    "固",
    "治",
    "英",
    "的",
    "念",
    "周",
    "参",
    "典",
    "官",
    "府",
    "妻",
    "河",
    "招",
    "枝",
    "武",
    "価",
    "居",
    "往",
    "易",
    "制",
    "肥",
    "舎",
    "券",
    "効",
    "承",
    "性",
    "非",
    "述",
    "版",
    "乳",
    "沿",
    "若",
    "宝",
    "呼",
    "宙",
    "垂",
    "供",
    "延",
    "並",
    "忠",
    "拡",
    "枚",
    "宗",
    "担",
    "届",
    "拝",
    "刻",
    "泥",
    "押",
    "祈",
    "抵",
    "欧",
    "姓",
    "征",
    "肩",
    "依",
    "邪",
    "刺",
    "沸",
    "到",
    "杯",
    "怖",
    "卓",
    "免",
    "泊",
    "侮",
    "昇",
    "肯",
    "彼",
    "怪",
    "突",
    "抱",
    "況",
    "草",
    "音",
    "茶",
    "室",
    "星",
    "南",
    "思",
    "点",
    "春",
    "秋",
    "昼",
    "食",
    "海",
    "後",
    "活",
    "風",
    "前",
    "科",
    "首",
    "計",
    "待",
    "持",
    "送",
    "級",
    "重",
    "神",
    "県",
    "発",
    "乗",
    "度",
    "柱",
    "指",
    "研",
    "追",
    "品",
    "洋",
    "炭",
    "界",
    "秒",
    "屋",
    "美",
    "面",
    "急",
    "昭",
    "畑",
    "相",
    "負",
    "客",
    "係",
    "拾",
    "紀",
    "飛",
    "型",
    "軍",
    "建",
    "単",
    "浅",
    "胃",
    "祝",
    "昨",
    "変",
    "信",
    "要",
    "勇",
    "栄",
    "省",
    "約",
    "便",
    "限",
    "保",
    "祖",
    "則",
    "厚",
    "独",
    "迷",
    "逆",
    "査",
    "退",
    "故",
    "政",
    "染",
    "洗",
    "砂",
    "肺",
    "背",
    "城",
    "皇",
    "専",
    "奏",
    "看",
    "革",
    "映",
    "泉",
    "宣",
    "段",
    "巻",
    "派",
    "律",
    "紅",
    "姿",
    "皆",
    "封",
    "柔",
    "咲",
    "狭",
    "怒",
    "珍",
    "枯",
    "郊",
    "冒",
    "挟",
    "香",
    "荒",
    "逃",
    "校",
    "弱",
    "時",
    "高",
    "紙",
    "馬",
    "夏",
    "帰",
    "記",
    "書",
    "家",
    "原",
    "通",
    "根",
    "員",
    "島",
    "息",
    "旅",
    "勉",
    "配",
    "院",
    "起",
    "倍",
    "庭",
    "真",
    "速",
    "流",
    "荷",
    "病",
    "宮",
    "庫",
    "消",
    "酒",
    "席",
    "殺",
    "笑",
    "借",
    "粉",
    "郡",
    "特",
    "孫",
    "差",
    "脈",
    "害",
    "料",
    "案",
    "航",
    "帯",
    "残",
    "梅",
    "候",
    "浴",
    "訓",
    "挙",
    "徒",
    "倉",
    "連",
    "桜",
    "俵",
    "留",
    "破",
    "素",
    "師",
    "容",
    "造",
    "耕",
    "財",
    "益",
    "個",
    "能",
    "格",
    "恩",
    "修",
    "純",
    "骨",
    "射",
    "秘",
    "針",
    "蚕",
    "座",
    "俳",
    "値",
    "班",
    "胸",
    "党",
    "除",
    "将",
    "株",
    "従",
    "陛",
    "降",
    "展",
    "朗",
    "納",
    "討",
    "恋",
    "恐",
    "涙",
    "疲",
    "眠",
    "凍",
    "途",
    "脂",
    "埋",
    "娘",
    "辱",
    "恥",
    "哲",
    "捕",
    "捜",
    "畜",
    "般",
    "軒",
    "浮",
    "倒",
    "悩",
    "隻",
    "悟",
    "華",
    "週",
    "雪",
    "魚",
    "野",
    "黒",
    "強",
    "黄",
    "教",
    "船",
    "鳥",
    "理",
    "組",
    "細",
    "終",
    "動",
    "深",
    "球",
    "宿",
    "部",
    "問",
    "帳",
    "祭",
    "悪",
    "商",
    "族",
    "習",
    "章",
    "笛",
    "進",
    "転",
    "都",
    "第",
    "側",
    "唱",
    "堂",
    "巣",
    "陸",
    "停",
    "敗",
    "健",
    "救",
    "菜",
    "康",
    "票",
    "清",
    "産",
    "得",
    "望",
    "械",
    "貨",
    "副",
    "混",
    "眼",
    "貧",
    "授",
    "婦",
    "液",
    "許",
    "険",
    "接",
    "基",
    "務",
    "設",
    "率",
    "規",
    "移",
    "張",
    "現",
    "術",
    "断",
    "情",
    "経",
    "常",
    "責",
    "寄",
    "採",
    "略",
    "郵",
    "脳",
    "訪",
    "閉",
    "窓",
    "郷",
    "異",
    "欲",
    "探",
    "域",
    "頂",
    "済",
    "翌",
    "推",
    "訳",
    "密",
    "捨",
    "視",
    "盛",
    "著",
    "乾",
    "掘",
    "猫",
    "豚",
    "涼",
    "軟",
    "鹿",
    "婚",
    "掃",
    "盗",
    "粒",
    "瓶",
    "符",
    "掛",
    "紹",
    "袋",
    "頃",
    "描",
    "菓",
    "販",
    "控",
    "渉",
    "偏",
    "患",
    "脱",
    "偶",
    "森",
    "買",
    "場",
    "雲",
    "答",
    "絵",
    "朝",
    "道",
    "間",
    "晴",
    "番",
    "悲",
    "寒",
    "温",
    "湖",
    "落",
    "遊",
    "開",
    "植",
    "歯",
    "登",
    "短",
    "童",
    "軽",
    "飲",
    "集",
    "湯",
    "港",
    "等",
    "陽",
    "筆",
    "葉",
    "暑",
    "期",
    "運",
    "着",
    "勝",
    "階",
    "最",
    "満",
    "景",
    "散",
    "給",
    "結",
    "無",
    "飯",
    "隊",
    "街",
    "象",
    "費",
    "順",
    "貯",
    "博",
    "焼",
    "量",
    "喜",
    "覚",
    "達",
    "然",
    "税",
    "貸",
    "減",
    "属",
    "富",
    "賀",
    "提",
    "貿",
    "備",
    "証",
    "評",
    "測",
    "復",
    "絶",
    "検",
    "程",
    "営",
    "過",
    "報",
    "統",
    "善",
    "痛",
    "詞",
    "創",
    "勤",
    "敬",
    "晩",
    "割",
    "裁",
    "棒",
    "衆",
    "揮",
    "装",
    "尊",
    "補",
    "策",
    "筋",
    "貴",
    "就",
    "湾",
    "腕",
    "塔",
    "渡",
    "替",
    "奥",
    "硬",
    "筒",
    "遅",
    "隅",
    "募",
    "畳",
    "超",
    "堅",
    "越",
    "帽",
    "幾",
    "普",
    "喫",
    "換",
    "敢",
    "湿",
    "幅",
    "雇",
    "偉",
    "鈍",
    "焦",
    "弾",
    "絡",
    "御",
    "新",
    "話",
    "園",
    "電",
    "遠",
    "数",
    "楽",
    "鉄",
    "福",
    "暗",
    "感",
    "詩",
    "漢",
    "路",
    "意",
    "農",
    "想",
    "業",
    "働",
    "塩",
    "愛",
    "続",
    "置",
    "腸",
    "試",
    "極",
    "照",
    "戦",
    "辞",
    "節",
    "夢",
    "禁",
    "鉱",
    "墓",
    "飼",
    "準",
    "預",
    "罪",
    "損",
    "勢",
    "幹",
    "群",
    "豊",
    "資",
    "義",
    "解",
    "暖",
    "絹",
    "聖",
    "源",
    "盟",
    "蒸",
    "幕",
    "腹",
    "傷",
    "署",
    "裏",
    "賃",
    "誠",
    "零",
    "煙",
    "触",
    "靴",
    "較",
    "詳",
    "寝",
    "溶",
    "奨",
    "歳",
    "暇",
    "誇",
    "傾",
    "嫌",
    "勧",
    "飽",
    "塗",
    "腰",
    "跡",
    "詰",
    "違",
    "殿",
    "歌",
    "読",
    "算",
    "聞",
    "語",
    "鳴",
    "鼻",
    "緑",
    "銀",
    "駅",
    "練",
    "様",
    "静",
    "旗",
    "漁",
    "関",
    "説",
    "種",
    "察",
    "歴",
    "管",
    "像",
    "銭",
    "徳",
    "綿",
    "銅",
    "演",
    "増",
    "酸",
    "構",
    "態",
    "雑",
    "際",
    "総",
    "領",
    "製",
    "複",
    "境",
    "慣",
    "精",
    "適",
    "疑",
    "誌",
    "認",
    "誤",
    "穀",
    "磁",
    "層",
    "障",
    "暮",
    "模",
    "閣",
    "踊",
    "稲",
    "僕",
    "端",
    "髪",
    "滴",
    "概",
    "憎",
    "緒",
    "線",
    "箱",
    "横",
    "談",
    "調",
    "賞",
    "標",
    "養",
    "選",
    "億",
    "課",
    "熱",
    "輪",
    "器",
    "敵",
    "導",
    "確",
    "質",
    "賛",
    "編",
    "暴",
    "潔",
    "潮",
    "諸",
    "劇",
    "遺",
    "熟",
    "誕",
    "蔵",
    "論",
    "権",
    "膚",
    "舞",
    "鋭",
    "輩",
    "寮",
    "誰",
    "範",
    "影",
    "震",
    "趣",
    "駐",
    "緊",
    "頭",
    "親",
    "橋",
    "薬",
    "館",
    "整",
    "録",
    "積",
    "機",
    "燃",
    "輸",
    "築",
    "衛",
    "興",
    "糖",
    "鋼",
    "縦",
    "憲",
    "樹",
    "奮",
    "激",
    "操",
    "避",
    "曇",
    "隣",
    "濃",
    "磨",
    "頼",
    "賢",
    "壊",
    "薄",
    "講",
    "績",
    "謝",
    "縮",
    "覧",
    "厳",
    "優",
    "齢",
    "濯",
    "療",
    "燥",
    "顔",
    "曜",
    "題",
    "観",
    "験",
    "類",
    "織",
    "職",
    "額",
    "簡",
    "難",
    "臨",
    "穫",
    "騒",
    "離",
    "贈",
    "礎",
    "鏡",
    "願",
    "識",
    "臓",
    "警",
    "爆",
    "競",
    "議",
    "護",
    "籍",
    "響",
    "驚",
];

pub(crate) const KA_MEANINGS: [&'static str;1235] = [
    "one",
    "two",
    "ten",
    "nine",
    "seven",
    "eight",
    "power, force",
    "enter, put in",
    "human being, person",
    "sword",
    "town subsection, miscellaneous counter, even number",
    "finish, complete, understand",
    "up",
    "big",
    "down",
    "three",
    "mouth",
    "woman",
    "small",
    "river",
    "evening",
    "thousand",
    "mountain",
    "child, noun suffix",
    "soil, earth, ground",
    "bow",
    "ten thousand",
    "talent, counter for age",
    "manufacture, construction",
    "round, suffix for names of ships/people",
    "military man, profession suffix",
    "of long duration, long time",
    "dry",
    "decease, dead",
    "oneself, self",
    "a bit of, unit of length",
    "give, grant",
    "symbol of repetition",
    "six",
    "dog",
    "five",
    "hand",
    "fire",
    "king",
    "water",
    "heaven",
    "middle, in",
    "tree, wood",
    "circle, yen",
    "moon, month",
    "day, sun, Japan",
    "letter, writings, sentence",
    "cut",
    "noon",
    "stop",
    "heart",
    "origin",
    "inside",
    "friend",
    "little",
    "father",
    "draw, pull",
    "great, thick",
    "present, this",
    "door, household",
    "cattle, cow, ox",
    "public, official",
    "divide, part, minute",
    "direction, way, square",
    "hair, fur, feather, down",
    "in advance",
    "change into",
    "district, ward",
    "counter, anti-",
    "not",
    "lack",
    "husband, man laborer",
    "courtesy title, family name, lineage",
    "compare",
    "Buddha, France",
    "branch, support",
    "take in, obtain, collect",
    "benevolence, virtue, charity",
    "fragment, one (of two), part",
    "shaku (unit of length, about 30 cm), measure",
    "counter for animals",
    "scanty, meager, scarce",
    "mediate, be in between",
    "redundant, superfluous",
    "set of two, pair, both",
    "reciprocal, mutual, each other",
    "four",
    "left",
    "right",
    "white",
    "stone",
    "eye, item",
    "rice field",
    "right, correct",
    "go out, put out",
    "gem, jewel, ball",
    "stand, establish",
    "basis, book, this",
    "life, be born, student",
    "old",
    "half",
    "wide",
    "north",
    "arrow",
    "winter",
    "mother",
    "outside",
    "city, market",
    "older brother",
    "employ, things to do",
    "stand, counter for machinery",
    "ice",
    "copy",
    "other",
    "reason",
    "serve, do",
    "world, era",
    "flat, calm",
    "strike, hit",
    "main, master",
    "go away, leave",
    "center, middle",
    "plate, dish, saucer",
    "report, speak humbly",
    "number, designation, sign",
    "substitute, generation, charge",
    "skin, hide, rind, leather, bark",
    "etiquette, rite, courtesy, gratitude",
    "people",
    "command",
    "history",
    "not yet",
    "lose, slip",
    "merit, success",
    "last part, end",
    "wrap, encompass",
    "add, append, join",
    "vicinity, borderland",
    "attach, belong, apply",
    "officiate, administer",
    "without failure, surely",
    "to the ... of, by means of",
    "tag, bill, paper money, label",
    "",
    "show",
    "publish",
    "pressure",
    "former, old",
    "cloth, spread",
    "phrase, haiku, verse",
    "eternal, long, forever",
    "speak eloquently, speech, valve, petal",
    "offense, commit (a crime), violate, defy",
    "hole, cave",
    "deal with, treat",
    "counter for books",
    "government agency",
    "very young, infantile",
    "sweet",
    "sweep away, pay",
    "summon, wear, call",
    "huge, gigantic, large",
    "occupy, tell fortunes, hold",
    "move inward, include, be congested",
    "ear",
    "rest",
    "name",
    "year",
    "ahead",
    "bamboo",
    "thread",
    "hundred",
    "character",
    "gas, spirit",
    "insect, bug",
    "early, quick",
    "same",
    "many",
    "pond",
    "self",
    "west",
    "light",
    "every",
    "think",
    "color",
    "flesh, meat",
    "present, hit",
    "meet, society",
    "rice, America",
    "feather, wing",
    "go, act, line",
    "Buddhist temple",
    "turn round, time",
    "combine, fit, match",
    "intercourse, interchange",
    "ground, place, base, earth, land",
    "row",
    "both",
    "have",
    "next",
    "whole",
    "state",
    "sheep",
    "blood",
    "die, death",
    "style, ceremony",
    "peaceful, inexpensive",
    "turn toward, face toward",
    "protect, obey, babysitter",
    "curve, musical composition",
    "each",
    "transmit",
    "lamp, light",
    "form, achieve",
    "old, grow old",
    "omen, trillion",
    "like, favorable",
    "garment, clothes",
    "mark, seal, stamp",
    "joint, together, both",
    "contend, dispute, argue",
    "intermediary, personal relations, relation",
    "matter",
    "tongue",
    "be, exist",
    "body, group",
    "temporary, tentative",
    "cause, depend, be limited",
    "another time, again, twice",
    "office, duty, responsibility, leave to, entrust",
    "ash",
    "desk",
    "empress",
    "universe",
    "dangerous",
    "exist, know",
    "house, residence",
    "come to, arrive, lead to",
    "suck, breathe in, inhale, smoke",
    "can",
    "busy",
    "skin",
    "lawn",
    "sweat",
    "dirty",
    "shout, scream",
    "small boat, ship",
    "project, plan, attempt",
    "fill, allocate, assign",
    "prostrate, bend down, lie down, hide",
    "man",
    "see",
    "red",
    "town",
    "flower",
    "village",
    "shellfish, shell",
    "foot, suffice, add",
    "vehicle, wheel, car",
    "run",
    "sell",
    "come",
    "voice",
    "shape",
    "steam",
    "wheat",
    "valley",
    "drawing",
    "body, form",
    "make, work",
    "say, speech",
    "near, recent",
    "what, how many",
    "younger brother",
    "company, society",
    "angle, horn, corner",
    "countryside, league, hometown, village, town",
    "live",
    "decide",
    "return",
    "slope, hill",
    "service, role",
    "body, oneself",
    "throw, send in",
    "medicine, doctor",
    "study exhaustively",
    "bean, pea, miniature",
    "help, rescue, assistance",
    "oppose, opposite, against",
    "ruler, familiar title, you",
    "bureau, limited part, office",
    "low",
    "cold",
    "good",
    "child",
    "first",
    "reform",
    "soldier",
    "complete",
    "retainer",
    "art, craft",
    "labor, toil",
    "hope, aspire",
    "seek, demand",
    "rank, position",
    "tie up, bundle",
    "timber, material",
    "separate, another",
    "enclose, surround",
    "notify, tell, inform",
    "break off, fold, bend",
    "exert, make efforts, strive",
    "advantage, profit, be effective",
    "pleasant",
    "even, equal",
    "article, line",
    "respond, reply",
    "skill, technique",
    "remaining, excess",
    "stamp, seal, judge",
    "resemble, be similar",
    "prevent, protect from",
    "ambition, will, intention, aim",
    "calamity, disaster, misfortune",
    "introductory part, order, preface",
    "form, condition, letter, circumstances",
    "egg",
    "forget",
    "I, private",
    "say no, not",
    "filial piety",
    "be in trouble",
    "system, lineage",
    "self, I, my, our",
    "criticize, critique",
    "disordered, riot, confusion",
    "blow",
    "sink",
    "marsh",
    "return",
    "resist",
    "attack",
    "inquire",
    "bed, floor",
    "crazy, go mad",
    "contain, include",
    "suppress, control",
    "pungent, hard, spicy",
    "stretch, lengthen, grow",
    "immediate, namely, conform",
    "pull out, stand out, surpass",
    "welcome, go to meet, pick up",
    "renew, again, further, furthermore",
    "Buddhist priest, boy, colloquial person suffix",
    "rain",
    "blue",
    "woods, forest",
    "sky, air, empty",
    "metal, gold, money",
    "study, educational, institution",
    "rock",
    "east",
    "walk",
    "know",
    "gate",
    "night",
    "capital",
    "country",
    "picture",
    "shop, store",
    "long, chief",
    "older sister",
    "bright, clear",
    "younger sister",
    "straight, fix, repair",
    "oil",
    "take",
    "wave",
    "swim",
    "taste",
    "begin",
    "place",
    "thing",
    "raise",
    "person",
    "receive",
    "use, envoy",
    "order, life",
    "board, plate",
    "fix, determine",
    "implement, tool",
    "commit, entrust",
    "let go, release",
    "real, fruit, nut",
    "happiness, happy",
    "shore, bank, coast",
    "harmony, peace, Japan",
    "affair, abstract thing",
    "former times, antiquity",
    "pour, concentrate, note",
    "express, surface, table",
    "clothes, clothing, submit",
    "suffering, bitter, painful",
    "cry",
    "pine",
    "print",
    "fruit",
    "season",
    "bottom",
    "poison",
    "example",
    "pasture",
    "graduate",
    "cooperate",
    "law, method",
    "bud, sprout",
    "path, diameter",
    "solid, firm, hard",
    "govern, cure, heal",
    "distinguished, England",
    "target, adjectival suffix",
    "thought, desire, attention",
    "lap, periphery, circumference",
    "participate, visit a holy place",
    "standard work, canon, law code, ceremony",
    "government, government official, authorities",
    "urban prefecture, government office, capital city",
    "wife",
    "river",
    "invite",
    "branch",
    "military",
    "price, value",
    "reside, exist",
    "go on, proceed",
    "easy, exchange",
    "system, control",
    "fatten, fertilize",
    "building, quarters",
    "ticket, certificate",
    "effect, be effective",
    "agree to, hear, be told",
    "nature, sex, -ity, gender",
    "is not, mistake, non-, un-",
    "state, mention, refer to, explain",
    "printing plate, publishing, edition",
    "milk",
    "along",
    "young",
    "treasure",
    "call, invite",
    "space, midair",
    "hang down, drip",
    "offer, accompany",
    "extend, postpone",
    "line up, ordinary",
    "loyalty, faithfulness",
    "enlarge, extend, expand",
    "counter for flat things",
    "religious sect, religion",
    "bear on shoulder, undertake",
    "deliver, reach, report, notify",
    "worship, humbly, pray, venerate",
    "engrave, carve, chop up, point of time",
    "mud",
    "push",
    "pray",
    "resist",
    "Europe",
    "surname",
    "conquer",
    "shoulder",
    "depend on",
    "evil, wrong",
    "stab, pierce",
    "boil, seethe",
    "arrive, reach",
    "cup, sake cup",
    "fearful, scary",
    "table, prominent",
    "exempt, escape, avoid",
    "stay overnight, lodge",
    "insult, despise, scorn",
    "ascend, rise, be promoted",
    "assent, agree to, consent",
    "third person pronoun, that",
    "mysterious, strange, doubt",
    "dash, thrust, poke, strike",
    "hug, embrace, hold in one's arm",
    "conditions, situation, circumstances",
    "grass",
    "sound",
    "tea",
    "room",
    "star",
    "south",
    "think",
    "point",
    "spring",
    "autumn",
    "daytime",
    "eat, food",
    "sea, ocean",
    "after, back",
    "active, live",
    "wind, manner",
    "before, front",
    "subject of study",
    "head, neck, leader",
    "plan, compute, measure",
    "wait",
    "hold",
    "send",
    "grade",
    "heavy",
    "god, mind",
    "prefecture",
    "start, emit",
    "ride, get on",
    "degree, time",
    "pillar, pole",
    "finger, point",
    "sand, sharpen",
    "chase, pursue",
    "article, goods",
    "ocean, western",
    "coal, charcoal",
    "world, boundary",
    "second (of time)",
    "house, small shop",
    "beautiful, beauty",
    "face, mask, surface",
    "urgent, hurry, sudden",
    "luminous, bright, clear",
    "field, cultivated field",
    "mutual, phase, minister",
    "bear, lose, defeat, owe",
    "visitor, customer, guest",
    "connect, person in charge",
    "pick up, ten (in documents)",
    "era",
    "fly",
    "type",
    "army",
    "build",
    "single",
    "shallow",
    "stomach",
    "celebrate",
    "yesterday, last",
    "change, abnormal",
    "believe, trust, message",
    "important, summarize, require",
    "brave, be spirited, encouraged",
    "flourish, glory, honor, prosper",
    "ministry, save, reflect on, omit",
    "promise, contract, approximately",
    "mail, post, convenient, excrement",
    "limit",
    "preserve",
    "ancestor",
    "rule, law",
    "thick, kind",
    "alone, Germany",
    "perplexed, get lost",
    "reverse, be contrary",
    "look into, investigate",
    "retreat, drive away, repel",
    "old, the late, deceased, reason",
    "political administration, government, rule",
    "dye",
    "wash",
    "sand",
    "lung",
    "back",
    "castle",
    "emperor",
    "exclusive",
    "play music",
    "watch, care for",
    "leather, reform",
    "reflect, project",
    "spring, fountain",
    "proclaim, announce",
    "step, stairs, rank",
    "roll up, volume, wind",
    "sect, group, dispatch",
    "law, rhythm, regulation",
    "crimson, deep red, rouge",
    "figure, form, shape, appearance, posture",
    "all",
    "seal",
    "soft",
    "bloom",
    "narrow",
    "get angry",
    "rare, unusual",
    "wither, blight",
    "suburb, outskirts",
    "risk, brave, desecrate",
    "hold between, interpose",
    "sweet smell, fragrance, aroma",
    "wild, violent, rough, devastate",
    "escape, run away, set free, miss",
    "school",
    "weak",
    "time",
    "high",
    "paper",
    "horse",
    "summer",
    "return",
    "write down",
    "write, book",
    "house, family",
    "plain, original",
    "pass, communicate, commute",
    "root",
    "member",
    "island",
    "breath",
    "travel",
    "endeavor",
    "distribute",
    "institution",
    "rise, get up",
    "times, double",
    "court, garden",
    "true, genuine",
    "quick, fast, prompt",
    "flow, current, style",
    "load, cargo, baggage",
    "illness, disease, sickness",
    "royal palace, Shinto shrine",
    "storage chamber, storehouse",
    "extinguish, delete, disappear, erase",
    "alcoholic drink, sake, alcohol, liquor",
    "seat",
    "kill",
    "laugh",
    "borrow",
    "powder",
    "county",
    "special",
    "grandchild",
    "difference",
    "vein, pulse",
    "harm, damage",
    "fee, materials",
    "proposal, plan",
    "navigate, sail",
    "belt, wear, zone",
    "remain, ruthless",
    "Japanese apricot, plum",
    "season, seasonal weather",
    "bathe, pour over, shower",
    "instruct, teaching, precept",
    "nominate, noteworthy act, raise",
    "follower, vain, useless, on foot",
    "storehouse, warehouse, depository",
    "link, in succession, group, accompaniment",
    "cherry",
    "straw sack",
    "keep, stay",
    "break, tear",
    "element, plain",
    "master, teacher",
    "appearance, contain",
    "make, produce, build",
    "till, cultivate, plough",
    "wealth, property, money",
    "benefit, profit, advantage",
    "individual, general counter",
    "ability, function, Noh play",
    "norm, status, rank, standard",
    "grace, favor, debt of gratitude",
    "cultivate, repair, study, master",
    "pure",
    "bone",
    "shoot",
    "secret",
    "needle",
    "silkworm",
    "seat, sit",
    "haiku, actor",
    "value, price",
    "squad, group",
    "chest, breast",
    "party, faction",
    "rid of, exclude",
    "general, officer",
    "stock, share, stump",
    "follow, obey, conquer",
    "imperial palace steps",
    "descend, fall, get off",
    "unfold, display, expand",
    "cheerful, clear, bright",
    "pay, accept, put away, supply",
    "attack, study, examine, discuss",
    "love",
    "fear",
    "tear",
    "tired",
    "sleep",
    "freeze",
    "way, road",
    "fat, grease",
    "bury, fill up",
    "daughter, girl",
    "humiliate, disgrace",
    "shame, disgrace, shy",
    "sagacious, philosophy",
    "catch, grasp, capture",
    "look for, search, seek",
    "livestock, animal raising",
    "sort, carry, all, general",
    "eaves, counter for houses",
    "float, rise to the surface",
    "topple, collapse, fall over",
    "suffer, be troubled, afflict",
    "one of a pair, counter for ships",
    "awake to, perceive, be enlightened",
    "magnificent, flower, brilliant, China",
    "week",
    "snow",
    "fish",
    "field",
    "black",
    "strong",
    "yellow",
    "teach, religion",
    "ship, boat, vessel",
    "bird, fowl, poultry",
    "reason, basic principle",
    "organize, assemble, group, class, gang",
    "slender, minute, narrow, fine, detailed",
    "end",
    "move",
    "deep",
    "ball",
    "lodge",
    "section",
    "question",
    "notebook",
    "festival",
    "bad, evil",
    "trade, deal",
    "family, tribe",
    "learn, custom",
    "chapter, badge",
    "flute, whistle",
    "advance, progress",
    "turn, roll over, fall down",
    "capital (city), metropolis",
    "ordinal number prefix, degree",
    "side",
    "sing",
    "hall",
    "nest",
    "land",
    "halt, stop",
    "be defeated",
    "robust, healthy",
    "save, rescue, aid",
    "vegetable, greens",
    "healthy, composure",
    "vote, slip, ballot",
    "clear, purify, pure",
    "give birth, produce",
    "acquire, gain, profit",
    "hope, desire, look after",
    "mechanical contrivance, machine",
    "money, goods, property, freight",
    "secondary, assistant, accompany, supplement",
    "mix",
    "eye",
    "poor",
    "confer",
    "adult woman",
    "liquid, fluid",
    "permit, allow",
    "danger, steep",
    "contact, touch",
    "base, foundation",
    "duty, work, serve",
    "set up, establish",
    "rate, lead, command",
    "regulation, measure",
    "shift, move, transfer",
    "spread, strain, stretch",
    "actual, appear, present",
    "practical art, technique",
    "cut off, decision, refuse",
    "emotion, actual conditions",
    "pass through, manage, sutra",
    "normal, regular, ever-, always",
    "responsibility, blame, condemn",
    "contribute, draw near, approach",
    "pick, gather, take, accept, employ",
    "abridged, strategy, omit, abbreviate",
    "mail",
    "brain",
    "visit",
    "close",
    "window",
    "hometown",
    "different",
    "desire, want",
    "probe, search",
    "bounded area, region",
    "summit, receive humbly",
    "settle, relieve, finish",
    "the following, the next",
    "infer, deduce, recommend",
    "translate, sense, reason",
    "close, secret, dense, fine",
    "discard, throw away, abandon",
    "regard, consider, see, vision",
    "prosperous, flourish, serve food",
    "write, publish, author, remarkable, conspicuous",
    "dry",
    "dig",
    "cat",
    "pig",
    "cool",
    "soft",
    "deer",
    "marry",
    "sweep",
    "steal",
    "grain",
    "bottle",
    "symbol",
    "set, hang",
    "introduce",
    "bag, sack",
    "time, period",
    "depict, draw, paint",
    "confectionery, cake",
    "engage in sales, sell",
    "hold back, refrain from, wait",
    "have relation with, cross over",
    "one-sided, lean, incline, partial",
    "affected by disease, be ill, suffer",
    "remove, escape from, undress, drop out",
    "by chance, even number, (married)couple",
    "forest",
    "buy",
    "place",
    "cloud",
    "answer",
    "picture",
    "morning, dynasty",
    "way, street, road",
    "interval, between",
    "fine weather, clear up",
    "numerical order, watch",
    "sad",
    "cold",
    "warm",
    "lake",
    "fall",
    "play",
    "open",
    "plant",
    "tooth",
    "climb",
    "short",
    "child",
    "light",
    "drink",
    "collect",
    "hot water",
    "port, harbor",
    "equal, class",
    "sun, positive",
    "brush, writing",
    "leaf、foliage",
    "summer heat, hot",
    "term, time, expect",
    "carry, move, fortune",
    "put on, arrive, stick",
    "win, excel, be superior",
    "floor, rank, stair, level",
    "most",
    "full",
    "scene",
    "scatter",
    "supply, pay",
    "tie, conclude",
    "without, nothing",
    "cooked rice, meal",
    "party, squad, unit",
    "city quarter, street",
    "phenomenon, elephant",
    "expense, spend, waste",
    "order, obey, sequence",
    "lay-up, storage, store",
    "extensive, doctor, broad",
    "burn, roast, broil, bake",
    "quantity, measure, weigh",
    "happy, happiness, be glad",
    "perceive, remember, awake",
    "attain, suffix for plural",
    "modifier forming suffix, as",
    "tax",
    "lend",
    "decrease",
    "belong to",
    "rich, wealth",
    "congratulate",
    "present, submit",
    "trade, exchange",
    "provide, furnish",
    "prove, certificate",
    "comment, criticism",
    "measure, conjecture",
    "return to, be restored",
    "break off, come to an end",
    "examine, investigate, inspect",
    "extent, established form, degree",
    "manage, barracks, conduct business",
    "pass by, exceed, spend (time), err",
    "inform, require, news, report, reward",
    "unite, interconnected system, govern, control",
    "good",
    "pain",
    "words",
    "create",
    "service",
    "respect",
    "evening",
    "divide, split",
    "cut out, judge",
    "rod, stick, pole",
    "multitude, populace",
    "wield, direct, command",
    "dress, fit out, wear, pretend",
    "honor, respect, valuable, noble",
    "supplement, supply, make up for",
    "scheme, measure, plan, means, policy",
    "muscle, threadlike structure, line, plot",
    "noble, your honorable, valuable, respect",
    "set about, engage (in an occupation), employ",
    "bay",
    "arm",
    "tower",
    "cross",
    "replace",
    "inner part",
    "hard, firm",
    "tube, pipe",
    "slow, late",
    "nook, corner",
    "raise, invite",
    "tatami, fold up",
    "surpass, exceed",
    "firm, hard, solid",
    "go beyond, exceed",
    "headgear, cap, hat",
    "how many/much, some",
    "widespread, general",
    "ingest, drink, smoke",
    "exchange, substitute",
    "bold, boldly, daring",
    "damp, moisten, humid",
    "width, breadth, range",
    "employ, charter, hire",
    "great, eminent, remarkable",
    "dull, slow-witted, blunt, dim",
    "scorch, be impatient, yearn for",
    "bullet, spring back, bounce, play",
    "interlink, entwine, get entangled",
    "general honorific term, polite prefix",
    "new",
    "speak",
    "garden",
    "electricity",
    "distant, far",
    "number, count",
    "pleasure, comfortable, music",
    "iron",
    "fortune",
    "dark, dim",
    "sense, feel",
    "poetry, poem",
    "Chinese, fellow",
    "road, way, street",
    "mind, meaning, will",
    "farming, agriculture",
    "conceive, idea, thought",
    "work, business, industry",
    "work",
    "salt",
    "love",
    "continue",
    "place, put",
    "intestines",
    "try, attempt",
    "extreme, pole",
    "illuminate, shine",
    "war, fight, battle",
    "word, resign, quit",
    "joint, season of the year, section, melody",
    "dream",
    "prohibit",
    "ore, mine",
    "grave, tomb",
    "raise animals",
    "standard, semi-",
    "deposit, entrust",
    "crime, sin, guilt",
    "loss, damage, harm",
    "power, force, vigor",
    "tree trunk, main part",
    "group, herd, crowd, flock",
    "plentiful, abundant, rich",
    "resources, capital, funds",
    "righteousness, meaning, justice",
    "take apart, dissolve, clarify, untie",
    "warm",
    "silk",
    "holy, saint",
    "source, origin",
    "alliance, oath",
    "steam, evaporate",
    "curtain, shogunate",
    "belly, heart, mind",
    "wound, injury, hurt",
    "public-service station",
    "rear, reverse side, back",
    "wage, charges, fare, fee",
    "sincerity, truth, reality, fidelity",
    "zero",
    "smoke",
    "touch",
    "shoes",
    "compare",
    "detailed",
    "go to sleep",
    "dissolve, melt",
    "encourage, urge",
    "year, age suffix",
    "free time, leisure",
    "boast, be proud of",
    "incline, lean, tilt",
    "dislike, unpleasant",
    "urge, recommend, offer",
    "satiated, get tired of",
    "apply on a surface, paint",
    "waist, loins, hips, small of back",
    "trace, mark, remains, ruins, tracks",
    "reprimand, stuff, closely packed, cram",
    "differ, violate, different, be mistaken",
    "palace, hall, lord, formal honorific title",
    "song",
    "read",
    "calculate",
    "hear, listen, ask",
    "language, word, tell",
    "cry, sound, ring, sing, howl",
    "nose",
    "green",
    "silver",
    "station",
    "train, knead",
    "mode, way, formal title, manner",
    "quiet",
    "flag, banner",
    "fish, fishing",
    "concern, barrier",
    "explain, theory, opinion",
    "variety, seed, type, kind",
    "inspect, guess, surmise, judge",
    "personal history, passing of time",
    "pipe, exercise control, wind instrument, tube",
    "image",
    "money",
    "virtue",
    "cotton",
    "copper",
    "perform",
    "increase",
    "acid, oxygen",
    "construct, mind",
    "state, condition",
    "miscellaneous, mixed",
    "verge, occasion, edge",
    "total, general, overall",
    "territory, govern, rule",
    "manufacture, produce, make",
    "compound, double, multiple",
    "boundary, situation, border",
    "habitual practice, get used",
    "refine, essence, spirit, energy",
    "suitable, fit, suit, appropriate",
    "doubt",
    "magazine",
    "recognize",
    "mistake, err",
    "cereal, grain",
    "magnetism, magnetic",
    "stratum, layer, level",
    "hindrance, interfere with",
    "dusk, live, come to an end",
    "pattern, imitate, copy, model",
    "tower, tall magnificent building, cabinet",
    "dance",
    "rice plant",
    "I, manservant",
    "end, edge, side",
    "hair (on the head)",
    "drop, drip, trickle",
    "general, approximate",
    "hate, hatred, hateful",
    "outset, cord, strap, beginning, thong",
    "line",
    "box",
    "sideways, side",
    "talk, conversation",
    "tone, investigate, prepare",
    "prize",
    "mark, sign",
    "foster, rear",
    "choose, elect",
    "hundred million",
    "section, lesson",
    "heat, hot, fever",
    "wheel, ring, circle",
    "vessel, instrument, container, capacity",
    "enemy",
    "guide, lead",
    "certain, verify",
    "quality, matter",
    "praise, agreement",
    "compile, knit, edit",
    "violent, rage, expose",
    "immaculate, pure, righteous",
    "tide",
    "various",
    "drama, play",
    "leave behind",
    "mature, ripen",
    "be born, birth",
    "store, warehouse",
    "argue, theory, thesis",
    "right, power, authority",
    "skin",
    "dance",
    "sharp",
    "fellow",
    "dormitory",
    "who, someone",
    "model, example",
    "shadow, silhouette",
    "quake, shake, tremble",
    "flavor, taste, elegance",
    "stationed, stop, reside",
    "tight, exigent, tense, hard",
    "head",
    "parent, relatives, intimate",
    "bridge",
    "drug, medicine",
    "public building",
    "put in order, organize, prepared",
    "record",
    "accumulate",
    "machine, opportunity",
    "burn",
    "transport",
    "construct, build",
    "guard, defend, protect",
    "prosper, amusement, interest, revive",
    "sugar",
    "steel",
    "vertical",
    "constitution",
    "standing tree, bush",
    "rouse up, be enlivened",
    "violent, intense, fierce",
    "manipulate, operate, chastity",
    "avoid",
    "cloudy",
    "neighbor",
    "thick, dark",
    "polish, brush",
    "rely on, request",
    "wise, intelligent",
    "break down, destroy, damage",
    "thin, weak, light, fade, dilute",
    "lecture",
    "achievements",
    "thank, apologize, gratitude",
    "shrink",
    "look over, see",
    "severe, strict, solemn",
    "superior, actor, gentle, excel",
    "age",
    "rinse",
    "treat",
    "dry up",
    "face",
    "day of the week",
    "title, topic, problem",
    "view",
    "test",
    "kind, type, genus",
    "weave",
    "employment",
    "amount, forehead",
    "simple, brief",
    "difficult, disaster",
    "be present at, face, confront",
    "harvest",
    "clamor, make noise",
    "separate, leave, keep apart",
    "present a gift, give, bestow",
    "foundation stone, cornerstone",
    "mirror, optical instrument",
    "wish, ask a favor, request",
    "discriminate, knowledge, know",
    "internal organ",
    "guard against, warn, admonish",
    "explode",
    "compete",
    "discuss, legislative body, deliberation",
    "protect",
    "register",
    "reverberate, echo, resound, affect",
    "surprise",
];

pub(crate) const KA_ONYOMIS: [&'static [&'static str];1235] = [
    &["イチ"],
    &["ニ"],
    &["ジュウ"],
    &["キュウ","ク"],
    &["シチ"],
    &["ハチ"],
    &["リョク","リキ"],
    &["ニュウ"],
    &["ジン","ニン"],
    &["トウ"],
    &["チョウ","テイ"],
    &["リョウ"],
    &["ジョウ","ショウ"],
    &["ダイ","タイ"],
    &["カ","ゲ"],
    &["サン"],
    &["コウ","ク"],
    &["ジョ","ニョ","ニョウ"],
    &["ショウ"],
    &["セン"],
    &["セキ"],
    &["セン"],
    &["サン"],
    &["シ","ス"],
    &["ド","ト"],
    &["キュウ"],
    &["マン","バン"],
    &["サイ"],
    &["コウ","ク"],
    &["ガン"],
    &["シ"],
    &["キュウ","ク"],
    &["カン"],
    &["ボウ","モウ"],
    &["コ","キ"],
    &["スン"],
    &["ヨ"],
    &[""],
    &["ロク"],
    &["ケン"],
    &["ゴ"],
    &["シュ","ズ"],
    &["カ"],
    &["オウ"],
    &["スイ"],
    &["テン"],
    &["チュウ"],
    &["ボク","モク"],
    &["エン"],
    &["ゲツ","ガツ"],
    &["ニチ","ジツ"],
    &["ブン","モン"],
    &["セツ","サイ"],
    &["ゴ"],
    &["シ"],
    &["シン"],
    &["ゲン","ガン"],
    &["ナイ"],
    &["ユウ"],
    &["ショウ"],
    &["フ"],
    &["イン"],
    &["タイ","タ"],
    &["コン","キン"],
    &["コ"],
    &["ギュウ"],
    &["コウ"],
    &["ブン","フン","ブ"],
    &["ホウ"],
    &["モウ"],
    &["ヨ"],
    &["カ","ケ"],
    &["ク"],
    &["ハン","ホン","タン"],
    &["フ","ブ"],
    &["ケツ"],
    &["フ","フウ"],
    &["シ"],
    &["ヒ"],
    &["ブツ"],
    &["シ"],
    &["シュウ"],
    &["ジン","ニン"],
    &["ヘン"],
    &["シャク"],
    &["ヒツ"],
    &["ボウ"],
    &["カイ"],
    &["ジョウ"],
    &["ソウ"],
    &["ゴ"],
    &["シ"],
    &["サ"],
    &["ウ","ユウ"],
    &["ハク","ビャク"],
    &["セキ","シャク","コク"],
    &["モク"],
    &["デン"],
    &["セイ","ショウ"],
    &["シュツ","スイ"],
    &["ギョク"],
    &["リツ","リュウ"],
    &["ホン"],
    &["セイ","ショウ"],
    &["コ"],
    &["ハン"],
    &["コウ"],
    &["ホク"],
    &["シ"],
    &["トウ"],
    &["ボ"],
    &["ガイ","ゲ"],
    &["シ"],
    &["ケイ","キョウ"],
    &["ヨウ"],
    &["ダイ","タイ"],
    &["ヒョウ"],
    &["シャ"],
    &["タ"],
    &["ユ","ユウ","ユイ"],
    &["シ","ジ"],
    &["セイ","セ"],
    &["ヘイ","ビョウ"],
    &["ダ"],
    &["シュ","ス"],
    &["キョ","コ"],
    &["オウ"],
    &[""],
    &["シン"],
    &["ゴウ"],
    &["ダイ","タイ"],
    &["ヒ"],
    &["レイ","ライ"],
    &["ミン"],
    &["レイ"],
    &["シ"],
    &["ミ"],
    &["シツ"],
    &["コウ","ク"],
    &["マツ","バツ"],
    &["ホウ"],
    &["カ"],
    &["ヘン"],
    &["フ"],
    &["シ"],
    &["ヒツ"],
    &["イ"],
    &["サツ"],
    &["カ"],
    &["シ","ジ"],
    &["カン"],
    &["アツ"],
    &["キュウ"],
    &["フ"],
    &["ク"],
    &["エイ"],
    &["ベン"],
    &["ハン"],
    &["ケツ"],
    &["ショ"],
    &["サツ","サク"],
    &["チョウ"],
    &["ヨウ"],
    &["カン"],
    &["フツ"],
    &["ショウ"],
    &["キョ"],
    &["セン"],
    &[""],
    &["ジ"],
    &["キュウ"],
    &["メイ","ミョウ"],
    &["ネン"],
    &["セン"],
    &["チク"],
    &["シ"],
    &["ヒャク"],
    &["ジ"],
    &["キ","ケ"],
    &["チュウ"],
    &["ソウ"],
    &["ドウ"],
    &["タ"],
    &["チ"],
    &["ジ","シ"],
    &["セイ","サイ"],
    &["コウ"],
    &["マイ"],
    &["コウ"],
    &["ショク","シキ"],
    &["ニク"],
    &["トウ"],
    &["カイ","エ"],
    &["ベイ","マイ"],
    &["ウ"],
    &["コウ","ギョウ","アン"],
    &["ジ"],
    &["カイ","エ"],
    &["ゴウ","カ","ガ"],
    &["コウ"],
    &["チ","ジ"],
    &["レツ"],
    &["リョウ"],
    &["ユウ","ウ"],
    &["ジ","シ"],
    &["ゼン"],
    &["シュウ"],
    &["ヨウ"],
    &["ケツ"],
    &["シ"],
    &["シキ"],
    &["アン"],
    &["コウ"],
    &["シュ","ス"],
    &["キョク"],
    &["カク"],
    &["デン"],
    &["トウ"],
    &["セイ","ジョウ"],
    &["ロウ"],
    &["チョウ"],
    &["コウ"],
    &["イ"],
    &["イン"],
    &["キョウ"],
    &["ソウ"],
    &["チュウ"],
    &["ケン"],
    &["ゼツ"],
    &["ザイ"],
    &["ダン","トン"],
    &["カ","ケ"],
    &["イン"],
    &["サイ","サ"],
    &["ニン"],
    &["カイ"],
    &["キ"],
    &["コウ"],
    &["ウ"],
    &["キ"],
    &["ソン","ゾン"],
    &["タク"],
    &["シ"],
    &["キュウ"],
    &["カン"],
    &["ボウ"],
    &[""],
    &[""],
    &["カン"],
    &["オ"],
    &["キョウ"],
    &["シュウ"],
    &["キ"],
    &["ジュウ"],
    &["フク"],
    &["ダン","ナン"],
    &["ケン"],
    &["セキ","シャク"],
    &["チョウ"],
    &["カ"],
    &["ソン"],
    &[""],
    &["ソク"],
    &["シャ"],
    &["ソウ"],
    &["バイ"],
    &["ライ"],
    &["セイ","ショウ"],
    &["ケイ","ギョウ"],
    &["キ"],
    &["バク"],
    &["コク"],
    &["ズ","ト"],
    &["タイ","テイ"],
    &["サク","サ"],
    &["ゲン","ゴン"],
    &["キン"],
    &["カ"],
    &["テイ","ダイ","デ"],
    &["シャ"],
    &["カク"],
    &["リ"],
    &["ジュウ"],
    &["ケツ"],
    &["ヘン"],
    &["ハン"],
    &["ヤク","エキ"],
    &["シン"],
    &["トウ"],
    &["イ"],
    &["キュウ"],
    &["トウ","ズ"],
    &["ジョ"],
    &["タイ","ツイ"],
    &["クン"],
    &["キョク"],
    &["テイ"],
    &["レイ"],
    &["リョウ"],
    &["ジ","ニ"],
    &["ショ"],
    &["カイ"],
    &["ヘイ","ヒョウ"],
    &["カン"],
    &["シン","ジン"],
    &["ゲイ"],
    &["ロウ"],
    &["キ"],
    &["キュウ"],
    &["イ"],
    &["ソク"],
    &["ザイ"],
    &["ベツ"],
    &["イ"],
    &["コク"],
    &["セツ"],
    &["ド"],
    &["リ"],
    &["カイ"],
    &["キン"],
    &["ジョウ"],
    &["オウ","ノウ"],
    &["ギ"],
    &["ヨ"],
    &["ハン","バン"],
    &["ジ"],
    &["ボウ"],
    &["シ"],
    &["サイ"],
    &["ジョ"],
    &["ジョウ"],
    &["ラン"],
    &["ボウ"],
    &["シ"],
    &["ヒ"],
    &["コウ"],
    &["コン"],
    &["ケイ"],
    &["ガ"],
    &["ヒ"],
    &["ラン"],
    &["スイ"],
    &["チン"],
    &["タク"],
    &["レイ"],
    &["コウ"],
    &["コウ"],
    &["シ"],
    &["ショウ"],
    &["キョウ"],
    &["ガン"],
    &["ヨク"],
    &["シン"],
    &["シン"],
    &["ソク"],
    &["バツ"],
    &["ゲイ"],
    &["コウ"],
    &["ボウ","ボツ"],
    &["ウ"],
    &["セイ","ショウ"],
    &["リン"],
    &["クウ"],
    &["キン","コン"],
    &["ガク"],
    &["ガン"],
    &["トウ"],
    &["ホ","ブ","フ"],
    &["チ"],
    &["モン"],
    &["ヤ"],
    &["キョウ","ケイ","キン"],
    &["コク"],
    &["ガ","カク"],
    &["テン"],
    &["チョウ"],
    &["シ"],
    &["メイ","ミョウ"],
    &["マイ"],
    &["チョク","ジキ","ジカ"],
    &["ユ"],
    &["シュ"],
    &["ハ"],
    &["エイ"],
    &["ミ"],
    &["シ"],
    &["ショ"],
    &["ブツ","モツ"],
    &["イク"],
    &["シャ"],
    &["ジュ"],
    &["シ"],
    &["メイ","ミョウ"],
    &["ハン","バン"],
    &["テイ","ジョウ"],
    &["グ"],
    &["イ"],
    &["ホウ"],
    &["ジツ"],
    &["コウ"],
    &["ガン"],
    &["ワ","オ"],
    &["ジ","ズ"],
    &["セキ","シャク"],
    &["チュウ"],
    &["ヒョウ"],
    &["フク"],
    &["ク"],
    &["キュウ"],
    &["ショウ"],
    &["サツ"],
    &["カ"],
    &["キ"],
    &["テイ"],
    &["ドク"],
    &["レイ"],
    &["ボク"],
    &["ソツ"],
    &["キョウ"],
    &["ホウ","ハツ","ホツ"],
    &["ガ"],
    &["ケイ"],
    &["コ"],
    &["ジ","チ"],
    &["エイ"],
    &["テキ"],
    &["ネン"],
    &["シュウ"],
    &["サン"],
    &["テン"],
    &["カン"],
    &["フ"],
    &["サイ"],
    &["カ"],
    &["ショウ"],
    &["シ"],
    &["ブ","ム"],
    &["カ"],
    &["キョ"],
    &["オウ"],
    &["エキ","イ"],
    &["セイ"],
    &["ヒ"],
    &["シャ"],
    &["ケン"],
    &["コウ"],
    &["ショウ"],
    &["セイ","ショウ"],
    &["ヒ"],
    &["ジュツ"],
    &["ハン"],
    &["ニュウ"],
    &["エン"],
    &["ジャク","ニャク"],
    &["ホウ"],
    &["コ"],
    &["チュウ"],
    &["スイ"],
    &["キョウ","ク"],
    &["エン"],
    &["ヘイ"],
    &["チュウ"],
    &["カク"],
    &["マイ"],
    &["シュウ","ソウ"],
    &["タン"],
    &[""],
    &["ハイ"],
    &["コク"],
    &["デイ"],
    &["オウ"],
    &["キ"],
    &["テイ"],
    &["オウ"],
    &["セイ","ショウ"],
    &["セイ"],
    &["ケン"],
    &["イ","エ"],
    &["ジャ"],
    &["シ"],
    &["フツ"],
    &["トウ"],
    &["ハイ"],
    &["フ"],
    &["タク"],
    &["メン"],
    &["ハク"],
    &["ブ"],
    &["ショウ"],
    &["コウ"],
    &["ヒ"],
    &["カイ","ケ"],
    &["トツ"],
    &["ホウ"],
    &["キョウ"],
    &["ソウ"],
    &["オン","ノン","イン"],
    &["チャ","サ"],
    &["シツ"],
    &["セイ","ショウ"],
    &["ナン"],
    &["シ"],
    &["テン"],
    &["シュン"],
    &["シュウ"],
    &["チュウ"],
    &["ショク","ジキ"],
    &["カイ"],
    &["ゴ","コウ"],
    &["カツ"],
    &["フウ","フ"],
    &["ゼン"],
    &["カ"],
    &["シュ"],
    &["ケイ"],
    &["タイ"],
    &["ジ"],
    &["ソウ"],
    &["キュウ"],
    &["ジュウ","チョウ"],
    &["シン","ジン"],
    &["ケン"],
    &["ハツ","ホツ"],
    &["ジョウ"],
    &["ド","ト","タク"],
    &["チュウ"],
    &["シ"],
    &["ケン"],
    &["ツイ"],
    &["ヒン"],
    &["ヨウ"],
    &["タン"],
    &["カイ"],
    &["ビョウ"],
    &["オク"],
    &["ビ"],
    &["メン"],
    &["キュウ"],
    &["ショウ"],
    &[""],
    &["ソウ","ショウ"],
    &["フ"],
    &["キャク","カク"],
    &["ケイ"],
    &["シュウ","ジュウ"],
    &["キ"],
    &["ヒ"],
    &["ケイ"],
    &["グン"],
    &["ケン","コン"],
    &["タン"],
    &["セン"],
    &["イ"],
    &["シュク","シュウ"],
    &["サク"],
    &["ヘン"],
    &["シン"],
    &["ヨウ"],
    &["ユウ"],
    &["エイ"],
    &["セイ","ショウ"],
    &["ヤク"],
    &["ビン","ベン"],
    &["ゲン"],
    &["ホ"],
    &["ソ"],
    &["ソク"],
    &["コウ"],
    &["ドク"],
    &["メイ"],
    &["ギャク"],
    &["サ"],
    &["タイ"],
    &["コ"],
    &["セイ","ショウ"],
    &["セン"],
    &["セン"],
    &["サ","シャ"],
    &["ハイ"],
    &["ハイ"],
    &["ジョウ"],
    &["コウ","オウ"],
    &["セン"],
    &["ソウ"],
    &["カン"],
    &["カク"],
    &["エイ"],
    &["セン"],
    &["セン"],
    &["ダン"],
    &["カン"],
    &["ハ"],
    &["リツ","リチ"],
    &["コウ","ク"],
    &["シ"],
    &["カイ"],
    &["フウ","ホウ"],
    &["ジュウ","ニュウ"],
    &[""],
    &["キョウ"],
    &["ド"],
    &["チン"],
    &["コ"],
    &["コウ"],
    &["ボウ"],
    &["キョウ"],
    &["コウ","キョウ"],
    &["コウ"],
    &["トウ"],
    &["コウ"],
    &["ジャク"],
    &["ジ"],
    &["コウ"],
    &["シ"],
    &["バ"],
    &["カ","ゲ"],
    &["キ"],
    &["キ"],
    &["ショ"],
    &["カ","ケ"],
    &["ゲン"],
    &["ツウ","ツ"],
    &["コン"],
    &["イン"],
    &["トウ"],
    &["ソク"],
    &["リョ"],
    &["ベン"],
    &["ハイ"],
    &["イン"],
    &["キ"],
    &["バイ"],
    &["テイ"],
    &["シン"],
    &["ソク"],
    &["リュウ","ル"],
    &["カ"],
    &["ビョウ","ヘイ"],
    &["キュウ","グウ","ク"],
    &["コ","ク"],
    &["ショウ"],
    &["シュ"],
    &["セキ"],
    &["サツ","サイ","セツ"],
    &["ショウ"],
    &["シャク"],
    &["フン"],
    &["グン"],
    &["トク"],
    &["ソン"],
    &["サ"],
    &["ミャク"],
    &["ガイ"],
    &["リョウ"],
    &["アン"],
    &["コウ"],
    &["タイ"],
    &["ザン"],
    &["バイ"],
    &["コウ"],
    &["ヨク"],
    &["クン"],
    &["キョ"],
    &["ト"],
    &["ソウ"],
    &["レン"],
    &["オウ"],
    &["ヒョウ"],
    &["リュウ","ル"],
    &["ハ"],
    &["ソ","ス"],
    &["シ"],
    &["ヨウ"],
    &["ゾウ"],
    &["コウ"],
    &["ザイ","サイ"],
    &["エキ","ヤク"],
    &["コ","カ"],
    &["ノウ"],
    &["カク","コウ"],
    &["オン"],
    &["シュウ","シュ"],
    &["ジュン"],
    &["コツ"],
    &["シャ"],
    &["ヒ"],
    &["シン"],
    &["サン"],
    &["ザ"],
    &["ハイ"],
    &["チ"],
    &["ハン"],
    &["キョウ"],
    &["トウ"],
    &["ジョ","ジ"],
    &["ショウ"],
    &[""],
    &["ジュウ","ショウ","ジュ"],
    &["ヘイ"],
    &["コウ"],
    &["テン"],
    &["ロウ"],
    &["ノウ","ナツ","ナ","ナン","トウ"],
    &["トウ"],
    &["レン"],
    &["キョウ"],
    &["ルイ"],
    &["ヒ"],
    &["ミン"],
    &["トウ"],
    &["ト"],
    &["シ"],
    &["マイ"],
    &[""],
    &["ジョク"],
    &["チ"],
    &["テツ"],
    &["ホ"],
    &["ソウ"],
    &["チク"],
    &["ハン"],
    &["ケン"],
    &["フ"],
    &["トウ"],
    &["ノウ"],
    &["セキ"],
    &["ゴ"],
    &["カ","ケ"],
    &["シュウ"],
    &["セツ"],
    &["ギョ"],
    &["ヤ"],
    &["コク"],
    &["キョウ","ゴウ"],
    &["コウ","オウ"],
    &["キョウ"],
    &["セン"],
    &["チョウ"],
    &["リ"],
    &["ソ"],
    &["サイ"],
    &["シュウ"],
    &["ドウ"],
    &["シン"],
    &["キュウ"],
    &["シュク"],
    &["ブ"],
    &["モン"],
    &["チョウ"],
    &["サイ"],
    &["アク","オ"],
    &["ショウ"],
    &["ゾク"],
    &["シュウ"],
    &["ショウ"],
    &["テキ"],
    &["シン"],
    &["テン"],
    &["ト","ツ"],
    &["ダイ"],
    &["ソク"],
    &["ショウ"],
    &["ドウ"],
    &["ソウ"],
    &["リク"],
    &["テイ"],
    &["ハイ"],
    &["ケン"],
    &["キュウ"],
    &["サイ"],
    &["コウ"],
    &["ヒョウ"],
    &["セイ","ショウ"],
    &["サン"],
    &["トク"],
    &["ボウ","モウ"],
    &["カイ"],
    &["カ"],
    &["フク"],
    &["コン"],
    &["ガン","ゲン"],
    &["ヒン","ビン"],
    &["ジュ"],
    &["フ"],
    &["エキ"],
    &["キョ"],
    &["ケン"],
    &["セツ"],
    &["キ"],
    &["ム"],
    &["セツ"],
    &["ソツ","リツ"],
    &["キ"],
    &["イ"],
    &["チョウ"],
    &["ゲン"],
    &["ジュツ"],
    &["ダン"],
    &["ジョウ","セイ"],
    &["ケイ","キョウ"],
    &["ジョウ"],
    &["セキ"],
    &["キ"],
    &["サイ"],
    &["リャク"],
    &["ユウ"],
    &["ノウ"],
    &["ホウ"],
    &["ヘイ"],
    &["ソウ"],
    &["キョウ","ゴウ"],
    &["イ"],
    &["ヨク"],
    &["タン"],
    &["イキ"],
    &["チョウ"],
    &["サイ"],
    &["ヨク"],
    &["スイ"],
    &["ヤク"],
    &["ミツ"],
    &["シャ"],
    &["シ"],
    &["セイ","ジョウ"],
    &["チョ"],
    &["カン"],
    &["クツ"],
    &["ビョウ"],
    &["トン"],
    &["リョウ"],
    &["ナン"],
    &["ロク"],
    &["コン"],
    &["ソウ"],
    &["トウ"],
    &["リュウ"],
    &["ビン"],
    &["フ"],
    &[""],
    &["ショウ"],
    &["タイ"],
    &["ケイ"],
    &["ビョウ"],
    &["カ"],
    &["ハン"],
    &["コウ"],
    &["ショウ"],
    &["ヘン"],
    &["カン"],
    &["ダツ"],
    &["グウ"],
    &["シン"],
    &["バイ"],
    &["ジョウ"],
    &["ウン"],
    &["トウ"],
    &["カイ","エ"],
    &["チョウ"],
    &["ドウ","トウ"],
    &["カン","ケン"],
    &["セイ"],
    &["バン"],
    &["ヒ"],
    &["カン"],
    &["オン"],
    &["コ"],
    &["ラク"],
    &["ユウ","ユ"],
    &["カイ"],
    &["ショク"],
    &["シ"],
    &["トウ","ト"],
    &["タン"],
    &["ドウ"],
    &["ケイ"],
    &["イン"],
    &["シュウ"],
    &["トウ"],
    &["コウ"],
    &["トウ"],
    &["ヨウ"],
    &["ヒツ"],
    &["ヨウ"],
    &["ショ"],
    &["キ","ゴ"],
    &["ウン"],
    &["チャク","ジャク"],
    &["ショウ"],
    &["カイ"],
    &["サイ"],
    &["マン"],
    &["ケイ"],
    &["サン"],
    &["キュウ"],
    &["ケツ"],
    &["ム","ブ"],
    &["ハン"],
    &["タイ"],
    &["ガイ","カイ"],
    &["ショウ","ゾウ"],
    &["ヒ"],
    &["ジュン"],
    &["チョ"],
    &["ハク","バク"],
    &["ショウ"],
    &["リョウ"],
    &["キ"],
    &["カク"],
    &["タツ"],
    &["ゼン","ネン"],
    &["ゼイ"],
    &["タイ"],
    &["ゲン"],
    &["ゾク"],
    &["フ","フウ"],
    &["ガ"],
    &["テイ"],
    &["ボウ"],
    &["ビ"],
    &["ショウ"],
    &["ヒョウ"],
    &["ソク"],
    &["フク"],
    &["ゼツ"],
    &["ケン"],
    &["テイ"],
    &["エイ"],
    &["カ"],
    &["ホウ"],
    &["トウ"],
    &["ゼン"],
    &["ツウ"],
    &["シ"],
    &["ソウ"],
    &["キン","ゴン"],
    &["ケイ"],
    &["バン"],
    &["カツ"],
    &["サイ"],
    &["ボウ"],
    &["シュウ","シュ"],
    &["キ"],
    &["ソウ","ショウ"],
    &["ソン"],
    &["ホ"],
    &["サク"],
    &["キン"],
    &["キ"],
    &["シュウ","ジュ"],
    &["ワン"],
    &["ワン"],
    &["トウ"],
    &["ト"],
    &["タイ"],
    &["オウ"],
    &["コウ"],
    &["トウ"],
    &["チ"],
    &["グウ"],
    &["ボ"],
    &["ジョウ"],
    &["チョウ"],
    &["ケン"],
    &["エツ"],
    &["ボウ"],
    &["キ"],
    &["フ"],
    &["キツ"],
    &["カン"],
    &["カン"],
    &["シツ"],
    &["フク"],
    &["コ"],
    &["イ"],
    &["ドン"],
    &["ショウ"],
    &["ダン"],
    &["ラク"],
    &["ギョ","ゴ"],
    &["シン"],
    &["ワ"],
    &["エン"],
    &["デン"],
    &["エン","オン"],
    &["スウ","ス"],
    &["ガク","ラク"],
    &["テツ"],
    &["フク"],
    &["アン"],
    &["カン"],
    &["シ"],
    &["カン"],
    &["ロ"],
    &["イ"],
    &["ノウ"],
    &["ソウ","ソ"],
    &["ギョウ","ゴウ"],
    &["ドウ"],
    &["エン"],
    &["アイ"],
    &["ゾク"],
    &["チ"],
    &["チョウ"],
    &["シ"],
    &["キョク","ゴク"],
    &["ショウ"],
    &["セン"],
    &["ジ"],
    &["セツ","セチ"],
    &["ム"],
    &["キン"],
    &["コウ"],
    &["ボ"],
    &["シ"],
    &["ジュン"],
    &["ヨ"],
    &["ザイ"],
    &["ソン"],
    &["セイ"],
    &["カン"],
    &["グン"],
    &["ホウ"],
    &["シ"],
    &["ギ"],
    &["カイ","ゲ"],
    &["ダン"],
    &["ケン"],
    &["セイ"],
    &["ゲン"],
    &["メイ"],
    &["ジョウ"],
    &["マク","バク"],
    &["フク"],
    &["ショウ"],
    &["ショ"],
    &["リ"],
    &["チン"],
    &["セイ"],
    &["レイ"],
    &["エン"],
    &["ショク"],
    &["カ"],
    &["カク"],
    &["ショウ"],
    &["シン"],
    &["ヨウ"],
    &["ショウ"],
    &["サイ","セイ"],
    &["カ"],
    &["コ"],
    &["ケイ"],
    &["ケン"],
    &["カン"],
    &["ホウ"],
    &["ト"],
    &["ヨウ"],
    &["セキ"],
    &["キツ"],
    &["イ"],
    &["デン","テン"],
    &["カ"],
    &["ドク","トク","トウ"],
    &["サン"],
    &["ブン","モン"],
    &["ゴ"],
    &["メイ"],
    &["ビ"],
    &["リョク","ロク"],
    &["ギン"],
    &["エキ"],
    &["レン"],
    &["ヨウ"],
    &["セイ","ジョウ"],
    &["キ"],
    &["ギョ","リョウ"],
    &["カン"],
    &["セツ","ゼイ"],
    &["シュ"],
    &["サツ"],
    &["レキ"],
    &["カン"],
    &["ゾウ"],
    &["セン"],
    &["トク"],
    &["メン"],
    &["ドウ"],
    &["エン"],
    &["ゾウ"],
    &["サン"],
    &["コウ"],
    &["タイ"],
    &["ザツ","ゾウ"],
    &["サイ"],
    &["ソウ"],
    &["リョウ"],
    &["セイ"],
    &["フク"],
    &["キョウ","ケイ"],
    &["カン"],
    &["セイ","ショウ"],
    &["テキ"],
    &["ギ"],
    &["シ"],
    &["ニン"],
    &["ゴ"],
    &["コク"],
    &["ジ"],
    &["ソウ"],
    &["ショウ"],
    &["ボ"],
    &["モ","ボ"],
    &["カク"],
    &["ヨウ"],
    &["トウ"],
    &["ボク"],
    &["タン"],
    &["ハツ"],
    &["テキ"],
    &["ガイ"],
    &["ゾウ"],
    &["ショ","チョ"],
    &["セン"],
    &[""],
    &["オウ"],
    &["ダン"],
    &["チョウ"],
    &["ショウ"],
    &["ヒョウ"],
    &["ヨウ"],
    &["セン"],
    &["オク"],
    &["カ"],
    &["ネツ"],
    &["リン"],
    &["キ"],
    &["テキ"],
    &["ドウ"],
    &["カク"],
    &["シツ","シチ","チ"],
    &["サン"],
    &["ヘン"],
    &["ボウ","バク"],
    &["ケツ"],
    &["チョウ"],
    &["ショ"],
    &["ゲキ"],
    &["イ","ユイ"],
    &["ジュク"],
    &["タン"],
    &["ゾウ"],
    &["ロン"],
    &["ケン","ゴン"],
    &["フ"],
    &["ブ"],
    &["エイ"],
    &["ハイ"],
    &["リョウ"],
    &["スイ"],
    &["ハン"],
    &["エイ"],
    &["シン"],
    &["シュ"],
    &["チュウ"],
    &["キン"],
    &["トウ","ズ","ト"],
    &["シン"],
    &["キョウ"],
    &["ヤク"],
    &["カン"],
    &["セイ"],
    &["ロク"],
    &["セキ"],
    &["キ"],
    &["ネン"],
    &["ユ"],
    &["チク"],
    &["エイ"],
    &["コウ","キョウ"],
    &["トウ"],
    &["コウ"],
    &["ジュウ"],
    &["ケン"],
    &["ジュ"],
    &["フン"],
    &["ゲキ"],
    &["ソウ"],
    &["ヒ"],
    &["ドン"],
    &["リン"],
    &["ノウ"],
    &["マ"],
    &["ライ"],
    &["ケン"],
    &["カイ"],
    &["ハス"],
    &["コウ"],
    &["セキ"],
    &["シャ"],
    &["シュク"],
    &["ラン"],
    &["ゲン","ゴン"],
    &["ユウ"],
    &["レイ"],
    &["タク"],
    &["リョウ"],
    &["ソウ"],
    &["ガン"],
    &["ヨウ"],
    &["ダイ"],
    &["カン"],
    &["ケン"],
    &["ルイ"],
    &["ショク","シキ"],
    &["ショク"],
    &["ガク"],
    &["カン"],
    &["ナン"],
    &["リン"],
    &["カク"],
    &["ソウ"],
    &["リ"],
    &["ゾウ","ソウ"],
    &["ソ"],
    &["キョウ"],
    &["ガン"],
    &["シキ"],
    &["ゾウ"],
    &["ケイ"],
    &["バク"],
    &["キョウ","ケイ"],
    &["ギ"],
    &["ゴ"],
    &["セキ"],
    &["キョウ"],
    &["キョウ"],
];

pub(crate) const KA_KUNYOMIS: [&'static [&'static str];1235] = [
    &["ひと"],
    &["ふた","ふたつ","ふたり"],
    &["とお","と"],
    &["ここの","ここのつ"],
    &["なな","なの","ななつ"],
    &["や","よう","やっつ"],
    &["ちから"],
    &["い","はい","いり","いる","はいる","いれる","いれ"],
    &["ひと"],
    &["かたな"],
    &[""],
    &[""],
    &["うえ","うわ","かみ","あ","あげる","あがる","のぼ","のぼる"],
    &["おお","おおきい"],
    &["した","しも","さ","さがる","さげる","くだ","くだる","ください","お","おろす","おりる"],
    &["み","みっか","みっつ"],
    &["くち"],
    &["おんな","め"],
    &["ちい","ちいさい","こ","お"],
    &["かわ"],
    &["ゆう"],
    &["ち"],
    &["やま"],
    &["こ"],
    &["つち"],
    &["ゆみ"],
    &[""],
    &[""],
    &[""],
    &["まる","まるい","まるめる"],
    &[""],
    &["ひさ","ひさしい","ひさしぶり"],
    &["ほ","ひ","ほす","ほし","ひる"],
    &["な","ない","なき","なくす","なくなる"],
    &["おのれ"],
    &[""],
    &["あた","あたえる"],
    &["n/a"],
    &["む","むい","むっつ"],
    &["いぬ"],
    &["いつ","いつつ"],
    &["て","た"],
    &["ひ"],
    &[""],
    &["みず"],
    &["あめ","あま"],
    &["なか"],
    &["き","こ"],
    &["まる","まるい"],
    &["つき"],
    &["ひ","か"],
    &["ふみ"],
    &["き","きる","きり","きれる"],
    &[""],
    &["と","や","とめる","とまる","やむ","やめる"],
    &["こころ"],
    &["もと"],
    &["うち"],
    &["とも"],
    &["すく","すこ","すくない","すこし"],
    &["ちち"],
    &["ひ","ひく"],
    &["ふと","ふとる","ふとい","ふとった","ふとさ"],
    &["いま"],
    &["と"],
    &["うし"],
    &["おおやけ"],
    &["わ","わける","わかる","わかれる"],
    &["かた"],
    &["け"],
    &[""],
    &["ば","ばける","ばかす"],
    &[""],
    &["そ","そる","そらす"],
    &[""],
    &["か","かける","かく","かかす"],
    &["おっと"],
    &["うじ"],
    &["くらべる","くら"],
    &["ほとけ"],
    &["ささ","ささえる"],
    &["おさ","おさめる","おさまる"],
    &[""],
    &["かた"],
    &[""],
    &["ひき"],
    &["とぼ","とぼしい","とぼしさ"],
    &[""],
    &[""],
    &["ふた"],
    &["たが","たがい"],
    &["よ","よん"],
    &["ひだり"],
    &["みぎ"],
    &["しろ","しら","しろい"],
    &["いし"],
    &["め","ま"],
    &["た"],
    &["ただ","ただしい","ただす","まさ","まさに"],
    &["で","だ","でる","だす"],
    &["たま"],
    &["た","たて","たつ","たち","たてる"],
    &["もと"],
    &["い","いきる","う","うまれる","うむ","お","は","はえる","はやす","なま","き"],
    &["ふる","ふるい"],
    &["なか","なかば"],
    &["ひろ","ひろまる","ひろめる","ひろがる","ひろげる","ひろい","ひろさ"],
    &["きた"],
    &["や"],
    &["ふゆ"],
    &["はは"],
    &["そと","ほか","はず","はずす","はずれる"],
    &["いち"],
    &["あに"],
    &["もち","もちいる"],
    &[""],
    &["こおり","ひ"],
    &["うつ","うつす","うつる"],
    &[""],
    &["よし"],
    &["つか","つかえる"],
    &["よ"],
    &["たい","ひらたい","たいら","ひら"],
    &["うつ","うち"],
    &["ぬし","おも","おもに","あるじ"],
    &["さ","さる"],
    &[""],
    &["さら"],
    &["もう","もうす","もうし"],
    &[""],
    &["かわる","かわり","かえる","よ","しろ","か"],
    &["かわ"],
    &[""],
    &["たみ"],
    &[""],
    &[""],
    &["いま","ま","いまだ","まだ"],
    &["うしな","うしなう"],
    &[""],
    &["すえ"],
    &["つつ","つつむ","つつみ"],
    &["くわ","くわえる","くわわる"],
    &["あた","あたり","べ"],
    &["つ","つける","つく","つき","づける","づく"],
    &[""],
    &["かなら","かならず"],
    &["も","もって"],
    &["ふだ"],
    &[""],
    &["しめ","しめす"],
    &[""],
    &[""],
    &[""],
    &["ぬの"],
    &[""],
    &["なが","ながい"],
    &[""],
    &["おか","おかす"],
    &["あな"],
    &[""],
    &[""],
    &[""],
    &["おさない"],
    &["あま","あまい","あまさ","あまえる","あまえ","あまやかす"],
    &["はら","はらう","はらい"],
    &["め","めす"],
    &[""],
    &["し","うらな","しめる","うらなう"],
    &["こ","こむ","こめる"],
    &["みみ"],
    &["やす","やすむ","やすみ","やすめる"],
    &["な"],
    &["とし"],
    &["さき"],
    &["たけ"],
    &["いと"],
    &[""],
    &["あざ"],
    &[""],
    &["むし"],
    &["はや","はやい","はやまる","はやめる","はやく"],
    &["おな","おなじ","おなじく"],
    &["おお","おおい","おおく"],
    &["いけ"],
    &["みずか","おの","みずから","おのずから"],
    &["にし"],
    &["ひか","ひかる","ひかり"],
    &["ごと"],
    &["かんが","かんがえる","かんがえ"],
    &["いろ"],
    &[""],
    &["あ","あたり","あたる","あてる"],
    &["あ","あう"],
    &["こめ"],
    &["は","わ","はね"],
    &["い","いく","ゆ","ゆく","おこな","おこなう"],
    &["てら"],
    &["まわ","まわる","まわす"],
    &["あ","あう","あい","あわす","あわせる"],
    &["まじ","ま","か","まじわる","まじえる","まじる","まざる","まぜる","かう","かわす"],
    &[""],
    &[""],
    &[""],
    &["あ","ある"],
    &["つ","つぐ","つぎ"],
    &["まった","まったく","すべ","すべて"],
    &["す"],
    &["ひつじ"],
    &["ち"],
    &["し","しぬ","しに"],
    &[""],
    &["やす","やすい","やすまる","やすらか"],
    &["む","むく","むき","むける","むかう","むこう"],
    &["まも","もり","まもる","まもり"],
    &["ま","まがる","まげる"],
    &["おのおの"],
    &["つた","つたわる","つたえる","つたう","つたい"],
    &["ひ"],
    &["な","なる","なす"],
    &["お","おいる","ふ","ふける"],
    &["きざ","きざす","きざし"],
    &["この","このむ","このみ","す","すき","すく","よ","よい","い","いい"],
    &["ころも"],
    &["しるし"],
    &["とも"],
    &["あらそう","あらそい","あらそ"],
    &["なか"],
    &[""],
    &["した"],
    &["あ","ある"],
    &[""],
    &["かり","かりに"],
    &["よる","よ"],
    &["ふたた","ふたたび"],
    &["まか","まかせる","まかす"],
    &["はい"],
    &["つくえ"],
    &[""],
    &[""],
    &["あぶ","あや","あぶない","あやうい","あやぶむ","あやうく"],
    &[""],
    &[""],
    &["いた","いたる"],
    &["す","すう"],
    &[""],
    &["いそが","いそがしい"],
    &["はだ"],
    &["しば"],
    &["あせ"],
    &["けが","よご","きたな","けがす","けがれる","けがらわしい","よごす","よごれる","きたない"],
    &["さけ","さけぶ"],
    &["ふね","ふな"],
    &["くわだ","くわだてる"],
    &["あ","あてる"],
    &["ふ","ふせる","ふす"],
    &["おとこ"],
    &["み","みる","みえる","みせる"],
    &["あか","あかい","あからむ","あからめる"],
    &["まち"],
    &["はな"],
    &["むら"],
    &["かい"],
    &["あし","た","たる","たりる","たす"],
    &["くるま"],
    &["はし","はしる","はしり"],
    &["う","うる"],
    &["く","くる","きた","きたる"],
    &["こえ","こわ"],
    &["かた","かたち"],
    &[""],
    &["むぎ"],
    &["たに"],
    &["はか","はかる"],
    &["からだ"],
    &["つく","つくる","つくり"],
    &["い","いう","こと"],
    &["ちか","ちかい","ちかく"],
    &["なに","なん"],
    &["おとうと"],
    &["やしろ"],
    &["かど","つの"],
    &["さと"],
    &["す","すむ","すまい"],
    &["き","きめる","きまる"],
    &["かえ","かえす","かえる","かえり"],
    &["さか"],
    &[""],
    &["み"],
    &["な","なげる"],
    &[""],
    &["きわ","きわめる"],
    &["まめ"],
    &["たす","たすける","たすかる","すけ"],
    &[""],
    &["きみ"],
    &[""],
    &["ひく","ひくい","ひくまる","ひくめる"],
    &["つめ","ひ","さ","つめたい","ひえる","ひや","ひややか","ひやす","ひやかす","さめる","さます"],
    &["よ","い","よい","いい"],
    &[""],
    &["はじ","はつ","うい","そ","はじめて","はじめ","はつ","そめる"],
    &["あらた","あらためる","あらたまる"],
    &[""],
    &[""],
    &[""],
    &[""],
    &[""],
    &[""],
    &["もと","もとめる"],
    &["くらい"],
    &["たば","たばねる"],
    &[""],
    &["わか","わかれ","わかれる"],
    &["かこ","かこむ","かこう","かこい"],
    &["つ","つぐ","つげる"],
    &["お","おる","おり","おれる"],
    &["つと","つとめる","つとめて"],
    &["き","きく","きき"],
    &["こころよ","こころよい","こころよさ"],
    &[""],
    &[""],
    &[""],
    &["わざ"],
    &["あま","あまり","あまる","あます"],
    &[""],
    &["にる","に"],
    &["ふせ","ふせぐ"],
    &["こころざ","こころざす","こころざし"],
    &["わざわ","わざわい"],
    &[""],
    &[""],
    &["たまご"],
    &["わす","わすれる"],
    &["わたし","わたくし"],
    &["いな"],
    &[""],
    &["こま","こまる"],
    &[""],
    &["われ","わ"],
    &[""],
    &["みだ","みだれる","みだす","みだれ"],
    &["ふ","ふく"],
    &["しず","しずむ","しずめる"],
    &["さわ"],
    &["もど","もどす","もどる"],
    &[""],
    &["せめる","せ"],
    &["うかがう","うかがい","うかが"],
    &["とこ","ゆか"],
    &["くる","くるう","くるおしい","くるわす","くるわせる"],
    &["ふく","ふくむ","ふくみ","ふくめる"],
    &["おさえる","おさ"],
    &["から","からい","からさ"],
    &["の","のびる","のばす"],
    &["すなわ","すなわち"],
    &["ぬく","ぬき","ぬける","ぬかす","ぬかる","ぬ"],
    &["むか","むかえる"],
    &["さら","ふ","さらに","ふける","ふかす"],
    &[""],
    &["あめ","あま"],
    &["あお","あおい"],
    &["はやし"],
    &["そら","あ","から","むな","あく","あき","あける","から","むなしい","むなしさ"],
    &["かね","かな"],
    &["まな","まなぶ"],
    &["いわ"],
    &["ひがし"],
    &["ある","あゆ","あるく","あゆむ","あゆみ"],
    &["し","しる","しらす","しらせる"],
    &["かど"],
    &["よ","よる"],
    &[""],
    &["くに"],
    &[""],
    &["みせ"],
    &["なが","ながい"],
    &["あね"],
    &["あ","あける","あか","あかるい","あからむ","あき","あきらか"],
    &["いもうと"],
    &["ただ","ただす","なお","なおる","なおす"],
    &["あぶら"],
    &["と","とる","とり"],
    &["なみ"],
    &["およ","およぐ","およぎ"],
    &["あじ","あじわう","あじわい"],
    &["はじ","はじまる","はじめる"],
    &["ところ"],
    &["もの"],
    &["そだ","そだつ","そだてる"],
    &["もの"],
    &["う","うける","うかる"],
    &["つか","つかう","つかい"],
    &["いのち"],
    &["いた"],
    &["さだ","さだか","さだめる","さだまる"],
    &[""],
    &[""],
    &["はな","はなす","はなつ","はなれる"],
    &["み","みの","みのる","みのり"],
    &["さいわ","さいわい","さち","しあわ","しあわせ"],
    &["きし"],
    &["やわ","やわらぐ","やわらげる","なご","なごむ","なごやか"],
    &["こと"],
    &["むかし"],
    &["そそ","そそぐ"],
    &["おもて","あらわ","あらわす","あらわれる"],
    &[""],
    &["くる","にが","くるしい","くるしむ","くるしめる","にがい","にがる"],
    &["な","なく"],
    &["まつ"],
    &["す","する"],
    &["はたす","はてる","はて","は"],
    &[""],
    &["そこ"],
    &[""],
    &["たと","たとえる"],
    &["まき"],
    &[""],
    &[""],
    &[""],
    &["め"],
    &[""],
    &["かた","かためる","かたまる","かたまり","かたい"],
    &["おさ","なお","おさめる","おさまる","なおる","なおす"],
    &[""],
    &["まと"],
    &[""],
    &["まわ","まわり"],
    &["まいる","まい"],
    &[""],
    &[""],
    &[""],
    &["つま"],
    &["かわ"],
    &["まね","まねく","まねき"],
    &["えだ"],
    &[""],
    &["あたい"],
    &["い","いる","お","おる"],
    &[""],
    &["やさ","やさしい","やすい"],
    &[""],
    &["こ","こえ","こえる","こやす","こやし"],
    &[""],
    &[""],
    &["き","きく"],
    &["うけたまわ","うけたまわる"],
    &[""],
    &[""],
    &["の","のべる"],
    &[""],
    &["ちち","ち"],
    &["そ","そう"],
    &["わかい","わか","も","もし"],
    &["たから"],
    &["よ","よぶ"],
    &[""],
    &["た","たれる","たらす","たれ"],
    &["そな","とも","そなえ","そなえる"],
    &["のびる","のべる","のべ","のばす","の"],
    &["なみ","な","ならべる","なら","ならぶ","ならびに","ならび"],
    &[""],
    &[""],
    &[""],
    &[""],
    &["かつ","かつぐ","にな","になう"],
    &["とど","とどく","とどける"],
    &["おが","おがむ"],
    &["きざ","きざむ","きざみ"],
    &["どろ"],
    &["お","おす","おさえる"],
    &["いの","いのる","いのり"],
    &[""],
    &[""],
    &[""],
    &[""],
    &["かた"],
    &[""],
    &[""],
    &["さ","さす","ささる","さし"],
    &["わ","わく","わかす"],
    &["いた","いたる"],
    &["さかずき"],
    &["こわ","こわい","こわがる"],
    &[""],
    &["まぬか","まぬかれる"],
    &["とまる","とめる"],
    &["あなど","あなどる"],
    &["のぼ","のぼる"],
    &[""],
    &["かれ","かの"],
    &["あや","あやしい","あやしむ"],
    &["つ","つく"],
    &["だ","いだ","かか","だく","いだく","かかえる"],
    &[""],
    &["くさ"],
    &["おと","ね"],
    &[""],
    &["むろ"],
    &["ほし"],
    &["みなみ"],
    &["おも","おもう","おもい"],
    &[""],
    &["はる"],
    &["あき"],
    &["ひる"],
    &["く","くう","た","たべる"],
    &["うみ"],
    &["のち","うし","うしろ","あと","おく","おくれ"],
    &[""],
    &["かぜ","かざ"],
    &["まえ"],
    &[""],
    &["くび"],
    &["はか","はかる","はかり","はからう"],
    &["まつ","またせる"],
    &["も","もつ","もち"],
    &["おく","おくる"],
    &[""],
    &["え","おも","かさ","おもい","おもさ","おもり","おもたい","おもし","かさねる","かさなる"],
    &["かみ","かん","こう"],
    &[""],
    &["た","たつ"],
    &["の","のる","のり","のせる"],
    &["たび"],
    &["はしら"],
    &["ゆび","さ","さす"],
    &["と","とぐ"],
    &["おう","お"],
    &["しな"],
    &[""],
    &["すみ"],
    &[""],
    &[""],
    &["や"],
    &["うつく","うつくしい"],
    &["おも","おもて","つら"],
    &["いそ","いそぐ","いそぎ"],
    &[""],
    &["はた","はたけ"],
    &["あい"],
    &["ま","まける","まかす","まけ","お","おう"],
    &[""],
    &["かか","かかる","かかり","かかわる","かかわり"],
    &["ひろ","ひろう"],
    &[""],
    &["と","とぶ","とばす"],
    &["かた"],
    &[""],
    &["た","たつ","たてる","たて"],
    &[""],
    &["あさ","あさい"],
    &[""],
    &["いわ","いわう","いわい"],
    &[""],
    &["か","かわる","かわり","かえる"],
    &[""],
    &["い","かなめ","いる"],
    &["いさ","いさむ","いさましい"],
    &["さか","さかえる","は","はえる"],
    &["かえり","かえりみる","はぶ","はぶく"],
    &[""],
    &["たより","たよ"],
    &["かぎる","かぎり","かぎ"],
    &["たもつ","たも"],
    &[""],
    &[""],
    &["あつ","あつい"],
    &["ひと","ひとり"],
    &["まよ","まよう","まよい"],
    &["さか","さかさ","さからう"],
    &[""],
    &["しりぞ","しりぞく","しりぞける"],
    &["ゆえ"],
    &["まつりごと"],
    &["そ","し","そめる","ぞめ","そまる","しみる","しみ"],
    &["あらう","あら"],
    &["すな"],
    &[""],
    &["せ","せい","そむく","そむける"],
    &["しろ"],
    &[""],
    &["もっぱら","もっぱ"],
    &["かな","かなでる"],
    &[""],
    &["かわ"],
    &["うつ","は","うつる","うつす","はえる"],
    &["いずみ"],
    &[""],
    &[""],
    &["ま","まく","まき"],
    &[""],
    &[""],
    &["べに","くれない"],
    &["すがた"],
    &["みな"],
    &[""],
    &["やわ","やわらかい","やわな"],
    &["さ","さく"],
    &["せま","せまい","せば","せばめる","せばまる"],
    &["いか","おこ","いかる","おこる"],
    &["めずら","めずらしい"],
    &["か","かれる","からす"],
    &[""],
    &["おか","おかす"],
    &["はさ","はさむ","はさまる"],
    &["か","かお","かおり","かおる"],
    &["あら","あ","あらい","あらす","あれる"],
    &["に","のが","にげる","にがす","のがす","のがれる"],
    &[""],
    &["よわい","よわる","よわまる","よわめる","よわ"],
    &["とき"],
    &["たか","たかい","たかさ","たかまる","たかぶる","たかめる"],
    &["かみ"],
    &["うま","ま"],
    &["なつ"],
    &["かえ","かえる"],
    &["しる","しるす"],
    &["か","かく"],
    &["いえ","や"],
    &["はら"],
    &["とお","かよ","とおる","とおり","とおす","とおし","かよう"],
    &["ね"],
    &[""],
    &["しま"],
    &["いき"],
    &["たび"],
    &[""],
    &["くば","くばる"],
    &[""],
    &["お","おきる","おこす"],
    &[""],
    &["にわ"],
    &["ま"],
    &["はや","すみ","はやい","はやめる","すみやか"],
    &["なが","ながれる","ながれ","ながす"],
    &["に"],
    &["や","やむ","やみ","やまい"],
    &["みや"],
    &[""],
    &["き","け","きえる","けす"],
    &["さけ","さか"],
    &[""],
    &["ころ","ころす","ころし"],
    &["わら","え","わらう","わらい","えむ","えみ"],
    &["か","かりる"],
    &["こ","こな"],
    &[""],
    &[""],
    &["まご"],
    &["さ","さす","さし"],
    &[""],
    &[""],
    &[""],
    &[""],
    &[""],
    &["お","おびる","おび"],
    &["のこる","のこす","のこり","のこ"],
    &["うめ"],
    &["そうろう"],
    &["あ","あびる","あびせる"],
    &[""],
    &["あ","あげる","あがる"],
    &[""],
    &["くら"],
    &["つら","つ","つらなる","つらねる","つれる","つれ"],
    &["さくら"],
    &["たわら"],
    &["と","とど","とめる","とまる","とどまる","とどめる"],
    &["やぶ","やぶる","やぶれる"],
    &[""],
    &[""],
    &[""],
    &["つく","つくる","つくり"],
    &["たがや","たがやす"],
    &[""],
    &[""],
    &[""],
    &[""],
    &[""],
    &[""],
    &["おさ","おさめる","おさまる"],
    &[""],
    &["ほね"],
    &["い","いる","さ","さす"],
    &["ひ","ひめる"],
    &["はり"],
    &["かいこ"],
    &["すわ","すわる"],
    &[""],
    &["ね","あたい"],
    &[""],
    &["むね","むな"],
    &[""],
    &["のぞ","のぞく"],
    &[""],
    &["かぶ"],
    &["したが","したがう","したがえる"],
    &[""],
    &["お","ふ","おりる","おろす","ふる","ふり"],
    &[""],
    &["ほが","ほがらかな"],
    &["おさ"," おさめる","おさまる"],
    &["う","うつ"],
    &["こ","こう","こい","こいしい","こいする"],
    &["おそれる","おそる","おそろしい","おそ"],
    &["なみだ"],
    &["つか","つかれる","つかれ"],
    &["ねむ","ねむい","ねむる"],
    &["こ","こおる","こご","こごえる"],
    &[""],
    &["あぶら"],
    &["う","うめる","うまる","うもれる"],
    &["むすめ"],
    &["はずかし","はずかしめ","はずかしめる"],
    &["は","はじ","はじらう","はじらい","はじる","はずかしい"],
    &[""],
    &["と","つか","とらえる","とらわれる","とる","つかまえる","つかまる"],
    &["さが","さがす"],
    &[""],
    &[""],
    &["のき"],
    &["う","うく","うかれる","うかぶ","うかべる"],
    &["たおれる","たおす","たお"],
    &["なや","なやむ","なやみ","なやます"],
    &[""],
    &["さと","さとる","さとり"],
    &["はな","はなやかな"],
    &[""],
    &["ゆき"],
    &["うお","さかな"],
    &["の"],
    &["くろい","くろ"],
    &["つよ","つよい","つよめる","つよまる","し","しいる"],
    &["き","こ"],
    &["おし","おそ","おしえる","おそわる"],
    &["ふね","ふな"],
    &["とり"],
    &[""],
    &["く","くむ","くみ"],
    &["ほそい","ほそる","こまかい","ほそ","こま"],
    &["お","おわり","おわらせる","おわる","おえる"],
    &["うご","うごく","うごかす","うごき"],
    &["ふか","ふかい","ふかまる","ふかめる"],
    &["たま"],
    &["やど","やどる","やどす"],
    &[""],
    &["と","とう","とい","とん"],
    &[""],
    &["まつる","まつり"],
    &["わる","あ","わるい","わるさ","あし","あしき"],
    &["あきな","あきなう","あきない"],
    &[""],
    &["なら","ならう","ならい"],
    &[""],
    &["ふえ"],
    &["すす","すすむ","すすめる"],
    &["ころ","ころがる","ころげる","ころがす","ころぶ"],
    &["みやこ"],
    &[""],
    &["かわ"],
    &["とな","となえる"],
    &[""],
    &["す"],
    &[""],
    &[""],
    &["やぶれる","やぶ"],
    &["すこ","すこやかな"],
    &["すく","すくう"],
    &["な"],
    &[""],
    &[""],
    &["きよ","きよい","きよまる","きよめる"],
    &["う","うむ","うまれる","うぶ"],
    &["える","うる","え","う"],
    &["のぞ","のぞむ","のぞみ"],
    &[""],
    &[""],
    &[""],
    &["ま","まじる","まじり","まざる","まぜる"],
    &["まなこ"],
    &["まず","まずしい","まずしさ"],
    &["さず"," さずける","さずかる"],
    &[""],
    &[""],
    &["ゆる","ゆるす","ゆるし"],
    &["けわ","けわしい"],
    &["つ","つぐ"],
    &["もと","もとい"],
    &["つと","つとめる","つとまる"],
    &["もう","もうける"],
    &["ひきいる","ひき"],
    &[""],
    &["うつ","うつす","うつる"],
    &["はる","はり","は"],
    &["あらわ","あらわれる","あらわす"],
    &[""],
    &["た","ことわ","たつ","ことわる","ことわり"],
    &["なさ","なさけ"],
    &["へ","た","へる","たつ"],
    &["つね","とこ"],
    &["せ","せめる"],
    &["よ","よる","より","よせる"],
    &["と","とる"],
    &[""],
    &[""],
    &[""],
    &["おとずれる","たずねる","おとず","たず"],
    &["と","とじる","とざす","し","しめる","しまる"],
    &["まど"],
    &[""],
    &["こと","ことなる"],
    &["ほ","ほっする","ほしい"],
    &["さぐ","さが","さぐる","さがす"],
    &[""],
    &["いただ","いただく","いただき"],
    &["す","すむ","すみ","すます","すませる"],
    &[""],
    &["お","おす"],
    &["わけ"],
    &[""],
    &["す","すてる"],
    &[""],
    &["も","さか","もる","さかん","さかんな"],
    &["あらわす","いちじるしい","あらわ","いちじる"],
    &["かわ","かわく","かわき","かわかす"],
    &["ほ","ほる"],
    &["ねこ"],
    &["ぶた"],
    &["すず","すずしい","すずむ"],
    &["やわ","やわらかい"],
    &["しか"],
    &[""],
    &["は","はく"],
    &["ぬす","ぬすむ","ぬすみ"],
    &["つぶ"],
    &[""],
    &[""],
    &["か","かける","かけ","かかる","かかり"],
    &[""],
    &["ふくろ"],
    &["ころ"],
    &["えが","えがく"],
    &[""],
    &[""],
    &["ひか","ひかえる","ひかえ"],
    &[""],
    &["かたよ","かたよる","かたより"],
    &["わずら","わずらう"],
    &["ぬ","ぬぐ","ぬげる"],
    &[""],
    &["もり"],
    &["か","かう"],
    &["ば"],
    &["くも"],
    &["こた","こたえ","こたえる"],
    &[""],
    &["あさ"],
    &["みち"],
    &["あいだ","ま"],
    &["は","はれる","はれ","はらす"],
    &[""],
    &["かな","かなしい","かなしむ","かなしさ","かなしみ"],
    &["さむ","さむい"],
    &["あたた","あたたか","あたたかい","あたたまる","あたためる"],
    &["みずうみ"],
    &["お","おちる","おとす"],
    &["あそ","あそび","あそぶ"],
    &["ひら","ひらく","あ","あく","あける"],
    &["う","うえる","うわる"],
    &["は"],
    &["のぼ","のぼる"],
    &["みじか","みじかい"],
    &["わらべ"],
    &["かる","かるい","かろ","かろやかな"],
    &["の","のむ"],
    &["あつ","つど","あつまる","あつまり","あつめる","つどう","つどい"],
    &["ゆ"],
    &["みなと"],
    &["ひと","ひとしい"],
    &["ひ"],
    &["ふで"],
    &["は"],
    &["あつ","あつい","あつさ"],
    &[""],
    &["はこ","はこぶ"],
    &["き","つ","きる","きせる","つく"],
    &["か","かつ","かち","まさ","まさる"],
    &[""],
    &["もっと","もっとも"],
    &["み","みちる","みつ","みたす"],
    &[""],
    &["ち","ちる","ちらす","ちらかす","ちらかる","ちらばる","ちらばす"],
    &[""],
    &["むす","ゆ","むすぶ","ゆう","ゆわえる"],
    &["な","ない","なし","なくす","なくなる"],
    &["めし"],
    &[""],
    &["まち"],
    &[""],
    &["つい","ついやす"],
    &[""],
    &[""],
    &[""],
    &["や","やく","やき","やける"],
    &["はかる","はかり","はか"],
    &["よろこ","よろこぶ","よろこび","よろこばす"],
    &["おぼ","さ","おぼえる","さます","さめる"],
    &["たち"],
    &[""],
    &[""],
    &["か","かす","かし"],
    &["へ","へる","へらす"],
    &[""],
    &["と","とむ","とみ"],
    &[""],
    &["さげる","さ"],
    &[""],
    &["そな","そなえる","そなわる"],
    &[""],
    &[""],
    &["はか","はかる"],
    &[""],
    &["た","たえる","たやす","たつ"],
    &[""],
    &["ほど"],
    &["いとな","いとなむ","いとなみ"],
    &["す","すぎる","すごす","あやま","あやまつ","あやまち"],
    &["むく","むくい","むくいる","むくう"],
    &["す","すべる","すべて"],
    &["よ","よい"],
    &["いた","いたい","いたむ","いたましい","いためる","いたみ"],
    &[""],
    &[""],
    &["つと","つとめる","つとまる"],
    &["うやまう","うやまい","うやま"],
    &[""],
    &["わ","わる","わり","われる","さ","さく"],
    &["た","さば","たつ","さばく"],
    &[""],
    &[""],
    &[""],
    &["よそお","よそおう"],
    &["たっとい","たっとぶ","とうとい","とうとぶ","たっと","とうと"],
    &["おぎな","おぎなう"],
    &[""],
    &["すじ"],
    &["たっと","とうと","たっとい","とうとい"],
    &["つ","つく"],
    &[""],
    &["うで"],
    &[""],
    &["わた","わたる","わたす"],
    &["か","かわる","かえる"],
    &["おく"],
    &["かた","かたい"],
    &["つつ"],
    &["おく","おそ","おくれる","おくらす","おそい","おそく"],
    &["すみ"],
    &["つのる"],
    &["たた","たたむ","たたみ"],
    &["こ","こえる","こす"],
    &["かた","かたい","かたさ"],
    &["こ","こす","こえる"],
    &[""],
    &["いく","いくつ","いくら"],
    &[""],
    &[""],
    &["かえる","かわる","か"],
    &[""],
    &["しめ","しめる","しめす"],
    &["はば"],
    &["やと","やとう"],
    &["えら","えらい"],
    &["にぶ","にぶい","にぶる"],
    &["こ","こげる","こがす","こがれる","あせ","あせる","あせり"],
    &["ひ","ひく","ひき","はず","はずむ","たま"],
    &["から","からむ","からまる","からめる"],
    &["おん"],
    &["あら","あたら","あたらしい","あらた","にい"],
    &["はな","はなす","はなし"],
    &["その"],
    &[""],
    &["とお","とおい","とおく"],
    &["かず","かぞ","かぞえる"],
    &["たの","たのしむ","たのしい","たのしみ"],
    &[""],
    &[""],
    &["くら","くらい","くらさ"],
    &[""],
    &[""],
    &[""],
    &["じ"],
    &[""],
    &[""],
    &[""],
    &["わざ"],
    &["はたら","はたらく","はたらき"],
    &["しお"],
    &["いと","いとしい","いとおしむ"],
    &["つづ","つづく","つづける","つづき"],
    &["お","おく"],
    &[""],
    &["こころ","ため","こころみる","こころみ","ためす","ためし"],
    &["きわ","きわめる","きわまる","きわまり","きわみ"],
    &["て","てる","てらす","てれる"],
    &["いくさ","たたか","たたかう","たたかわす"],
    &["や","やめる"],
    &["ふし"],
    &["ゆめ"],
    &[""],
    &[""],
    &["はか"],
    &["か","かう"],
    &[""],
    &["あず","あずける","あずかる"],
    &["つみ"],
    &["そこ","そこねる","そこなう"],
    &["いきお","いきおい"],
    &["みき"],
    &["む","むら","むれる","むれ","むらがる"],
    &["ゆた","ゆたか"],
    &[""],
    &[""],
    &["と","とく","とかす","とける"],
    &["あたた","あたたかい","あたたまる","あたためる"],
    &["きぬ"],
    &[""],
    &["みなもと"],
    &[""],
    &["む","むす","むれる","むらす"],
    &[""],
    &["はら"],
    &["きず","いた","いたむ","いためる"],
    &[""],
    &["うら"],
    &[""],
    &["まこと"],
    &[""],
    &["けむ","けむる","けむい","けむり"],
    &["ふ","さわ","ふれる","さわる"],
    &["くつ"],
    &[""],
    &["くわ","くわしい"],
    &["ね","ねる","ねかす","ねかせる"],
    &["と","とける","とかす","とく"],
    &[""],
    &[""],
    &["ひま"],
    &["ほこ","ほこる","ほこり"],
    &["かたむ","かし","かたむける","かたむく","かしげる"],
    &["きら","きらう","きらい","いや","いやがる"],
    &["すす","すすめる"],
    &["あ","あきる","あかす"],
    &["ぬ","ぬる","ぬり"],
    &["こし"],
    &["あと"],
    &["つ","つめる","つまる","つむ"],
    &["ちが","ちがう","ちがえる"],
    &["との"],
    &["うた","うたう"],
    &["よ","よむ"],
    &[""],
    &["き","きく","きこえる"],
    &["かた","かたる"],
    &["な","なく","なる","ならす"],
    &["はな"],
    &["みどり"],
    &[""],
    &[""],
    &["ね","ねる","ねり"],
    &["さま"],
    &["しず","しずか","しずまる","しずめる"],
    &["はた"],
    &[""],
    &["せき","かか","かかわる"],
    &["と","とく"],
    &["たね"],
    &[""],
    &[""],
    &["くだ"],
    &[""],
    &["ぜに"],
    &[""],
    &["わた"],
    &[""],
    &[""],
    &["ま","ふ","ます","まし","ふえる","ふやす"],
    &["す","すい"],
    &["かま","かまえる","かまう"],
    &[""],
    &[""],
    &["きわ"],
    &[""],
    &[""],
    &[""],
    &[""],
    &["さかい"],
    &["なれる","ならす","な"],
    &[""],
    &[""],
    &["うたが","うたがう","うたがい"],
    &[""],
    &["みと","みとめる"],
    &["あやま","あやまる","あやまり"],
    &[""],
    &[""],
    &[""],
    &["さわ","さわる"],
    &["く","くれる","くらす"],
    &[""],
    &[""],
    &["おど","おどる","おどり"],
    &["いね","いな"],
    &[""],
    &["はし","は","はた"],
    &["かみ"],
    &["しずく","したた","したたる"],
    &[""],
    &["にく","にくむ","にくい","にくらしい","にくしみ"],
    &["お"],
    &[""],
    &["はこ"],
    &["よこ"],
    &[""],
    &["しら","ととの","しらべる","ととのえる","ととのう"],
    &[""],
    &[""],
    &["やしな","やしなう"],
    &["えら","えらぶ"],
    &[""],
    &[""],
    &["あつ","あつい"],
    &["わ"],
    &["うつわ"],
    &["かたき"],
    &["みちび","みちびく","みちびき"],
    &["たしか","たしかめる","たし"],
    &[""],
    &[""],
    &["あ","あむ","あみ"],
    &["あば","あばく","あばれる"],
    &["いさぎよ","いさぎよい"],
    &["しお"],
    &[""],
    &[""],
    &[""],
    &["う","うれる"],
    &[""],
    &["くら"],
    &[""],
    &[""],
    &[""],
    &["ま","まう","まい"],
    &["するど","するどい"],
    &[""],
    &[""],
    &["だれ"],
    &[""],
    &["かげ"],
    &["ふる","ふるえる","ふるえ"],
    &["おもむき"],
    &[""],
    &[""],
    &["あたま","かしら"],
    &["おや","した","したしい"],
    &["はし"],
    &["くすり"],
    &["たて"],
    &["ととの","ととのえる","ととのう"],
    &[""],
    &["つ","つむ","つもる","つもり"],
    &["はた"],
    &["も","もえる","もやす","もす"],
    &[""],
    &["きず","きずく"],
    &[""],
    &["おこ","おこる","おこす"],
    &[""],
    &["はがね"],
    &["たて"],
    &[""],
    &[""],
    &["ふる","ふるう"],
    &["はげ","はげしい"],
    &["みさお","あやつ","あやつる"],
    &["さ","さける"],
    &["くも","くもる","くもり"],
    &["とな","となり"],
    &["こ","こい","こさ"],
    &["みが","みがく"],
    &["たの","たのむ","たのもしい","たよ","たよる"],
    &["かしこ","かしこい"],
    &["こわ","こわす","こわれる"],
    &["うす","うすい","うすめる","うすまる","うすらぐ","うすれる"],
    &[""],
    &[""],
    &["あやまる","あやま"],
    &["ちぢ","ちぢむ","ちぢまる","ちぢめる","ちぢれる","ちぢらす"],
    &[""],
    &["おごそか","きびしい","おごそ","きび"],
    &["やさし","やさしさ","すぐれる","やさ","すぐ"],
    &[""],
    &[""],
    &[""],
    &[""],
    &["かお"],
    &[""],
    &[""],
    &[""],
    &[""],
    &[""],
    &["お","おる","おり"],
    &[""],
    &["ひたい"],
    &[""],
    &["かた","むずか","かたい","かたさ","むずかしい"],
    &["のぞ","のぞむ"],
    &[""],
    &["さわ","さわぐ","さわぎ","さわがす","さわがしい"],
    &["はなれる","はなす","はな"],
    &["おく","おくる"],
    &["いしずえ"],
    &["かがみ"],
    &["ねが","ねがう"],
    &[""],
    &[""],
    &[""],
    &[""],
    &["きそう","せる","きそ","せ"],
    &[""],
    &["まも","まもる"],
    &[""],
    &["ひび","ひびく","ひびき","ひびかす"],
    &["おどろ","おどろく","おどろかす"],
];
